spool on;
spool create_pretups_SCHEMA.log;

   CREATE USER {{ PRETUPS_SCHEMA_USER_NAME }} IDENTIFIED BY {{ PRETUPS_SCHEMA_PASSWORD }}
   DEFAULT TABLESPACE {{ PRETUPS_DEFAULT_TableSpace }}
   TEMPORARY TABLESPACE TEMP
   PROFILE {{ DB_USER_PROFILE_NAME }}
   ACCOUNT UNLOCK;
   CREATE DIRECTORY Dbdump_dir AS '{{ BASE_DIR }}/{{ Temp_Dir }}';
   GRANT READ, WRITE ON DIRECTORY Dbdump_dir TO {{ PRETUPS_SCHEMA_USER_NAME }}; 

spool off;
EOT
