---
########################################################
# Author           Date        Remarks
#------------    -----------  ---------
#Sadhan Kumar K  25-07-2016    Initial Creation
#
# This file Runs the role of Patch.
#########################################################

- name: DB PATCH INSTALLATION ROLE
  hosts: dbservers
  vars_files:
    - roles/vars/devVars.yml
  roles:
   - { role: dbShip, tags: dbShip}
