---
########################################################
# Author           Date        Remarks
#------------    -----------  ---------
#Sadhan Kumar K  25-07-2016    Initial Creation
#
# This file Runs the role of Patch.
#########################################################

- name: PATCH INSTALLATION ROLE
  hosts: appserver
  vars_files:
    - group_vars/USER_ENTRY.yml 
    - roles/vars/devVars.yml
  roles:
   - { role: doPatch, tags: doPatch}