---
- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Define nodejs_install_npm_user
  set_fact:
    nodejs_install_npm_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: nodejs_install_npm_user is not defined

- name: Create npm global directory
  file:
    path: "{{ npm_config_prefix }}"
    owner: "{{ nodejs_install_npm_user }}"
    group: "{{ nodejs_install_npm_user }}"
    state: directory
    mode: 0755

- name: Add npm_config_prefix bin directory to global $PATH.
  template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644

- name: Ensure npm global packages are installed.
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: true
    state: latest
  environment:
    NPM_CONFIG_PREFIX: "{{ npm_config_prefix }}"
    NODE_PATH: "{{ npm_config_prefix }}/lib/node_modules"
    NPM_CONFIG_UNSAFE_PERM: "{{ npm_config_unsafe_perm }}"
  with_items: "{{ nodejs_npm_global_packages }}"
  tags: ['skip_ansible_lint']

- name: Install packages defined in a given package.json.
  npm:
    path: "{{ nodejs_package_json_path }}"
  when: nodejs_package_json_path is defined and nodejs_package_json_path


- name: Create a node_pretups directory
  file:
    path: "{{ Tomcat_Path }}/node_pretups"
    state: directory
    owner: "{{ USER_NAME }}"
    group: "{{ GROUP_NAME }}"


- name: Move directory contents, git clone
  ansible.builtin.copy:
    src: node_pretups/.
    dest: "{{ Tomcat_Path }}/node_pretups/"
    owner: "{{ USER_NAME }}"
    group: "{{ GROUP_NAME }}"

- name: "let's make it work: npmstart.sh: replace the cd dir"
  lineinfile: dest="{{ Tomcat_Path }}/node_pretups/npmstart.sh" regexp='replace this' line='cd {{ Tomcat_Path }}/node_pretups/'



#- name: Execute the script
#  command: sh {{ Tomcat_Path }}/node_pretups/npmstart.sh