source <Tomcat-Path>/conf/pretups/commonLoadClassPath.sh
#Language setting for the SMS without this setting users will get the invalid Pos key
LANG=en_US; export LANG
PATH=$JAVA_HOME/bin:$CATALINA_HOME/bin:$PATH:.
BASH_ENV=$HOME/.bashrc
#JAVA_OPTS="-Xms32m -Xmx32m"; export JAVA_OPTS;

#CLASSPATH=$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/classes:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/activation.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/mail.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/ojdbc5.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/servlet.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/log4j-1.2.9.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/cos.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/struts-legacy.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/jxl.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/rsaexternal.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/edtftpj-1.5.4.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/struts2-core-2.0.6.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/struts-core-1.3.8.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/struts-faces-1.3.8.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/struts-el-1.3.8.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/struts-extras-1.3.8.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/struts-tiles-1.3.8.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/struts-taglib-1.3.8.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-beanutils-1.7.0.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-collections-3.1.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-digester-1.8.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-chain-1.1.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-digester-1.8.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-fileupload-1.1.1.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-io-1.1.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-logging-1.0.4.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-validator-1.3.1.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/jaxrpc-impl_1.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/saaj-api.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/jaxrpc-spi.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/jsr173_api.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/jaxrpc-api.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/activation.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/FastInfoset.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/mail.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/saaj-impl.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/jaxrpc-impl.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/axis.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/jaxrpc.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/saaj.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/commons-discovery-0.2.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/wsdl4j-1.5.1.jar:$CATALINA_HOME/webapps/pretups/WEB-INF/lib/alepokenyastub.jar:.

export BASH_ENV PATH CLASSPATH

#cd $CATALINA_HOME/webapps/pretups/WEB-INF/classes/
cd $CATALINA_HOME/webapps/pretups/WEB-INF/lib/

#java com/btsl/pretups/iat/processes/IATDWHFileCreation $CATALINA_HOME/webapps/pretups/WEB-INF/classes/configfiles/Constants.props $CATALINA_HOME/webapps/pretups/WEB-INF/classes/configfiles/LogConfig.props Y 

java -classpath pretupsCore.jar:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:$ com/btsl/pretups/iat/processes/IATDWHFileCreation $CATALINA_HOME/conf/pretups/Constants.props $CATALINA_HOME/conf/pretups/LogConfig.props Y 
