package com.btsl.pretups.master.businesslogic;

/**
 * @author satakshi.gaur
 *
 */
public class NetworkSummaryPostgresQry implements NetworkSummaryQry{
	
	@Override
	public StringBuilder loadNetworkSummaryDataListQry(){
		StringBuilder selectQueryBuff=null ;
		selectQueryBuff = new StringBuilder("SELECT EXTRACT (MONTH FROM TS.TRANS_DATE) AS MONTH, EXTRACT (YEAR FROM TS.TRANS_DATE) AS YEAR ,N.NETWORK_NAME,TS.GATEWAYCODE,C.CATEGORY_NAME,ST.NAME AS SERVICE_TYPE,SSM.SELECTOR_NAME,TS.INTERFACE_ID, SUM(TS.SUCCESS_COUNT) AS SUCCESS_COUNT, ");
		selectQueryBuff.append(" SUM(TS.ERROR_COUNT) AS ERROR_COUNT,SUM(TS.RECEIVER_TRANSFER_VALUE) AS RECEIVER_TRANSFER_VALUE, SUM(TS.ACCESS_FEE) AS ACCESS_FEE, SUM(TS.TAX_AMOUNT) AS TAX_AMOUNT, SUM(TS.ERROR_AMT) AS ERROR_AMT, SUM(TS.SUCCESS_AMT) AS SUCCESS_AMT ");
		selectQueryBuff.append(" FROM TRANSACTION_SUMMARY TS,NETWORKS N, SERVICE_TYPE ST,CATEGORIES C,SERVICE_TYPE_SELECTOR_MAPPING SSM ");
		selectQueryBuff.append(" WHERE TS.NETWORK_CODE=? AND N.NETWORK_CODE=TS.NETWORK_CODE AND C.CATEGORY_CODE=TS.CATEGORY AND ST.SERVICE_TYPE=TS.SERVICE_TYPE AND TS.SERVICE_TYPE=SSM.SERVICE_TYPE AND TS.SUB_SERVICE=SSM.SELECTOR_CODE AND TS.TRANS_DATE>=TO_DATE(?,'dd/mm/yy') ");
		selectQueryBuff.append(" AND TRANS_DATE<=(SELECT (date_trunc('MONTH', TO_DATE(?,'dd/mm/yy')) + INTERVAL '1 MONTH - 1 day')::date) ");
		selectQueryBuff.append(" GROUP BY EXTRACT (YEAR FROM TS.TRANS_DATE), EXTRACT (MONTH FROM TS.TRANS_DATE),N.NETWORK_NAME,TS.GATEWAYCODE,C.CATEGORY_NAME,ST.NAME,SSM.SELECTOR_NAME,TS.INTERFACE_ID");
		selectQueryBuff.append(" ORDER BY YEAR , MONTH ,N.NETWORK_NAME,TS.GATEWAYCODE,C.CATEGORY_NAME,ST.NAME,SSM.SELECTOR_NAME,TS.INTERFACE_ID");
	return selectQueryBuff;
	}

}
