


  ALTER TABLE ADJUSTMENTS ADD CONSTRAINT PK_ADJUSTMENTS PRIMARY KEY (ADJUSTMENT_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE C2S_TRANSFERS ADD CONSTRAINT TRANSFER_ID_PK PRIMARY KEY (TRANSFER_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE TRANSFER_ITEMS ADD CONSTRAINT PK_TRANSFER_ITEMS PRIMARY KEY (TRANSFER_ID, SNO)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SUBSCRIBER_TRANSFERS ADD PRIMARY KEY (TRANSFER_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE USER_WALLET_PRODUCT_MAPPING ADD PRIMARY KEY (NETWORK_CODE, PRODUCT_CODE, ACCOUNT_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE INTERFACE_NODE_DETAILS ADD CONSTRAINT INTERFACE_NODE_DETAILS_PK PRIMARY KEY (INTERFACE_ID, IP, PORT, SEQUENCE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORKS ADD PRIMARY KEY (NETWORK_CODE);

  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USER_BALANCES ADD CONSTRAINT PK_USER_BALANCES1 PRIMARY KEY (USER_ID, PRODUCT_CODE, NETWORK_CODE, NETWORK_CODE_FOR, BALANCE_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE BARRED_MSISDNS ADD CONSTRAINT PK_BARRED_MSISDNS_NEW PRIMARY KEY (MODULE, NETWORK_CODE, MSISDN, USER_TYPE, BARRED_TYPE, FOR_MSISDN)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE P2P_SUBSCRIBERS_COUNTERS ADD CONSTRAINT PK_USERID_MSISDN_SEVCTYPE PRIMARY KEY (USER_ID, MSISDN, SERVICE_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE DAILY_C2S_LMS_SUMMARY ADD CONSTRAINT DAILY_C2S_LMS_SUMMARY_PK1 PRIMARY KEY (TRANS_DATE, USER_ID, PRODUCT_CODE, LMS_PROFILE, VERSION)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE VOMS_TYPES ADD CONSTRAINT VOMS_TYPES_PK PRIMARY KEY (VOUCHER_TYPE)
  ;
  --TABLESPACE VOMS_INDEXES  ENABLE

  ALTER TABLE VOMS_VOUCHER_SUMMARY ADD CONSTRAINT PK_VOMS_VOUCHER_SUMMARY PRIMARY KEY (SUMMARY_DATE, PRODUCT_ID, PRODUCTION_NETWORK_CODE, USER_NETWORK_CODE)
  ;
  --TABLESPACE VOMS_INDEXES  ENABLE

  ALTER TABLE VOMS_VOUCHER_BATCH_SUMMARY ADD CONSTRAINT PK_VOMS_BATCH_SUMMARY PRIMARY KEY (BATCH_NO)
  ;
  --TABLESPACE VOMS_INDEXES  ENABLE

  ALTER TABLE VOMS_PRINT_BATCHES ADD CONSTRAINT PK_VOMS_PRINT_BATCHES PRIMARY KEY (PRINTER_BATCH_ID)
  ;
  --TABLESPACE VOMS_INDEXES  ENABLE

  ALTER TABLE VOMS_BATCHES ADD CONSTRAINT PK_VOMS_BATCHES PRIMARY KEY (BATCH_NO)
  ;
  --TABLESPACE VOMS_INDEXES  ENABLE

  ALTER TABLE VOMS_PRODUCT_CONSUMPTION ADD CONSTRAINT PK_VOMS_PRD_CONSUMP PRIMARY KEY (PRODUCT_CONSUMPTION_ID)
  ;
  --TABLESPACE VOMS_INDEXES  ENABLE

  ALTER TABLE VOMS_ACTIVE_PRODUCTS ADD CONSTRAINT PK_VOMS_ACT_PRD PRIMARY KEY (ACTIVE_PRODUCT_ID)
  ;
  --TABLESPACE VOMS_INDEXES  ENABLE

  ALTER TABLE VOMS_PRODUCTS ADD CONSTRAINT PK_VOMS_PRODUCTS PRIMARY KEY (PRODUCT_ID)
  ;
  --TABLESPACE VOMS_INDEXES  ENABLE

  ALTER TABLE VOMS_CATEGORIES ADD CONSTRAINT PK_VOMS_CATEGORIES PRIMARY KEY (CATEGORY_ID)
  ;
  --TABLESPACE VOMS_INDEXES  ENABLE

  ALTER TABLE FOC_BATCHES ADD CONSTRAINT PK_FOC_BATCHES PRIMARY KEY (BATCH_ID)
  ;
  --TABLESPACE P_C2SINDEX  ENABLE

  ALTER TABLE BATCHES ADD CONSTRAINT PK_BATCH PRIMARY KEY (BATCH_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE ACT_BONUS_SUBS_MAPPING ADD CONSTRAINT PK_ACT_BONUS_SUBS_MAP PRIMARY KEY (USER_ID, SUBSCRIBER_MSISDN)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE VAS_ITEMS ADD CONSTRAINT PK_VAS_ITEMS PRIMARY KEY (VAS_ITEM_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE VAS_CIRCLE_ITEM_PRICES ADD CONSTRAINT PK_VAS_CIRCLE_ITEM_PRICE PRIMARY KEY (VAS_ITEM_ID, VAS_CIRCLE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE VAS_CATEGORY_TYPES ADD CONSTRAINT PK_VAS_CATEGORY_TYPES PRIMARY KEY (VAS_CATEGORY_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE VAS_CATEGORIES ADD CONSTRAINT PK_VAS_CATEGORIES PRIMARY KEY (VAS_CATEGORY_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE VAS_BATCHES ADD CONSTRAINT PK_VAS_BATCH PRIMARY KEY (VAS_BATCH_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USER_TRANSFER_COUNTS ADD CONSTRAINT PK_USER_TRANSFER_COUNTS PRIMARY KEY (USER_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USER_SIM_SERVICES ADD CONSTRAINT PK_USER_SIM_SERVICES PRIMARY KEY (NETWORK_CODE, USER_TYPE, PROFILE, SIM_PROFILE_ID, POSITION, PRESENT_STATUS)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USER_SERVICES ADD CONSTRAINT PK_USER_SERVICES PRIMARY KEY (USER_ID, SERVICE_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USER_ROLES ADD CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE_CODE)
  
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USER_PRODUCT_TYPES ADD CONSTRAINT PK_USER_PRODUCT_TYPES PRIMARY KEY (USER_ID, PRODUCT_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USER_PHONES ADD CONSTRAINT PK_USER_PHONES PRIMARY KEY (USER_PHONES_ID)
 ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USER_GEOGRAPHIES ADD CONSTRAINT PK_USER_GEOGRAHIES PRIMARY KEY (USER_ID, GRPH_DOMAIN_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USER_DOMAINS ADD CONSTRAINT PK_USER_DOMAINS PRIMARY KEY (USER_ID, DOMAIN_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
 
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE TRANSFER_RULES ADD CONSTRAINT PK_TRANSFER_RULES_NEW PRIMARY KEY (MODULE, NETWORK_CODE, RECEIVER_SERVICE_CLASS_ID, RECEIVER_SUBSCRIBER_TYPE, SENDER_SERVICE_CLASS_ID, SENDER_SUBSCRIBER_TYPE, SUB_SERVICE, SERVICE_TYPE, RULE_LEVEL, GATEWAY_CODE, GRADE_CODE, CATEGORY_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE TRANSFER_PROFILE_PRODUCTS ADD CONSTRAINT PK_TRANSFER_PROFILE_PRODUCTS PRIMARY KEY (PROFILE_ID, PRODUCT_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE TRANSFER_PROFILE ADD CONSTRAINT PK_TRANSFER_PROFILE PRIMARY KEY (PROFILE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE TRANSACTION_LOAD ADD CONSTRAINT PK_TRANSACTION_LOAD PRIMARY KEY (INSTANCE_ID, NETWORK_CODE, INTERFACE_ID, SERVICE_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORK_SERVICES ADD CONSTRAINT PK_NETWORK_SERVICES PRIMARY KEY (MODULE_CODE, SERVICE_TYPE, RECEIVER_NETWORK, SENDER_NETWORK)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORK_PRODUCT_MAPPING ADD CONSTRAINT PK_NETWORK_PRODUCT_MAP PRIMARY KEY (NETWORK_CODE, PRODUCT_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORK_PREFIXES ADD CONSTRAINT PK_NETWORK_PREFERENCES PRIMARY KEY (PREFIX_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORK_PREFERENCES ADD CONSTRAINT PK_NETWORK_PREFER PRIMARY KEY (NETWORK_CODE, PREFERENCE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORK_LOAD ADD CONSTRAINT PK_NETWORK_LOAD PRIMARY KEY (INSTANCE_ID, NETWORK_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORK_INTERFACE_MODULES ADD CONSTRAINT PK_NETWORK_INTERFACE_MODULES PRIMARY KEY (NETWORK_CODE, MODULE, METHOD_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE MSISDN_USAGE_SUMMARY ADD CONSTRAINT PK_MSISDN_USG_SUM PRIMARY KEY (MONTH_YEAR, MONTH, MODULE, NETWORK_CODE, MSISDN, PREFIX_ID, SERVICE_TYPE, SUB_SERVICE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE MODULES ADD CONSTRAINT PK_MODULES PRIMARY KEY (MODULE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE MESSAGE_REQ_RESP_MAPPING ADD CONSTRAINT PK_MSG_REQ_RESP_MAP PRIMARY KEY (REQ_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE MESSAGE_GATEWAY_TYPES ADD CONSTRAINT PK_MSG_GATEWAY_TYPES PRIMARY KEY (GATEWAY_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE MESSAGE_GATEWAY_SUBTYPES ADD CONSTRAINT PK_MSGGTW_SUB_TYPE PRIMARY KEY (GATEWAY_TYPE, GATEWAY_SUBTYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE MESSAGE_GATEWAY ADD CONSTRAINT PK_MESSAGE_GATEWAY PRIMARY KEY (GATEWAY_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE MESSAGE_ARGUMENT ADD CONSTRAINT PK_MESSAGE_ARGUMENT PRIMARY KEY (MESSAGE_CODE, ARGUMENT)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE MESSAGES_MASTER ADD CONSTRAINT PK_MESSAGES_MASTER PRIMARY KEY (MESSAGE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE LOYALITY_ITEMS ADD CONSTRAINT LOYALITY_ITEMS_PK PRIMARY KEY (ITEM_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE LOW_BALANCE_ALERT ADD CONSTRAINT PK_LOW_BALANCE PRIMARY KEY (ALERT_SEND_ON_DATE, USER_ID, PRODUCT_CODE, ALERT_TO)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE LOOKUP_TYPES ADD CONSTRAINT PK_LOOKUP_TYPES PRIMARY KEY (LOOKUP_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE LOOKUPS ADD CONSTRAINT PK_LOOKUPS PRIMARY KEY (LOOKUP_CODE, LOOKUP_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE LOCALE_MASTER ADD CONSTRAINT PK_LOCALE_MASTER PRIMARY KEY (LANGUAGE, COUNTRY)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE LANG_MASTER ADD CONSTRAINT PK_LANG_MASTER PRIMARY KEY (LAND_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE KEY_VALUES ADD CONSTRAINT PK_KEY_VALUES PRIMARY KEY (TYPE, KEY)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE JOB_MASTER ADD CONSTRAINT PK_JOB_MASTER PRIMARY KEY (JOB_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE INTF_NTWRK_PRFX_MAPPING ADD CONSTRAINT PK_INTF_NTWRK_PRFX_MAPPING PRIMARY KEY (NETWORK_CODE, INTERFACE_ID, PREFIX_ID, ACTION, METHOD_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE INTERFACE_TYPES ADD CONSTRAINT PK_INTERFACE_TYPES PRIMARY KEY (INTERFACE_TYPE_ID)
  USING INDEX (CREATE UNIQUE INDEX PK_INTERFACE_TYPESD ON INTERFACE_TYPES (INTERFACE_TYPE_ID) 
  ;
  --TABLESPACE PRTP_DATA )  ENABLE

  ALTER TABLE INTERFACE_ROUTING_CONTROL ADD CONSTRAINT PK_INTERFACE_ROUTING_CONTROL PRIMARY KEY (INTERFACE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE INTERFACE_NETWORK_MAPPING ADD CONSTRAINT PK_INT_NET_MAP PRIMARY KEY (NETWORK_CODE, INTERFACE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE INTERFACES ADD CONSTRAINT PK_INTERFACES PRIMARY KEY (INTERFACE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE INSTANCE_LOAD ADD CONSTRAINT PK_INSTANCE_LOAD PRIMARY KEY (INSTANCE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE IDS ADD CONSTRAINT PK_ID_GENERATOR PRIMARY KEY (NETWORK_CODE, ID_TYPE, ID_YEAR)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE IAT_NW_SERVICE_MAPPING ADD CONSTRAINT PK_IAT_NW_SERVICE_MAPPING PRIMARY KEY (SERIAL_NUMBER)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE IAT_NW_COUNTRY_MAPPING ADD CONSTRAINT PK_IAT_NW_COUNTRY_MAPPING PRIMARY KEY (SERIAL_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE IAT_COUNTRY_MASTER ADD CONSTRAINT PK_IAT_MASTER PRIMARY KEY (COUNTRY_SERIAL_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE GROUP_TYPE_PROFILES ADD CONSTRAINT PK_GROUP_TYPE_PROFILES PRIMARY KEY (NETWORK_CODE, GROUP_TYPE, REQ_GATEWAY_TYPE, RES_GATEWAY_TYPE, TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE GROUP_TYPE_COUNTERS ADD CONSTRAINT PK_GROUP_TYPE_COUNTERS PRIMARY KEY (USER_ID, MSISDN, GROUP_TYPE, TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE GROUP_ROLES ADD CONSTRAINT PK_GROUP_ROLES PRIMARY KEY (GROUP_ROLE_CODE, ROLE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SOS_SETTLEMENT_FAIL_RECCORDS ADD CONSTRAINT PK_SOS_SETTLE_FAIL_REC PRIMARY KEY (TRANSACTION_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE SOS_MONTHLY_SUMMARY ADD CONSTRAINT PK_SOS_MTHLY_SUMM PRIMARY KEY (MONTH, YEAR, NETWORK_CODE)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE SOS_DAILY_SUMMARY ADD CONSTRAINT PK_SOS_DAILY_SUMMARY PRIMARY KEY (TRANSACTION_DATE, NETWORK_CODE)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE SMS_MASTER ADD CONSTRAINT PK_SMS_MASTER PRIMARY KEY (SMS_PARAM_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SLAB_MASTER ADD CONSTRAINT PK_SLAB_MASTER PRIMARY KEY (SLAB_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SKEY_TRANSFERS ADD CONSTRAINT PK_SKEY_TRANSFERS PRIMARY KEY (SENDER_ID, SENDER_MSISDN)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SIM_SERVICE_CATEGORIES ADD CONSTRAINT PK_SIM_SERVICE_CATEGORIES PRIMARY KEY (CATEGORY_CODE, MAJOR_VERSION, MINOR_VERSION, SERVICE_ID, SERVICE_SET_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SIM_SERVICES ADD CONSTRAINT PK_SIM_SERVICES PRIMARY KEY (SERVICE_SET_ID, SERVICE_ID, MAJOR_VERSION, MINOR_VERSION)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SIM_PROFILE ADD CONSTRAINT PK_SIM_PROFILE PRIMARY KEY (SIM_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SIM_IMAGE ADD CONSTRAINT PK_SIM_IMAGE PRIMARY KEY (MSISDN)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SIMVENDER_MASTER_KEY_MAPPING ADD CONSTRAINT PRIMARY PRIMARY KEY (SIM_VENDER_CODE, SIM_PROFILE_ID, NETWORK_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_TYPE_SELECTOR_MAPPING ADD CONSTRAINT PK_STYPE_SEL_MAPPING PRIMARY KEY (SNO)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_TYPE ADD CONSTRAINT PK_SERVICE_TYPE PRIMARY KEY (SERVICE_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_SET ADD CONSTRAINT PK_SERVICE_SET PRIMARY KEY (ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_PROVIDER_GROUPS ADD CONSTRAINT PK_SERVICE_PRO_GRP PRIMARY KEY (GROUP_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_PROVIDER ADD CONSTRAINT PK_SERVICE_PROVIDER PRIMARY KEY (GROUP_ID, SERVICE_PROVIDER_NAME)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_PAYMENT_MAPPING ADD CONSTRAINT PK_SERVICE_PAYMENT_MAPPING PRIMARY KEY (SERVICE_TYPE, PAYMENT_METHOD, SUBSCRIBER_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_KEYWORDS ADD CONSTRAINT PK_SERVICE_KEYWORDS PRIMARY KEY (SERVICE_KEYWORD_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_INTERFACE_ROUTING ADD CONSTRAINT PK_SERVICE_ROUTING PRIMARY KEY (NETWORK_CODE, SERVICE_TYPE, SENDER_SUBSCRIBER_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_CLASS_PREFERENCES ADD CONSTRAINT PK_SERVICE_CLASS_PREFERENCE PRIMARY KEY (MODULE, NETWORK_CODE, PREFERENCE_CODE, SERVICE_CLASS_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SERVICE_CLASSES ADD CONSTRAINT PK_SERVICE_CLASSES PRIMARY KEY (SERVICE_CLASS_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SELECTOR_AMOUNT_MAPPING ADD CONSTRAINT PK_SELECTOR_AMOUNT_MAPPING PRIMARY KEY (SERVICE_TYPE, SELECTOR_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SCHEDULED_BATCH_MASTER ADD CONSTRAINT PK_SCHEDULED_TRANS PRIMARY KEY (BATCH_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE ROUTING_CONTROL ADD CONSTRAINT PK_ROUTING_CONTROL PRIMARY KEY (NETWORK_CODE, SERVICE_TYPE, INTERFACE_CATEGORY)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE ROLES ADD CONSTRAINT PK_ROLES PRIMARY KEY (ROLE_CODE, DOMAIN_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE RES_MESSAGE_GATEWAY ADD CONSTRAINT PK_RES_MESSAGE_GATEWAY PRIMARY KEY (GATEWAY_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE RESTRICTED_MSISDNS ADD CONSTRAINT PK_RESCT_MSISDN PRIMARY KEY (OWNER_ID, MSISDN)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE REQ_MESSAGE_GATEWAY ADD CONSTRAINT PK_REQ_MESSAGE_GATEWAY PRIMARY KEY (GATEWAY_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE REG_INFO ADD CONSTRAINT PK_REG_INFO PRIMARY KEY (MSISDN, TRANSACTION_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE REGISTRATION_CONTROL ADD CONSTRAINT PK_REGISTRATION_CONTROL PRIMARY KEY (REGISTRATION_TYPE, NETWORK_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE PROFILE_SET_VERSION ADD CONSTRAINT PK_PSV PRIMARY KEY (SET_ID, VERSION)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE PROFILE_SET ADD CONSTRAINT PK_PSET PRIMARY KEY (SET_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE PREFIX_SERVICE_MAPPING ADD CONSTRAINT PK_PREFIX_SERVICE_MAP PRIMARY KEY (PREFIX_ID, SERVICE_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE POS_KEYS ADD CONSTRAINT PK_POS_KEYS PRIMARY KEY (ICC_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE POSTPAID_CUST_PAY_MASTER ADD CONSTRAINT PK_POST_CUST_MASTER PRIMARY KEY (QUEUE_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE POSTPAID_CONTROL_PARAMETERS ADD CONSTRAINT PK_POSTPAID_CONTROL_PAR PRIMARY KEY (MSISDN)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE PORTED_MSISDN ADD CONSTRAINT PK_PORTED_MSISDN PRIMARY KEY (MSISDN, SUBSCRIBER_TYPE, PORT_TYPE)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE PIN_PASSWORD_ALERT ADD CONSTRAINT PK_PIN_PWD_ALERT PRIMARY KEY (MOBILE_NO, MODULE_CODE, TYPE, CREATED_ON)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE PERIOD_MASTER ADD CONSTRAINT PK_PERIOD_MASTER PRIMARY KEY (PERIOD_ID, PERIOD_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE PAYMENT_METHOD_KEYWORD ADD CONSTRAINT PK_PAYMENT_METHOD_KEYWORD PRIMARY KEY (PAYMENT_METHOD_KEYWORD, SERVICE_TYPE, NETWORK_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE PAGE_ROLES ADD CONSTRAINT PK_PAGE_ROLES PRIMARY KEY (ROLE_CODE, PAGE_CODE)
 ;
  --TABLESPACE PRTP_DATA   ENABLE

  ALTER TABLE PAGES ADD CONSTRAINT PK_PAGES PRIMARY KEY (PAGE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE P2P_SUMMARY_DAILY ADD CONSTRAINT PK_P2P_SUMM_DLY PRIMARY KEY (TRANS_DATE, SENDER_NETWORK_CODE, RECEIVER_NETWORK_CODE, SERVICE_TYPE, SUB_SERVICE_TYPE, TRANSFER_CATEGORY)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE TABLES_PURGING ADD CONSTRAINT PK_TABLES_PURGING PRIMARY KEY (TABLE_NAME)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SYSTEM_PREFERENCES ADD CONSTRAINT PK_SYSTEM_PREFERENCES PRIMARY KEY (PREFERENCE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE WHITE_LIST ADD CONSTRAINT PK_WHITE_LIST PRIMARY KEY (MSISDN)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SOS_SUBSCRIBER_MONTHLY_SUMMARY ADD CONSTRAINT PK_SOS_SUBSCRIBER_MON_SUM PRIMARY KEY (SUBSCRIBER_MSISDN, MONTH, YEAR)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE SVC_SETOR_INTFC_MAPPING ADD CONSTRAINT PK_SVC_SETOR_INTFC_MAP PRIMARY KEY (SRV_SELECTOR_INTERFACE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SUB_LOOKUPS ADD CONSTRAINT PK_SUB_LOOKUPS PRIMARY KEY (SUB_LOOKUP_CODE, LOOKUP_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SUBSCRIBER_SELECTOR_MAPPING ADD CONSTRAINT PK_SUB_SEL_MAPPING PRIMARY KEY (SNO, MAPPING_TYPE, SENDER_SUBSCRIBER_TYPE, RECEIVER_SUBSCRIBER_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SUBSCRIBER_ROUTING ADD CONSTRAINT PK_SUBSCRIBER_ROUTING PRIMARY KEY (MSISDN, SUBSCRIBER_TYPE)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE CELL_IDS ADD CONSTRAINT PK_CELL_IDS PRIMARY KEY (CELL_ID, GROUP_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CELL_GROUPS ADD CONSTRAINT PK_CELL_GROUPS PRIMARY KEY (GROUP_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CATEGORY_ROLES ADD CONSTRAINT PK_CATEGORY_ROLES PRIMARY KEY (CATEGORY_CODE, ROLE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CATEGORY_REQ_GTW_TYPES ADD CONSTRAINT PK_CATEGORY_REQ_GTW_TYPES PRIMARY KEY (CATEGORY_CODE, GATEWAY_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CATEGORIES ADD CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORY_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CARD_GROUP_SUB_BON_ACC_DETAILS ADD CONSTRAINT PK_CARD_GRP_SUB_BON_ACC_DET PRIMARY KEY (CARD_GROUP_SET_ID, VERSION, CARD_GROUP_ID, BUNDLE_ID)
  USING INDEX (CREATE UNIQUE INDEX PK_CARD_GROUP_SUB_BON_ACC_DET ON CARD_GROUP_SUB_BON_ACC_DETAILS (CARD_GROUP_SET_ID, VERSION, CARD_GROUP_ID, BUNDLE_ID) 
  ;
  --TABLESPACE PRTP_DATA )  ENABLE

  ALTER TABLE CARD_GROUP_SET_VERSIONS ADD CONSTRAINT PK_CARD_GROUP_SET_VERSIONS PRIMARY KEY (CARD_GROUP_SET_ID, VERSION)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CARD_GROUP_SET ADD CONSTRAINT PK_CARD_GROUP_SET PRIMARY KEY (CARD_GROUP_SET_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CARD_GROUP_DETAILS ADD CONSTRAINT PK_CARD_GROUP_DEATILS PRIMARY KEY (CARD_GROUP_SET_ID, VERSION, CARD_GROUP_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CARD_DETAILS ADD CONSTRAINT PK_CARD_DETAILS PRIMARY KEY (USER_ID, CARD_NUMBER)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE C2S_SUB_DENOM_DETAILS ADD CONSTRAINT PK_C2S_SUB_DENOM PRIMARY KEY (TRANSFER_DATE, NETWORK_CODE, INTERFACE_ID, DENOMINATION_SLAB, SERVICE_TYPE, SERVICE_CLASS_ID, SERVICE_CLASS_CODE, SUB_SERVICE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE C2S_IAT_TRANSFER_ITEMS ADD CONSTRAINT PK_C2S_IAT_TRANSFER_ITEMS PRIMARY KEY (TRANSFER_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE C2C_BATCH_ITEMS ADD CONSTRAINT PK_C2C_BATCH_ITEMS PRIMARY KEY (BATCH_DETAIL_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE C2C_BATCHES ADD CONSTRAINT PK_C2C_BATCHES PRIMARY KEY (BATCH_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE BONUS_BUNDLE_MASTER ADD CONSTRAINT PK_BUNDLE_INFO PRIMARY KEY (BUNDLE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE BONUS ADD CONSTRAINT PK_BON PRIMARY KEY (USER_ID_OR_MSISDN, PROFILE_TYPE, PRODUCT_CODE, POINTS_DATE, BUCKET_CODE)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE P2P_SUBSCRIBERS ADD CONSTRAINT PK_P2P_SUBSCRIBERS PRIMARY KEY (USER_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE P2P_BUDDIES ADD CONSTRAINT PK_P2P_BUDDIES PRIMARY KEY (PARENT_ID, BUDDY_MSISDN)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE OTA_JOB_DATABASE ADD CONSTRAINT PK_OTA_JOB_DB PRIMARY KEY (JOB_ID, BATCH_ID, MSISDN)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE GEOGRAPHICAL_DOMAIN_TYPES ADD CONSTRAINT PK_GROGRAPHICAL_DOMAIN_TYPES PRIMARY KEY (GRPH_DOMAIN_TYPE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE OTA_ADM_TRANSACTION ADD CONSTRAINT PK_OTA_ADM PRIMARY KEY (MSISDN)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE O2C_BATCH_ITEMS ADD CONSTRAINT PK_O2C_BATCH_ITEMS PRIMARY KEY (BATCH_DETAIL_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE O2C_BATCHES ADD CONSTRAINT PK_O2C_BATCHES PRIMARY KEY (BATCH_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORK_VAS_CATEGORY_MAPPING ADD CONSTRAINT PK PRIMARY KEY (NETWORK_CODE, VAS_TYPE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORK_STOCK_TRANS_ITEMS ADD CONSTRAINT PK_NETWORK_STOCK_TRANS_ITEMS PRIMARY KEY (S_NO, TXN_NO)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE NETWORK_STOCK_TRANSACTIONS ADD CONSTRAINT PK_NETWORK_STOCK_TRANSACTIONS PRIMARY KEY (TXN_NO)
  ; 

  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE SUBSCRIBER_MSISDN_ALIAS ADD CONSTRAINT MSISDN PRIMARY KEY (MSISDN)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE SUBSCRIBER_CONTROL ADD CONSTRAINT PK_SUBSCRIBER_CONTRL PRIMARY KEY (MSISDN, CREATED_DATE, MODULE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE STK_PROFILES ADD CONSTRAINT PK_STK_PROFILES PRIMARY KEY (PROFILE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE SRV_CLASS_MAPPED_MSISDN ADD CONSTRAINT PK_SRV_MSISDN PRIMARY KEY (MSISDN, SERVICE_TYPE, SERVICE_CLASS_CODE, MODULE, USER_TYPE)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE SOS_TRANSACTION_DETAILS ADD CONSTRAINT IND_SOS_TRAN_DETAILS_PK PRIMARY KEY (TRANSACTION_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE SOS_SUMMARY_BY_ERROR_STATUS ADD CONSTRAINT PK_SOS_SUMM_BY_ERSTATUS PRIMARY KEY (PROCESS_TYPE, TRANSACTION_DATE, ERROR_STATUS, NETWORK_CODE)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE GEOGRAPHICAL_DOMAINS ADD CONSTRAINT PK_GEOGRAPHICAL_DOMAINS PRIMARY KEY (GRPH_DOMAIN_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE FOC_BONUS_BATCHES ADD CONSTRAINT PK_FOC_BONUS_BATCH PRIMARY KEY (BATCH_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE FOC_BATCH_ITEMS ADD CONSTRAINT PK_FOC_BATCH_ITEMS PRIMARY KEY (BATCH_DETAIL_ID)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE FOC_BATCH_GEOGRAPHIES ADD CONSTRAINT PK_FOC_BATCH_GEOGRAPHIES PRIMARY KEY (BATCH_ID, GEOGRAPHY_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE DOWNLOAD_SCHEDULED_REPORTS ADD CONSTRAINT PK_REPORT_CODE PRIMARY KEY (REPORT_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE DOMAIN_TYPES ADD CONSTRAINT PK_DOMAIN_TYPES PRIMARY KEY (DOMAIN_TYPE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE DOMAINS ADD CONSTRAINT PK_DOMAINS PRIMARY KEY (DOMAIN_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE DIVISION_DEPARTMENT ADD CONSTRAINT PK_DIVISION_DEPARTMENT PRIMARY KEY (DIVDEPT_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE DAILY_SUBS_COUNT ADD CONSTRAINT PK_DAILY_SUBS_COUNT PRIMARY KEY (NETWORK_CODE, MODULE, TRANS_DATE, SERVICE_TYPE)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE DAILY_SCHEDULED_REPORT ADD CONSTRAINT PK_DAILY_SCHEDULED_REPORT PRIMARY KEY (REPORT_CODE)
  ;
  --TABLESPACE P_C2SDATA  ENABLE

  ALTER TABLE BATCH_GEOGRAPHIES ADD CONSTRAINT PK_BATCH_GEOGRAPHIES PRIMARY KEY (BATCH_ID, GEOGRAPHY_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CREDENTIAL_SEC ADD CONSTRAINT CREDENTIAL_SEC_PK PRIMARY KEY (SNO)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CREDENTIAL_FIRST ADD CONSTRAINT CREDENTIAL_FIRST_PK PRIMARY KEY (SNO)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CONTROL_PREFERENCES ADD CONSTRAINT PK_CONTROL_PREFERENCES PRIMARY KEY (CONTROL_CODE, NETWORK_CODE, PREFERENCE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE COMMISSION_PROFILE_SET_VERSION ADD CONSTRAINT PK_COMM_PROF_SET_VER PRIMARY KEY (COMM_PROFILE_SET_ID, COMM_PROFILE_SET_VERSION)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE COMMISSION_PROFILE_SET ADD CONSTRAINT PK_COMMISSION_PROFILE_SET PRIMARY KEY (COMM_PROFILE_SET_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE COMMISSION_PROFILE_PRODUCTS ADD CONSTRAINT PK_COMMSISION_PROFILE_PRODUCTS PRIMARY KEY (COMM_PROFILE_PRODUCTS_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CHNL_TRANSFER_RULES_PRODUCTS ADD CONSTRAINT PK_CHNL_TRF_RULE_PRODUCT PRIMARY KEY (PRODUCT_CODE, TRANSFER_RULE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CHNL_TRANSFER_RULES ADD CONSTRAINT PK_CHNL_TRANSFER_RULES PRIMARY KEY (TRANSFER_RULE_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CHANNEL_USERS ADD CONSTRAINT PK_CHANNEL_USERS PRIMARY KEY (USER_ID)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE CHANNEL_GRADES ADD CONSTRAINT PK_CHANNEL_GRADES PRIMARY KEY (GRADE_CODE)
  ;
  --TABLESPACE PRTP_DATA  ENABLE

  ALTER TABLE C2S_DAILY_TRANSACTIONS ADD CONSTRAINT PK_C2S_DL_TRANS PRIMARY KEY (TRANS_DATE, NETWORK_CODE, RECEIVER_NETWORK_CODE, SENDER_CATEGORY, SERVICE_TYPE, SUB_SERVICE_TYPE, RECEIVER_SERVICE_CLASS_ID, RECEIVER_SERVICE_CLASS_CODE)
  ;
  --TABLESPACE ALL_INDX  ENABLE

  ALTER TABLE C2S_SUMMARY_DAILY ADD CONSTRAINT PK_C2S_SUMMARY_DLY PRIMARY KEY (TRANS_DATE, SENDER_NETWORK_CODE, RECEIVER_NETWORK_CODE, SERVICE_TYPE, SUB_SERVICE_TYPE)
  ;
  --TABLESPACE ALL_INDX  ENABLE

  ALTER TABLE HOURLY_TRANSACTION_SUMMARY ADD CONSTRAINT PK_HRLY_TRANS_SUMM PRIMARY KEY (TRANS_DATE, TRANS_HOUR, SERVICE, SUB_SERVICE, TRANSFER_CATEGORY, SENDER_SERVICE_CLASS, RECEIVER_SERVICE_CLASS)
  ; 
  --TABLESPACE P_C2SINDEX  ENABLE

  ALTER TABLE MONTHLY_TRANSACTION_SUMMARY ADD CONSTRAINT PK_MON_TRANS_SUMM PRIMARY KEY (TRANS_MONTH_YEAR, TRANS_MONTH, SENDER_NETWORK_CODE, RECEIVER_NETWORK_CODE, SERVICE, SUB_SERVICE, TRANSFER_CATEGORY, SENDER_SERVICE_CLASS, RECEIVER_SERVICE_CLASS)
  ;
  --TABLESPACE ALL_INDX  ENABLE

  ALTER TABLE MONTHLY_CHNL_TRANS_DETAILS ADD CONSTRAINT PK_MON_CHNL_TRANS_DET PRIMARY KEY (TRANS_DATE, USER_ID, RECEIVER_CATEGORY_CODE, PRODUCT_CODE, TYPE, TRANSFER_CATEGORY, TRANSFER_TYPE, TRANSFER_SUB_TYPE)
  ;
  --TABLESPACE ALL_INDX  ENABLE

  ALTER TABLE P2P_SUBSCRIBER_SUMMARY ADD CONSTRAINT PK_P2P_SUBS_SUMM PRIMARY KEY (MONTH_YEAR, MONTH, USER_ID, SUBSCRIBER_TYPE, SENDER_SERVICE_CLASS, SERVICE, SUB_SERVICE, TRANSFER_CATEGORY)
  ;
  --TABLESPACE P_C2SDATA  ENABLE
