JAVA_FOLDER_PATH: /data1/pretups73_dev/tomcat8_web/webapps/pretups/WEB-INF/src/Java
COMPILE_FILE_PATH: /data1/pretups73_dev/tomcat8_web/webapps/pretups/WEB-INF/src
Local_TOMCAT_PATH: /data1/pretups73_dev/tomcat8_web