INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, type, VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('MAX_MSISDN_TEXTBOX_LENGTH', 'Max Mobile Number', 'SYSTEMPRF', 'INT', '10', 0, 10, 50, 'Maximum Mobile number length', 'N', 'Y', 'C2S', NULL, TIMESTAMP '2006-12-13 00:00:00.000000', 'ADMIN', TIMESTAMP '2006-12-13 00:00:00.000000', 'ADMIN', NULL, 'N');
