---

 - name: Create an pretups_ui_image directory
   file:
     path: "/{{ REG_DIR }}/pretups_ui_image"
     state: directory
     owner: "{{ PRIVATE_REG_USER_NAME }}"
     group: "{{ PRIVATE_REG_GROUP_NAME }}"


 - name: Copying private reg - DockerFile, apachae Tomcat and pretups.war to the destination
   become: true
   remote_user: "{{ PRIVATE_REG_USER_NAME }}"
   ansible.builtin.copy:
     src: private_reg/.
     dest: "/{{ REG_DIR }}/pretups_ui_image"
     owner: "{{ PRIVATE_REG_USER_NAME }}"
     group: "{{ PRIVATE_REG_GROUP_NAME }}"
     mode: '0777'

 - name: "let's make it work: main.js: replace the cd dir"
   replace: dest="/{{ REG_DIR }}/pretups_ui_image/pretups-ui/main.38ecb79856ff8fffef44.js" regexp='http://172.30.24.113:8086/voucherMgmt/v1' replace='http://{{ LOGIN_MODULE_IP }}:{{ LOGIN_MODULE_NODEPORT }}/voucherMgmt/v1' encoding='cp1252'

 - name: "let's make it work: main.js: replace the cd dir"
   replace: dest="/{{ REG_DIR }}/pretups_ui_image/pretups-ui/main.38ecb79856ff8fffef44.js" regexp='http://172.30.24.104:5001/' replace='http://{{ NODE_IP }}:{{ NODE_MODULE_NODEPORT }}/voucherMgmt/v1' encoding='cp1252'



 - name: "let's make it work: index.html: replace the cd dir"
   replace: dest="/{{ REG_DIR }}/pretups_ui_image/pretups-ui/index.html" regexp='http://172.30.24.113:9747/pretups-ui/' replace='http://{{ PRETUPS_UI_IP }}:{{ PRETUPS_UI_NODEPORT }}/pretups-ui/' encoding='cp1252'

 - name: "let's make it work: index.html: replace the cd dir"
   replace: dest="/{{ REG_DIR }}/pretups_ui_image/pretups-ui/main.38ecb79856ff8fffef44.js" regexp='http://172.30.24.113:6789/pretups/' replace='http://{{ PRETUPS_IP }}:{{ PRETUPS_NODEPORT }}/pretups/' encoding='cp1252'




 - name: Build an Image
   become: true
   remote_user: "{{ PRIVATE_REG_USER_NAME }}"
   command: chdir="/{{ REG_DIR }}/pretups_ui_image"  docker build --build-arg MYJAVAOPTS="-server  -Xms2048m -Xmx2048m -Xmn1024m  -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -XX:ParallelGCThreads=16  -XX:+PrintGCDetails -XX:+UseParallelOldGC -Xloggc:gc_ptups_txn.log -Djava.library.path=$CATALINA_HOME/lib -Dpretups.shutdown.port={{ PRETUPS_UI_SHUTDOWN_PORT }}  -Dpretups.startup.port={{ PRETUPS_UI_CONTAINER_PORT }} -Dpretups.http.port={{ PRETUPS_UI_CONTAINER_PORT }} -Dpretups.instance.type=WEB -Dpretups.instance.module=C2S" -t pretups-ui:v1 -f DockerFile .


 - name: Tag an Image
   become: true
   remote_user: "{{ PRIVATE_REG_USER_NAME }}"
   command: docker image tag pretups-ui:v1 localhost:5000/pretups-uiapp:v1


 - name: Push the Image changes
   become: true
   remote_user: "{{ PRIVATE_REG_USER_NAME }}"
   command: docker image push localhost:5000/pretups-uiapp:v1

#docker run  -e ENV_DOCKER_REGISTRY_HOST=172.30.38.52 -e ENV_DOCKER_REGISTRY_PORT=5000 -p 8080:80 konradkleine/docker-registry-frontend




