---
- name: install redis deps
  yum: name=make state=present
  tags: redis

- name: install redis deps
  yum: name=gcc state=present
  tags: redis

- name: install redis deps
  yum: name=wget state=present
  tags: redis


- name: download redis source
  shell: wget -O - http://download.redis.io/releases/redis-{{redis.version}}.tar.gz | tar -xz -C /tmp creates=/tmp/redis-{{redis.version}}
  tags: redis

- name: install redis
  shell: make chdir=/tmp/redis-{{redis.version}} creates=/tmp/redis-{{redis.version}}/src/redis-server
  tags: redis

- name: move compiled redis binaries
  shell: cp -f redis-cli /usr/local/bin chdir=/tmp/redis-{{redis.version}}/src
  tags: redis


- name: move compiled redis binaries
  shell: cp -f redis-server /usr/local/bin chdir=/tmp/redis-{{redis.version}}/src
  tags: redis 

- name: move compiled redis binaries
  shell: cp -f redis-benchmark /usr/local/bin chdir=/tmp/redis-{{redis.version}}/src
  tags: redis


- name: configure redis-server
  template: src=redis.conf.j2 dest=/etc/redis.conf
  notify:
  - restart redis
  tags: redis

- name: make redis a service
  template: src=redis_init_script.j2 dest=/etc/init.d/redis mode=755
  tags: redis

- name: run redis
  shell: /etc/init.d/redis start creates=/var/run/redis.pid
  tags: redis
