---
 - name: copying apache-tomcat-8
   remote_user: "{{ USER_NAME }}"
   sudo: true
   unarchive: src={{ tomcat_name }}.tar.gz dest=~/ creates=no mode=0755 owner={{ USER_NAME }} group={{ GROUP_NAME }}

 - name: print the tomcat name
   debug: msg="tomcat is {{ tomcat_name }}"

 - name: registering a variable with the tomcat patch directory FOR WEB
   remote_user: "{{ USER_NAME }}"
   sudo: true
   shell: /bin/pwd chdir=~/{{ tomcat_name }}
   register: tomcat_path

 - name: print tomcat_path
   debug: msg="tomcat_path is {{ tomcat_path.stdout }}"

 - name: print environment path variable of pretups user
   debug: msg="pretups path variable is {{ ansible_env.PATH }}"

