spool on;
spool assign_table_space.log;

ALTER USER {{ PRETUPS_SCHEMA_USER_NAME }}
QUOTA UNLIMITED ON {{ PRTP_DATA_TS_NAME }}
QUOTA UNLIMITED ON {{ P_C2SINDX_TS_NAME }}
QUOTA UNLIMITED ON {{ P_C2SDATA_TS_NAME }}
QUOTA UNLIMITED ON {{ MISP_DATA_TS_NAME }}
QUOTA UNLIMITED ON {{ PRTPUSERS_TS_NAME }}
QUOTA UNLIMITED ON {{ P_C2SINDX1_TS_NAME }}
QUOTA UNLIMITED ON {{ PRTPUSERBAL_HIST_TS_NAME }}
QUOTA UNLIMITED ON {{ PRTPINDX_1_TS_NAME }}
QUOTA UNLIMITED ON {{ P_C2SDATA_1_TS_NAME }}
QUOTA UNLIMITED ON {{ P2P_INDX_TS_NAME }}
QUOTA UNLIMITED ON {{ PRTPMIS_TS_NAME }}
QUOTA UNLIMITED ON {{ P2P_DATA_TS_NAME }}
QUOTA UNLIMITED ON {{ IN_INDX_TS_NAME }}
QUOTA UNLIMITED ON {{ PRTPDATA_TS_NAME }}
QUOTA UNLIMITED ON {{ IN_DATA_TS_NAME }}
QUOTA UNLIMITED ON {{ PRTP_INDX_TS_NAME }};

spool off;
