---
apiVersion: v1
kind: Service
metadata:
  name: pretups-ui-service
spec:
  selector:
    app: pretups-ui
  type: NodePort
  ports:
     -  port: 80
        protocol: TCP
        targetPort: PRETUPS_UI_CONTAINER_PORT
        nodePort: PRETUPS_UI_NODEPORT	
