--JIRA ID = PRETUPS-25653--


UPDATE PAGES_UI
SET MODULE_CODE='COMMON', PAGE_URL='/voucher-resend', MENU_NAME='Voucher PIN Resed', SHOW_MENU='Y', SEQUENCE_NO=2, MENU_LEVEL='1', PARENT_PAGE_CODE='ROOT', IMAGE='assets/images/UserBarring/svg/UserBarring@1.5x.svg', ROLE_CODE=NULL, DOMAIN_TYPE=NULL, CATEGORY_CODE=NULL, PAGE_TYPE='home_actions', APP_NAME='eTopup', IS_DEFAULT=NULL
WHERE PAGE_CODE='P_VOUCH_PIN_RESEND';






--JIRA ID = PRETUPS-26197  --
ALTER TABLE CHANNEL_TRANSFERS MODIFY RECONCILIATION_REMARK VARCHAR2(150);



--JIRA ID = PRETUPS-26219 --
INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, "TYPE", VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('MAX_KEY_LENGTH', 'Max Key Length', 'SYSTEMPRF', 'INT', '50', 1, 60, 50, 'Max Key Length', 'N', 'Y', 'C2S', 'Max Key Length', TIMESTAMP '2016-06-07 00:00:00.000000', 'ADMIN', TIMESTAMP '2016-06-07 00:00:00.000000', 'ADMIN', NULL, 'Y');





--PRETUPS-26255

UPDATE PAGES_UI
SET MODULE_CODE='COMMON', PAGE_URL='/division', MENU_NAME='Division & Department', SHOW_MENU='Y', SEQUENCE_NO=23, MENU_LEVEL='1', PARENT_PAGE_CODE='ROOT', IMAGE='assets/images/home/svg/home.svg', ROLE_CODE=NULL, DOMAIN_TYPE='OPERATOR', CATEGORY_CODE='SUADM', PAGE_TYPE=NULL, APP_NAME='eTopup', IS_DEFAULT=NULL
WHERE PAGE_CODE='P_SU_DIV_DEPT_MAIN';

----
UPDATE PAGES_UI
SET MODULE_CODE='COMMON', PAGE_URL='/autoC2CSOSCreditLimit', MENU_NAME='Automatic Stock Mgmt', SHOW_MENU='Y', SEQUENCE_NO=14, MENU_LEVEL='1', PARENT_PAGE_CODE='ROOT', IMAGE='assets/images/recharge_icons/recharge.svg', ROLE_CODE=NULL, DOMAIN_TYPE='OPERATOR', CATEGORY_CODE='BCU', PAGE_TYPE=NULL, APP_NAME='eTopup', IS_DEFAULT=NULL
WHERE PAGE_CODE='P_STOCK_MGMT_MAIN';