INSERT INTO PAGE_UI_ROLES
(ROLE_CODE, PAGE_CODE)
VALUES('VOMSVIEWACT', 'P_VMS_DEN_MAIN');

INSERT INTO PAGE_UI_ROLES
(ROLE_CODE, PAGE_CODE)
VALUES('VOMSADACTPR', 'P_VMS_DEN_MAIN');

INSERT INTO PAGE_UI_ROLES
(ROLE_CODE, PAGE_CODE)
VALUES('VOMSMODACTPR', 'P_VMS_DEN_MAIN');