--PRETUPS-25354
UPDATE pages_ui
SET menu_name='Approval Level 1'
WHERE page_code='P_APPR_L1';

--PRETUPS-25354
UPDATE PAGES_UI
SET MENU_NAME='Approval Level 1'
WHERE PAGE_CODE='P_APPR_SU_L1';

--PRETUPS-25847
UPDATE PAGES_UI
SET MENU_NAME='Voucher PIN Resend'
WHERE PAGE_CODE='P_VOUCH_PIN_RESEND';

--PRETUPS-25711	
UPDATE PAGES_UI
SET  MENU_NAME='Voucher Type Mgmt'
WHERE PAGE_CODE='P_VMS_TYPE_MGMT';
