/** 
 * COPYRIGHT: Comviva Technologies Pvt. Ltd.
 * This software is the sole property of Comviva
 * and is protected by copyright law and international
 * treaty provisions. Unauthorized reproduction or
 * redistribution of this program, or any portion of
 * it may result in severe civil and criminal penalties
 * and will be prosecuted to the maximum extent possible
 * under the law. Comviva reserves all rights not
 * expressly granted. You may not reverse engineer, decompile,
 * or disassemble the software, except and only to the
 * extent that such activity is expressly permitted
 * by applicable law notwithstanding this limitation.
 * THIS SOFTWARE IS PROVIDED TO YOU "AS IS" WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 * YOU ASSUME THE ENTIRE RISK AS TO THE ACCURACY
 * AND THE USE OF THIS SOFTWARE. Comviva SHALL NOT BE LIABLE FOR
 * ANY DAMAGES WHATSOEVER ARISING OUT OF THE USE OF OR INABILITY TO
 * USE THIS SOFTWARE, EVEN IF Comviva HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **/
package com.btsl.user.businesslogic;

import lombok.Getter;

/**
 * System Preference Constants enum.
 *
 * @author SubeshKCV
 * @date : 06-Sep-2019
 */

/**
 * Gets the type.
 *
 * @return the type
 */
@Getter
public enum SystemPreferenceConstants {

	/** The multi operator support. */
	MULTI_OPERATOR_SUPPORT("MULTI_OPERATOR_SUPPORT"),

	/** The amount multi factor. */
	AMOUNT_MULT_FACTOR("AMOUNT_MULT_FACTOR"),

	/** The max series length. */
	MAX_SERIES_LENGTH("MAX_SERIES_LENGTH"),

	/** The min ext code length. */
	MIN_EXT_CODE_LENGTH("MIN_EXT_CODE_LENGTH"),

	/** The external code length. */
	EXTERNAL_CODE_LENGTH("EXTERNAL_CODE_LENGTH"),

	/** The multiple wallets. */
	MULTIPLE_WALLETS("MULTIPLE_WALLETS"),

	/** The commission wallet identifier. */
	COMMISSION_WALLET_IDENTIFIER("COMMISSION_WALLET_IDENTIFIER"),

	/** The is commission wallet required. */
	IS_COMMISSION_WALLET_REQUIRED("IS_COMMISSION_WALLET_REQUIRED"),

	/** The is remittance wallet required. */
	IS_REMITTANCE_WALLET_REQUIRED("IS_REMITTANCE_WALLET_REQUIRED"),

	/** The remittance wallet identifier. */
	REMITTANCE_WALLET_IDENTIFIER("REMITTANCE_WALLET_IDENTIFIER"),

	/** The protelecom remittance wallet identifier. */
	PROTELECOM_REMITTANCE_WALLET_IDENTIFIER("PROTELECOM_REMITTANCE_WALLET_IDENTIFIER"),

	/** The is protelecom remittance wallet required. */
	IS_PROTELECOM_REMITTANCE_WALLET_REQUIRED("IS_PROTELECOM_REMITTANCE_WALLET_REQUIRED"),

	/** The bonussva wallet identifier. */
	BONUSSVA_WALLET_IDENTIFIER("BONUSSVA_WALLET_IDENTIFIER"),

	/** The is random pass allow. */
	IS_RANDOM_PASS_ALLOW("IS_RANDOM_PASS_ALLOW"),

	/** The new domain services for category. */
	NEW_DOMAIN_SERVICES_FOR_CATEGORY("NEW_DOMAIN_SERVICES_FOR_CATEGORY"),
	DWH_DELIMITER_VALUE_TANGO("DWH_DELIMITER_VALUE_TANGO"), MAX_BILLER_VALIDATIONS("MAX_BILLER_VALIDATIONS"),
	ACCOUNT_NO_LENGTH("ACCOUNT_NO_LENGTH"), REPORTS_DECIMAL_PLACES("REPORTS_DECIMAL_PLACES"),
	/** The is loyalty enabled. */
	IS_LOYALTY_ENABLED("IS_LOYALTY_ENABLED"),

	/** The currency factor. */
	CURRENCY_FACTOR("CURRENCY_FACTOR"),

	/** The default registration type. */
	DEFAULT_REGISTRATION_TYPE("DEFAULT_REGISTRATION_TYPE"),

	/** The master wallet type id. */
	MASTER_WALLET_TYPE_ID("MASTER_WALLET_TYPE_ID"),

	/** The is topup opt multi wallet req. */
	IS_TOPUP_OPT_MULTI_WALLET_REQ("IS_TOPUP_OPT_MULTI_WALLET_REQ"),

	/** The is biller multi wallet req. */
	IS_BILLER_MULTI_WALLET_REQ("IS_BILLER_MULTI_WALLET_REQ"),

	/** The min external code length. */
	MIN_EXTERNAL_CODE_LENGTH("MIN_EXT_CODE_LENGTH"),

	/** The is external code required. */
	IS_EXTERNAL_CODE_REQUIRED("IS_ID_REQUIRED"),

	/** The min contactno length. */
	MIN_CONTACTNO_LENGTH("MIN_CONTACTNO_LENGTH"),

	/** The max contactno length. */
	MAX_CONTACTNO_LENGTH("MAX_CONTACTNO_LENGTH"), IS_TEST_SETUP("IS_TEST_SETUP"), MSISDN_PREFIX("MSISDN_PREFIX"),
	SMS_LENGTH_TO_REMOVE("SMS_LENGTH_TO_REMOVE"),
	// VMS systempreference values

	CHANNEL_SOS_ENABLE("CHANNEL_SOS_ENABLE"),

	IS_TRF_RULE_USER_LEVEL_ALLOW("IS_TRF_RULE_USER_LEVEL_ALLOW"),

	LMS_APPL("LMS_APPL"),

	OPT_IN_OUT_ALLOW("OPT_IN_OUT_ALLOW"),

	ALLOWD_USR_TYP_CREATION("ALLOWD_USR_TYP_CREATION"),

	MAX_PASSWORD_BLOCK_COUNT("MAX_PWD_BLOCK_COUNT"),
	
	C2S_PWD_BLK_EXP_DURATION("C2S_PWD_BLK_EXP_DRN"),

	PINPAS_EN_DE_CRYPTION_TYPE("PINPAS_EN_DE_CRYPTION_TYPE"),

	SHA2_FAMILY_TYPE("SHA-256"),

	CALENDAR_TYPE("CALENDAR_TYPE"),

	PASSWORD_BLK_RST_DURATION("PWD_BLK_RST_DURATION"),

	USER_VOUCHERTYPE_ALLOWED("N"),

	VMS_APPROVAL_REQ("VMS_APPROVAL_REQ"),

	MAX_LOGINS_LOCATION("MAX_LOGINS_LOCATION"),
	
	DAYS_AFTER_CHANGE_PASSWORD("DYS_AFTER_CHANGE_PWD"),

	MAX_LOGINS_TYPE("MAX_LOGINS_TYPE"),

	FORCE_LOGOUT_1STUSER("FORCE_LOGOUT"),

	IS_VOU_DEN_PROFILE_ZERO_ALLOW("IS_VOU_DEN_PROFILE_ZERO_ALLOW"),

	MAX_DENOMINATION_VAL("MAX_DENOMINATION_VAL"),

	PAYAMT_MRP_SAME("PAYAMT_MRP_SAME"),

	VOMS_DATE_FORMAT("VOMS_DATE_FORMAT"),

	VOMS_PROFILE_DEF_MINMAXQTY("VOMS_PROFILE_DEF_MINMAXQTY"),

	MAX_REQ_VOUCHER_QTY("MAX_REQ_VOUCHER_QTY"),

	FINANCIAL_YEAR_START("FINANCIAL_YEAR_START"),

	DIRECT_VOUCHER_ENABLE("DIRECT_VOUCHER_ENABLE"),

	SYSTEM_DATE_FORMAT("SYSTEM_DATE_FORMAT"),

	DATE_FORMAT_CAL_JAVA("DATE_FORMAT_CAL_JAVA"),

	IS_MON_DATE_ON_UI("IS_MON_DATE_ON_UI"),

	SEQUENCE_ID_ENABLE("SEQUENCE_ID_ENABLE"),

	VOMS_MAX_APPROVAL_LEVEL("VOMS_MAX_APPROVAL_LEVEL"),

	VOMS_MAX_APPROVAL_LEVEL_SUB_SUPER_ADMIN("VOMS_MAX_APPROVAL_LEVEL_SUB_SUPER_ADMIN"),

	VOMS_MAX_APPROVAL_LEVEL_SUPER_NW_ADMIN("VOMS_MAX_APPROVAL_LEVEL_SUPER_NW_ADMIN"),

	VOMS_MAX_APPROVAL_LEVEL_NW_ADMIN("VOMS_MAX_APPROVAL_LEVEL_NW_ADMIN"),

	ONLINE_VOUCHER_GEN_LIMIT("ONLINE_VOUCHER_GEN_LIMIT"), ONLINE_VOUCHER_GEN_LIMIT_NW("ONLINE_VOUCHER_GEN_LIMIT_NW"),
	OPERATOR_UTIL_CLASS("OPERATOR_UTIL_VMS"), NW_CODE_NW_PREFIX_MAPPING("NW_CODE_NW_PREFIX_MAPPING"),
	VOMS_SERIAL_NO_MAX_LENGTH("VOMS_SNO_MAX_LENGTH"),
	VOMS_NATIONAL_LOCAL_PREFIX_ENABLE("VOMS_NATIONAL_LOCAL_PREFIX_ENABLE"), NW_NATIONAL_PREFIX("NW_NATIONAL_PREFIX"),
	MULTIPLE_VOUCHER_TABLE("MULTIPLE_VOUCHER_TABLE"), HASHING_ENABLE("HASHING_ENABLE"),
	HASHING_ID_RANGE("HASHING_ID_RANGE"), VOUCH_GEN_BATCH_SIZE("VOUCH_GEN_BATCH_SIZE"),
	VOUCH_GEN_RETRY_COUNT("VOUCH_GEN_RETRY_COUNT"),
	IS_SECURITY_COMMON_VALIDATION_REQUIRED("IS_SECURITY_COMMON_VALIDATION_REQUIRED"),
	SYSTEM_DTTIME_FORMAT("SYSTEM_DTTIME_FORMAT"), VOMS_PIN_MAX_LENGTH("VOMS_PIN_MAX_LENGTH"),
	VMSPIN_EN_DE_CRYPTION_TYPE("VMSPIN_EN_DE_CRYPTION_TYPE"), SEQUENCE_ID_RANGE("SEQUENCE_ID_RANGE"),
	VOUCHER_GEN_EMAIL_NOTIFICATION("VOUCHER_GEN_EMAIL_NOTIFICATION"), VMS_D_STATUS_CHANGE("VMS_D_STATUS_CHANGE"),
	VMS_E_STATUS_CHANGE("VMS_E_STATUS_CHANGE"), VMS_P_STATUS_CHANGE("VMS_P_STATUS_CHANGE"),
	
	EMAIL_DEFAULT_LOCALE("EMAIL_DEFAULT_LOCALE"),
	
	DEFAULT_COUNTRY("DEFAULT_COUNTRY"),
	
	VMS_P_STATUS_CHANGE_MAP("VMS_P_STATUS_CHANGE_MAP"),
	
	VMS_E_STATUS_CHANGE_MAP("VMS_E_STATUS_CHANGE_MAP"),
	
	VMS_D_STATUS_CHANGE_MAP("VMS_D_STATUS_CHANGE_MAP"),
	
	SYSTEM_DATETIME_FORMAT("SYSTEM_DTTIME_FORMAT"),
	
	ONLINE_CHANGE_STATUS_SYSTEM_LMT("ONLINE_CHANGE_STATUS_SYSTEM_LMT"),
	
	ONLINE_CHANGE_STATUS_NETWORK_LMT("ONLINE_CHANGE_STATUS_NETWORK_LMT"),
	
	DEFAULT_MESSGATEWAY("DEFAULT_MESSGATEWAY"),
	
	DEFAULT_LANGUAGE("DEFAULT_LANGUAGE"),
	

	VOUCHER_GEN_SMS_NOTIFICATION("VOUCHER_GEN_SMS_NOTIFICATION"),
	
	MAX_LOGIN_PWD_LENGTH("MAX_LOGIN_PWD_LENGTH"),
	
	VOMS_SERIAL_NO_MIN_LENGTH("VOMS_SNO_MIN_LENGTH"),
	
	VOMS_PIN_MIN_LENGTH("VOMS_PIN_MIN_LENGTH"),
	
	OPERATOR_UTIL_CLASS_VMS("OPERATOR_UTIL_C_VMS"),
	MAX_FILE_SIZE_FOR_VMSSIGNED_DOC("MAX_FILE_SIZE_FOR_VMSSIGNED_DOC"),
	VMS_ALLOW_CONTENT_TYPE("VMS_ALLOW_CONTENT_TYPE"),
	
	VOMS_PROF_TALKTIME_MANDATORY("VOMS_PROF_TALKTIME_MANDATORY"),
	
	VOMS_PROF_VALIDITY_MANDATORY("VOMS_PROF_VALIDITY_MANDATORY"),
	VMS_MAX_APPR_LEVEL("VOMS_MAX_APPROVAL_LEVEL"),
	VMS_MAX_BATCHES_ALLOWED("VMS_MAX_BATCHES_ALLOWED"),
	
	VOMS_PROFILE_MIN_REORDERQTY("VOMS_PROFILE_MIN_REORDERQTY"),
	
	VOMS_PROFILE_MAX_REORDERQTY("VOMS_PROFILE_MAX_REORDERQTY"),

	DATE_TIME_FORMAT("DATE_TIME_FORMAT"),
	CHECKSUM_SECURITY_ENABLE("VMS_CHECK_SUM_ENABLE"),
	
	
	VOU_UPLOAD_ERROR_DISPLAY("VOU_UPLOAD_ERROR_DISPLAY"),
	
	VOMS_VOUCHER_FILE_PATH("VOMS_VOUCHER_FILE_PATH"),
	
	RESET_PASSWORD_EXPIRED_TIME_IN_HOURS("RESET_PWD_EXP_TIME_IN_HOURS"),
	
	PSWD_EXP_TIME_IN_HOUR_AFTER_CREATION("PSWD_EXP_TIME_IN_HOUR_ON_CREATION"),
	
	
	CHANGE_PASSWORD_NOT_REQUIRED_CATEGORY("PWD_CHANGE_NOT_REQ"),
	
	C2S_DEFAULT_PASSWORD("C2S_DEFAULT_PASSWORD"),
	
	

	;

	/** The type. */
	// Type
	private String type;

	/**
	 * Construct the System Preference.
	 *
	 * @param type - type
	 */
	SystemPreferenceConstants(String type) {
		this.type = type;
	}

	/**
	 * System Preference checking.
	 *
	 * @param type - string
	 * @return boolean -true/false
	 */
	public static boolean isSystemPreference(String type) {
		for (SystemPreferenceConstants iniType : SystemPreferenceConstants.values()) {
			if (iniType.getType().equals(type)) {
				return true;
			}
		}
		return false;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	
}

