---

 - name: Create an pretups_ui_image directory
   file:
     path: "/{{ REG_DIR }}/redis_image"
     state: directory
     owner: "{{ PRIVATE_REG_USER_NAME }}"
     group: "{{ PRIVATE_REG_GROUP_NAME }}"


 - name: Copying private reg - DockerFile, apachae Tomcat and pretups.war to the destination
   become: true
   remote_user: "{{ PRIVATE_REG_USER_NAME }}"
   ansible.builtin.copy:
     src: private_reg/.
     dest: "/{{ REG_DIR }}/redis_image"
     owner: "{{ PRIVATE_REG_USER_NAME }}"
     group: "{{ PRIVATE_REG_GROUP_NAME }}"
     mode: '0777'


 - name: Build an Image
   become: true
   remote_user: "{{ PRIVATE_REG_USER_NAME }}"
   command: chdir="/{{ REG_DIR }}/redis_image/redis-sentinel-ha-k8s-deployment/docker"  docker build -t redis-sentinel-ha-cluster:1.0 .

 - name: Tag an Image
   become: true
   remote_user: "{{ PRIVATE_REG_USER_NAME }}"
   command: docker image tag redis-sentinel-ha-cluster:1.0 localhost:5000/redis-sentinel-ha-cluster:1.0


 - name: Push the Image changes
   become: true
   remote_user: "{{ PRIVATE_REG_USER_NAME }}"
   command: docker image push localhost:5000/redis-sentinel-ha-cluster:1.0

#docker run  -e ENV_DOCKER_REGISTRY_HOST=172.30.38.52 -e ENV_DOCKER_REGISTRY_PORT=5000 -p 8080:80 konradkleine/docker-registry-frontend




