---
apiVersion: v1
kind: Service
metadata:
  name: pretups-service
spec:
  selector:
    app: pretups
  type: NodePort
  ports:
     -  port: 80
        protocol: TCP
        targetPort: PRETUPS_CONTAINER_PORT
        nodePort: PRETUPS_NODEPORT	
