---
apiVersion: v1
kind: Service
metadata:
  name: redis-ha-cluster-redis-slave-lbl-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 31303
  selector:
      app: redis-ha-cluster-redis-slave-lbl

