---
 - name: "Constants.props: comment the variable with the concrete value: pretups.db" 
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)#pretups.db=postgresql(.*)' line='pretups.db=postgresql'

 - name: "Constants.props: comment the variable with the concrete value: pretups.db" 
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)pretups.db=oracle(.*)' line='#pretups.db=oracle'

 - name: "Constants.props: replace the variable with the concrete value: datasourceurl"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='^datasourceurl=(.*)' line='datasourceurl=jdbc:postgresql://{{ DBIP_CON_STRING }}:{{ DBPORT }}/{{ DB_Name }}'

# - name: "Constants.props: replace the variable with the concrete value: DB IP"
#   shell: sed -i 's/<DBIP>/{{ DBIP_CON_STRING }}/g' "{{ Tomcat_Path }}"/conf/pretups/Constants.props
#   replace: dest="{{ Tomcat_Path }}"/conf/pretups/Constants.props regexp='^(.*)<DBIP>(.*)$' replace='\1{{ DBIP }}\2' backup=yes

# - name: "Constants.props: replace the variable with the concrete value: DB PORT"
#   shell: sed -i 's/<DBPORT>/{{ DBPORT }}/g' "{{ Tomcat_Path }}"/conf/pretups/Constants.props

# - name: "Constants.props: replace the variable with the concrete value: DB SID"
#   shell: sed -i 's/<SID>/{{ SID }}/g' "{{ Tomcat_Path }}"/conf/pretups/Constants.props

 - name: "Constants.props: replace the variable with the concrete value: DB_name: it's written over the credentials: to identify the DB"
   shell: sed -i 's/DB_Name/{{ DB_Name }}/g' "{{ Tomcat_Path }}"/conf/pretups/Constants.props

 - name: "Constants.props: replace the variable with the concrete value: DB NAME"
   shell: sed -i 's/<DBNAME>/{{ USERNAME }}/g' "{{ Tomcat_Path }}"/conf/pretups/Constants.props

 - name: "Constants.props: replace the variable with the concrete value: DB PASSWD"
   shell: sed -i 's/<DBPWD>/{{ PASSWORD }}/g' "{{ Tomcat_Path }}"/conf/pretups/Constants.props

 - name: "Constants.props: uncomment the variable with the concrete value: #C3p0Path"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^#C3p0Path=' line='C3p0Path=<Tomcat-Path>/webapps/pretups/WEB-INF/classes/configfiles/C3p0.props'

 - name: "Constants.props: uncomment the variable with the concrete value: #C3p0PathReport"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^#C3p0PathReport=' line='C3p0PathReport=<Tomcat-Path>/webapps/pretups/WEB-INF/classes/configfiles/C3p0_Report.props'

 - name: "Constants.props: uncomment the variable with the concrete value: #C3p0PathExternalDB"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^#C3p0PathExternalDB=' line='C3p0PathExternalDB=<Tomcat-Path>/webapps/pretups/WEB-INF/classes/configfiles/C3p0_ExternalDB.props'

 - name: "Constants.props: replace the variable with the concrete value: DB TOMCAT_PATH FOR WEB"
   replace: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='^(.*)<Tomcat-Path>/logs(.*)$' replace='\1{{ CATALINA_OUT_LOG_PATH_WEB }}\2'
   when: INSTANCE_TYPE == 'WEB'

 - name: "Constants.props: replace the variable with the concrete value: DB TOMCAT_PATH FOR SMSR"
   replace: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='^(.*)<Tomcat-Path>/logs(.*)$' replace='\1{{ CATALINA_OUT_LOG_PATH_SMSR }}\2'
   when: INSTANCE_TYPE == 'SMSR'

 - name: "Constants.props: replace the variable with the concrete value: DB TOMCAT_PATH FOR SMSP"
   replace: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='^(.*)<Tomcat-Path>/logs(.*)$' replace='\1{{ CATALINA_OUT_LOG_PATH_SMSP }}\2'
   when: INSTANCE_TYPE == 'SMSP'

 - name: "Constants.props: replace the variable with the concrete value: DB TOMCAT_PATH"
#   shell: sed -i 's/<Tomcat-Path>/{{ Tomcat_Path }}/g' "{{ Tomcat_Path }}"/conf/pretups/Constants.props
   replace: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='^(.*)<Tomcat-Path>(.*)$' replace='\1{{ Tomcat_Path }}\2'
#  backup=yes

 - name: "Constants.props: replace the variable with the concrete value: INSTANCE_ID"
   shell: sed -i 's/INSTANCE_ID=10/INSTANCE_ID={{ INSTANCE_ID }}/g' "{{ Tomcat_Path }}"/conf/pretups/Constants.props

 - name: "Constants.props: change the variable with the concrete value: POSTGRES_DB_SUPPORT"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^#POSTGRES_DB_SUPPORT(.*)' line='POSTGRES_DB_SUPPORT=Y'

 - name: "Constants.props: comment the variable with the concrete value: poolmanagerclass=com.btsl.db.pool.OJDBCPoolManager"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^poolmanagerclass=com.btsl.db.pool.OJDBCPoolManager(.*)' line='#poolmanagerclass=com.btsl.db.pool.OJDBCPoolManager'

 - name: "Constants.props: uncomment the variable with the concrete value: poolmanagerclass=com.btsl.db.pool.C3p0PoolManager"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^#poolmanagerclass=com.btsl.db.pool.C3p0PoolManager(.*)' line='poolmanagerclass=com.btsl.db.pool.C3p0PoolManager'

 - name: "Constants.props: comment the variable with the concrete value: reportdbpoolmanagerclass=com.btsl.db.pool.OJDBCPoolManager"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^reportdbpoolmanagerclass=com.btsl.db.pool.OJDBCPoolManager(.*)' line='#reportdbpoolmanagerclass=com.btsl.db.pool.OJDBCPoolManager'

 - name: "Constants.props: uncomment the variable with the concrete value: #reportdbpoolmanagerclass=com.btsl.db.pool.C3p0PoolManager"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^#reportdbpoolmanagerclass=com.btsl.db.pool.C3p0PoolManager(.*)' line='reportdbpoolmanagerclass=com.btsl.db.pool.C3p0PoolManager'

 - name: "Constants.props: comment the variable with the concrete value: currentReportDBPoolManagerClass=com.btsl.db.pool.OJDBCPoolManager"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^currentReportDBPoolManagerClass=com.btsl.db.pool.OJDBCPoolManager(.*)' line='#currentReportDBPoolManagerClass=com.btsl.db.pool.OJDBCPoolManager'

 - name: "Constants.props: uncomment the variable with the concrete value: #currentReportDBPoolManagerClass=com.btsl.db.pool.C3p0PoolManager"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^#currentReportDBPoolManagerClass=com.btsl.db.pool.C3p0PoolManager(.*)' line='currentReportDBPoolManagerClass=com.btsl.db.pool.C3p0PoolManager'

 - name: "Constants.props: comment the variable with the concrete value: externaldbpoolmanagerclass=com.btsl.db.pool.OJDBCPoolManager"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^externaldbpoolmanagerclass=com.btsl.db.pool.OJDBCPoolManager(.*)' line='#externaldbpoolmanagerclass=com.btsl.db.pool.OJDBCPoolManager'

 - name: "Constants.props: uncomment the variable with the concrete value: #externaldbpoolmanagerclass=com.btsl.db.pool.C3p0PoolManager"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^#externaldbpoolmanagerclass=com.btsl.db.pool.C3p0PoolManager(.*)' line='externaldbpoolmanagerclass=com.btsl.db.pool.C3p0PoolManager'

 - name: "Constants.props: replace the variable with the concrete value: reportdbdatasourceurl"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^reportdbdatasourceurl=(.*)' line='reportdbdatasourceurl=jdbc:postgresql://{{ DBIP_CON_STRING }}:{{ DBPORT }}/{{ DB_Name }}'
  
 - name: "Constants.props: replace the variable with the concrete value: reportdbuserid"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^reportdbuserid=(.*)' line='reportdbuserid={{ USERNAME }}' 

 - name: "Constants.props: replace the variable with the concrete value: reportdbpasswd"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^reportdbpasswd=(.*)' line='reportdbpasswd={{ PASSWORD }}'
 
 - name: "Constants.props: replace the variable with the concrete value: currentDateRptDBDataSourceURL"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^currentDateRptDBDataSourceURL=(.*)' line='currentDateRptDBDataSourceURL=jdbc:postgresql://{{ DBIP_CON_STRING }}:{{ DBPORT }}/{{ DB_Name }}'

 - name: "Constants.props: replace the variable with the concrete value: currentReportDBUserId"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^currentReportDBUserId=(.*)' line='currentReportDBUserId={{ USERNAME }}' 

 - name: "Constants.props: replace the variable with the concrete value: currentReportDBPasswd"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^currentReportDBPasswd=(.*)' line='currentReportDBPasswd={{ PASSWORD }}'

 - name: "Constants.props: replace the variable with the concrete value: externaldbdatasourceurl"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^externaldbdatasourceurl=(.*)' line='externaldbdatasourceurl=jdbc:postgresql://{{ DBIP_CON_STRING }}:{{ DBPORT }}/{{ DB_Name }}'

# - name: "Constants.props: Commenting actual path for reports in oracle"
#   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^report.actualpath=WEB-INF/reports(.*)' line='#report.actualpath=WEB-INF/reports'

 - name: "Constants.props: Uncommenting actual path for reports in postgres"
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^report.actualpath=/WEB-INF/reports(.*)' line='report.actualpath=/WEB-INF/reports_postgres'

 - name: "Constants.props: set the OAM IP "
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^ONM_HOST_IP=(.*)' line='ONM_HOST_IP={{ OAM_HOST_IP }}'

 - name: "Constants.props: set the minimum size of DB threads "
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^minpoolsize=(.*)' line='minpoolsize={{ minpoolsize }}'

 - name: "Constants.props: set the pool size of DB threads "
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^poolsize=(.*)' line='poolsize={{ poolsize }}'

 - name: "Constants.props: set the Country code "
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^COUNTRY_CODE=(.*)' line='COUNTRY_CODE={{ COUNTRY_CODE }}'

 - name: "Constants.props: set the Admin Mobile no "
   lineinfile: dest={{ Tomcat_Path }}/conf/pretups/Constants.props regexp='(.*)^adminmobile=(.*)' line='adminmobile={{ ADMIN_MOBILE }}'
