#generated via----- $ python -c 'import crypt; print crypt.crypt("pretups123", "$6$pretups$")'
password: $6$pretups$BRXe4gptAbgyvybFSVnUE3jTTMfkXnS6rKl/FhuvSzUac4jogQcDk/6aSh6rVOc2JLKasiZBTZ0JhJaZ7/pUG0 
#pretups_user: pretups1
#from_path: /data
#PROJECT_ROOT: "{{ Project_Root.stdout }}"
#HOME: /data/pretups
