---
apiVersion: v1
kind: Service
metadata:
  name: pretups-node-service
spec:
  selector:
    app: pretups-node
  type: NodePort
  ports:
     -  port: 80
        protocol: TCP
        targetPort: NODE_MODULE_CONTAINER_PORT
        nodePort: NODE_MODULE_NODEPORT	
