package com.btsl.pretups.skey.businesslogic;

import java.io.Serializable;
import java.util.Date;

/*
 * SKeyTransferVO.java
 * Name Date History
 * ------------------------------------------------------------------------
 * Gurjeet Singh Bedi 22/06/2005 Initial Creation
 * ------------------------------------------------------------------------
 * Copyright (c) 2005 Bharti Telesoft Ltd.
 * S Key Transfer VO to be used for interaction with the backend
 */

public class SKeyTransferVO implements Serializable {
    private String _senderID; // Stores the unique ID of the sender
    private String _senderMsisdn; // Stores the Msisdn from which the request is
                                  // recieved
    private String _module; // The module from where the request is coming
    private String _serviceType; // The type of service requested by the sender
    private String _senderType; // Type of sender user, Pre or Post paid
    private long _skey; // The skey that was sent to the concerned user
    private String _recieverMsisdn; // Receiver Msisdn for which the request was
                                    // sent
    private long _transferValue; // Value requested
    private String _paymentMethod; // Payment method to be used
    private Date _requestDate; // Date of requisition
    private Date _requestOn; // Requisition Date time
    private String _requestBy; // Request generated by
    private String _transferID; // Transfer ID generated by the system
    private String _transferStatus; // Status of the Transfer request
    private String _status; // Skey Status i.e. Accepted, Cancelled or expired
    private String _previousStatus; // Previous Skey Status i.e. Accepted,
                                    // Cancelled or expired
    private Date _createdOn; // Created On
    private String _buddy; // Buddy
    private String _skeySentToMsisdn; // S Key to be send to this number
    private String _defaultPaymentMethod; // flag indicating whether Payment
                                          // method is default

    public String toString() {
        return ("_transferID:" + _transferID + " _senderMsisdn:" + _senderMsisdn + " _module:" + _module + " _serviceType:" + _serviceType + "_recieverMsisdn:" + _recieverMsisdn + " _requestDate:" + _requestDate + " _transferValue:" + _transferValue + " _transferStatus:" + _transferStatus + " _status:" + _status + " _previousStatus:" + _previousStatus);
    }

    public String getModule() {
        return _module;
    }

    public void setModule(String module) {
        _module = module;
    }

    public String getPaymentMethod() {
        return _paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        _paymentMethod = paymentMethod;
    }

    public String getRecieverMsisdn() {
        return _recieverMsisdn;
    }

    public void setRecieverMsisdn(String recieverMsisdn) {
        _recieverMsisdn = recieverMsisdn;
    }

    public String getRequestBy() {
        return _requestBy;
    }

    public void setRequestBy(String requestBy) {
        _requestBy = requestBy;
    }

    public Date getRequestDate() {
        return _requestDate;
    }

    public void setRequestDate(Date requestDate) {
        _requestDate = requestDate;
    }

    public Date getRequestOn() {
        return _requestOn;
    }

    public void setRequestOn(Date requestOn) {
        _requestOn = requestOn;
    }

    public String getSenderID() {
        return _senderID;
    }

    public void setSenderID(String senderID) {
        _senderID = senderID;
    }

    public String getSenderMsisdn() {
        return _senderMsisdn;
    }

    public void setSenderMsisdn(String senderMsisdn) {
        _senderMsisdn = senderMsisdn;
    }

    public String getServiceType() {
        return _serviceType;
    }

    public void setServiceType(String serviceType) {
        _serviceType = serviceType;
    }

    public long getSkey() {
        return _skey;
    }

    public void setSkey(long skey) {
        _skey = skey;
    }

    public long getTransferValue() {
        return _transferValue;
    }

    public void setTransferValue(long transferValue) {
        _transferValue = transferValue;
    }

    public String getSenderType() {
        return _senderType;
    }

    public void setSenderType(String senderType) {
        _senderType = senderType;
    }

    public Date getCreatedOn() {
        return _createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        _createdOn = createdOn;
    }

    public String getStatus() {
        return _status;
    }

    public void setStatus(String status) {
        _status = status;
    }

    public String getTransferID() {
        return _transferID;
    }

    public void setTransferID(String transferID) {
        _transferID = transferID;
    }

    public String getTransferStatus() {
        return _transferStatus;
    }

    public void setTransferStatus(String transferStatus) {
        _transferStatus = transferStatus;
    }

    public String getPreviousStatus() {
        return _previousStatus;
    }

    public void setPreviousStatus(String previousStatus) {
        _previousStatus = previousStatus;
    }

    public String getBuddy() {
        return _buddy;
    }

    public void setBuddy(String buddy) {
        _buddy = buddy;
    }

    public String getSkeySentToMsisdn() {
        return _skeySentToMsisdn;
    }

    public void setSkeySentToMsisdn(String skeySentToMsisdn) {
        _skeySentToMsisdn = skeySentToMsisdn;
    }

    public String getDefaultPaymentMethod() {
        return _defaultPaymentMethod;
    }

    public void setDefaultPaymentMethod(String defaultPaymentMethod) {
        _defaultPaymentMethod = defaultPaymentMethod;
    }
}
