---


- name: "Trying to create redis user."
  hosts: appservers-pretups
  serial: 1
  become: yes
  user: "{{ ansible_ssh_user }}"
  gather_facts: true
  vars_files:
    - roles/create_user/vars/main.yml
  roles: 
    - {role: create_user, tags: create_user_web}


- name: "Copy and Create deployment yml"
  hosts: appservers-pretups
  serial: 1
  become: yes
  user: "{{ ansible_ssh_user }}"
  gather_facts: true
  roles: 
    - {role: deploy_redis, tags: create_user_web}