

ALTER TABLE SYSTEM_PREFERENCES
MODIFY NAME NVARCHAR2(40);

ALTER TABLE SYSTEM_PRF_HISTORY
MODIFY NAME NVARCHAR2(40);

commit;

SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('CHANNEL_SOS_ENABLE', 'SOS Feature Enable or disable', 'SYSTEMPRF', 'BOOLEAN', 'true', 
    NULL, NULL, 50, 'SOS Feature Enabled or disabled ', 'N', 
    'Y', 'C2S', 'SOS Feature Enabled or disabled', TO_DATE('04/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('04/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'true/false', 'Y');
COMMIT;


 
 
 delete from Control_Preferences where preference_code= 'AUTO_C2C_TRANSFER_ALLOWED';
commit;

delete from System_Preferences where preference_code= 'AUTO_C2C_TRANSFER_ALLOWED';
commit;

SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('AUTO_C2C_SOS_CAT_ALLOWED', 'auto c2c and SOS categories allowed', 'CATPRF', 'BOOLEAN', 'true', 
    NULL, NULL, 50, 'Category for auto C2C  and SOS is allowed', 'Y', 
    'Y', 'C2S', 'Category for auto C2C is allowed', TO_DATE('03/15/2015 12:37:04', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('03/15/2015 12:37:04', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'true/false', 'Y');
COMMIT;



alter table user_transfer_counts add LAST_SOS_TXN_ID varchar2(20);
commit;
alter table user_transfer_counts add LAST_SOS_TXN_STATUS varchar2(20);

commit;


alter table channel_transfers add SOS_STATUS varchar2(20);
commit;

alter table channel_users add sos_allowed varchar2(5) default 'N';
commit;
alter table channel_users add sos_allowed_amount number(10) default 0;

commit;

alter table channel_users add sos_threshold_limit number(10) default 0;
commit;

update Roles set role_name='Auto C2C/SOS Credit Limit' where role_code='AUTOC2CCRLMT';
commit;

-- entry in service_type table for SOS Settlement service
Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
 Values
   ('SOSSTL', 'C2S', 'ALL', 'TYPE MSISDN PIN', 'com.btsl.pretups.user.requesthandler.ChannelSOSSettlementHandler', 
    'SOS Settlement', 'SOS settlement request', 'Y', TO_DATE('04/18/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('04/18/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'SOS settlement request', 'N', 'N', 
    'Y', NULL, 'N', 'NA', 'N', 
    NULL, NULL, NULL, 'TYPE,MSISDN,STATUS,MESSAGE', 'TYPE,MSISDN,PIN', 
    'Y');
COMMIT;




SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('CHANNEL_AUTOC2C_ENABLE', 'Auto C2C Feature Enable or disable', 'SYSTEMPRF', 'BOOLEAN', 'true', 
    NULL, NULL, 50, 'Auto C2C Feature Enabled or disabled ', 'N', 
    'Y', 'C2S', 'Auto C2C Feature Enabled or disabled', TO_DATE('04/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('04/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'true/false', 'Y');
COMMIT;

-- Procedure modification for DWH added column SOS_STATUS for channel transfer
CREATE OR REPLACE PROCEDURE RP2PDWHTEMPPRC
(
           P_DATE                 IN DATE,
           P_MASTERCNT            OUT NUMBER,
           P_CHTRANSCNT           OUT    NUMBER,
           P_C2STRANSCNT          OUT    NUMBER,
           P_MESSAGE              OUT VARCHAR2
)
IS

SQLEXCEPTION EXCEPTION;
EXITEXCEPTION EXCEPTION;

BEGIN
        DBMS_OUTPUT.PUT_LINE('START RP2P DWH PROC');

        EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_RP2P_DWH_MASTER';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_RP2P_DWH_CHTRANS';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_RP2P_DWH_C2STRANS';


    INSERT INTO TEMP_RP2P_DWH_MASTER ( SRNO, DATA )
    SELECT ROWNUM,(U.USER_ID||','||PARENT_ID||','||OWNER_ID||','||USER_TYPE||','||EXTERNAL_CODE||','||MSISDN
    ||','||REPLACE(L.LOOKUP_NAME,',',' ')||','||REPLACE(LOGIN_ID,',',' ')||','||U.CATEGORY_CODE||','||CAT.CATEGORY_NAME||','||
    UG.GRPH_DOMAIN_CODE||','||REPLACE(GD.GRPH_DOMAIN_NAME,',',' ')||','||
    REPLACE(USER_NAME,',',' ')||','||REPLACE(CITY,',',' ')||','||REPLACE(STATE,',',' ')||','||REPLACE(COUNTRY,',',' ')||',' ||',' ) DATA FROM USERS U, 

CATEGORIES CAT,USER_GEOGRAPHIES UG,GEOGRAPHICAL_DOMAINS GD,LOOKUPS L, LOOKUP_TYPES LT
    WHERE U.USER_ID=UG.USER_ID AND U.CATEGORY_CODE=CAT.CATEGORY_CODE AND U.STATUS<>'C'
    AND UG.GRPH_DOMAIN_CODE=GD.GRPH_DOMAIN_CODE AND L.LOOKUP_CODE=U.STATUS
    AND LT.LOOKUP_TYPE='URTYP' AND LT.LOOKUP_TYPE=L.LOOKUP_TYPE AND TRUNC(U.CREATED_ON)<=P_DATE
    AND USER_TYPE='CHANNEL';
    COMMIT;
    SELECT MAX(SRNO) INTO P_MASTERCNT FROM TEMP_RP2P_DWH_MASTER;



    INSERT INTO TEMP_RP2P_DWH_CHTRANS ( SRNO, DATA )
    SELECT ROWNUM,DATA FROM (SELECT (CT.TRANSFER_ID||','||REQUEST_GATEWAY_TYPE||','||TO_CHAR

(CT.TRANSFER_DATE,'DD/MM/YYYY')
    ||','||TO_CHAR(CT.CREATED_ON,'DD/MM/YYYY HH12:MI:SS PM')||','||CT.NETWORK_CODE
    ||','||CT.TRANSFER_TYPE||','||CT.TRANSFER_SUB_TYPE||','||CT.TRANSFER_CATEGORY
    ||','||CT.TYPE||','||CT.FROM_USER_ID||','||CT.TO_USER_ID||','||CT.MSISDN||','||CT.TO_MSISDN
    ||','||CT.SENDER_CATEGORY_CODE||','||CT.RECEIVER_CATEGORY_CODE||','||
    CTI.REQUIRED_QUANTITY||','||CTI.REQUIRED_QUANTITY||','||CTI.REQUIRED_QUANTITY
    ||','||CTI.MRP||','||CTI.PAYABLE_AMOUNT||','||CTI.NET_PAYABLE_AMOUNT||','||0
    ||','||CTI.TAX1_VALUE||','||CTI.TAX2_VALUE||','||CTI.TAX3_VALUE||','||CTI.COMMISSION_VALUE
    ||','||','||','||CT.EXT_TXN_NO||','||TO_CHAR(CT.EXT_TXN_DATE,'DD/MM/YYYY')||','||','||CTI.PRODUCT_CODE||','||','
    || DECODE(CT.STATUS ,'CLOSE','200','240') ||','||','||','||','||','||','||','||','||','||','||CT.CELL_ID||','
||CTI.SENDER_POST_STOCK||','||CTI.SENDER_PREVIOUS_STOCK||','||CTI.RECEIVER_POST_STOCK||','||CTI.RECEIVER_PREVIOUS_STOCK||','||','||','||CT.SOS_STATUS||','||CT.SOS_SETTLEMENT_DATE||',') DATA     

            FROM CHANNEL_TRANSFERS CT,CHANNEL_TRANSFERS_ITEMS CTI
    WHERE CT.TRANSFER_ID=CTI.TRANSFER_ID(+)
    AND CT.STATUS IN('CLOSE','CNCL') AND TRUNC(CT.CLOSE_DATE)=P_DATE
    ORDER BY CT.MODIFIED_ON,CT.TYPE);
    COMMIT;
    SELECT MAX(SRNO) INTO P_CHTRANSCNT FROM TEMP_RP2P_DWH_CHTRANS;



    INSERT INTO TEMP_RP2P_DWH_C2STRANS ( SRNO, DATA,TRANSFER_STATUS)
    SELECT ROWNUM,DATA,TRANSFER_STATUS FROM (SELECT (CT.TRANSFER_ID||','||REQUEST_GATEWAY_TYPE||','||TO_CHAR

(CT.TRANSFER_DATE,'DD/MM/YYYY')
    ||','||TO_CHAR(CT.TRANSFER_DATE_TIME,'DD/MM/YYYY HH12:MI:SS PM')||','||CT.NETWORK_CODE||','||CT.SERVICE_TYPE||','||','||   'SALE'||','||'C2S'||','||

CT.SENDER_ID||','||','||CT.SENDER_MSISDN||','||CT.RECEIVER_MSISDN||','||
    CT.SENDER_CATEGORY||','||','||CT.SENDER_TRANSFER_VALUE||','||CT.RECEIVER_TRANSFER_VALUE||','||
    CT.TRANSFER_VALUE||','||CT.QUANTITY||','||','||','|| CT.RECEIVER_ACCESS_FEE||','||
    CT.RECEIVER_TAX1_VALUE||','||CT.RECEIVER_TAX2_VALUE||','||0||','||','||CT.DIFFERENTIAL_APPLICABLE||','||
    CT.DIFFERENTIAL_GIVEN||','||','||','||','||CT.PRODUCT_CODE||','||CT.CREDIT_BACK_STATUS||','||CT.TRANSFER_STATUS
    ||','||CT.RECEIVER_BONUS_VALUE||','||CT.RECEIVER_VALIDITY||','||CT.RECEIVER_BONUS_VALIDITY||','
    ||CT.SERVICE_CLASS_CODE||','||CT.INTERFACE_ID||','||CT.CARD_GROUP_CODE
    ||','||REPLACE(KV.VALUE,',',' ')||','||CT.SERIAL_NUMBER||','||CT.INTERFACE_REFERENCE_ID||','||CT.CELL_ID||','||CT.SENDER_POST_BALANCE||','||CT.SENDER_PREVIOUS_BALANCE||','||CT.RECEIVER_POST_BALANCE||','||CT.RECEIVER_PREVIOUS_BALANCE||','||CT.REVERSAL_ID||','||CT.SUB_SERVICE ||',') DATA,CT.TRANSFER_STATUS TRANSFER_STATUS
    FROM C2S_TRANSFERS CT, KEY_VALUES KV ,Service_Type_Selector_Mapping STSM WHERE CT.TRANSFER_DATE=P_DATE  AND stsm.SELECTOR_CODE=CT.SUB_SERVICE AND stsm.SERVICE_TYPE=CT.SERVICE_TYPE 
    AND KV.KEY(+)=CT.ERROR_CODE AND KV.TYPE(+)='C2S_ERR_CD' ORDER BY CT.TRANSFER_DATE_TIME);
    COMMIT;

    SELECT MAX(SRNO) INTO P_C2STRANSCNT FROM TEMP_RP2P_DWH_C2STRANS;


    DBMS_OUTPUT.PUT_LINE('RP2P DWH PROC COMPLETED');
    P_MESSAGE:='SUCCESS';

    EXCEPTION
                 WHEN SQLEXCEPTION THEN
            P_MESSAGE:='NOT ABLE TO MIGRATE DATA, SQL EXCEPTION OCCOURED';
            RAISE EXITEXCEPTION;
                 WHEN OTHERS THEN
                        P_MESSAGE:='NOT ABLE TO MIGRATE DATA, EXCEPTION OCCOURED';
                        RAISE  EXITEXCEPTION;

END;
COMMIT;


update SERVICE_TYPE set MESSAGE_FORMAT = 'TYPE MSISDN1', REQUEST_PARAM = 'TYPE,EXTNWCODE,MSISDN,PIN,LOGINID,PASSWORD,EXTCODE,MSISDN1' where SERVICE_TYPE = 'SOSSTL';
commit;

ALTER TABLE channel_transfers ADD SOS_SETTLEMENT_DATE DATE;
COMMIT;




SET DEFINE OFF;
Insert into PAGES
   (PAGE_CODE, MODULE_CODE, PAGE_URL, MENU_NAME, MENU_ITEM, 
    SEQUENCE_NO, MENU_LEVEL, APPLICATION_ID)
 Values
   ('SOSC2CM001', 'CHRPTC2C', '/sosTxnDetails.do?method=loadSOSDetails', 'SOS TXN Details Report', 'Y', 
    354, '2', '1');
COMMIT;

SET DEFINE OFF;
Insert into PAGE_ROLES
   (ROLE_CODE, PAGE_CODE, APPLICATION_ID)
 Values
   ('SOSTRFDETAILS', 'SOSC2CM001', '1');
COMMIT;


SET DEFINE OFF;
Insert into ROLES
   (DOMAIN_TYPE, ROLE_CODE, ROLE_NAME, GROUP_NAME, STATUS, 
    ROLE_TYPE, FROM_HOUR, TO_HOUR, GROUP_ROLE, APPLICATION_ID, 
    GATEWAY_TYPES, ROLE_FOR, IS_DEFAULT, IS_DEFAULT_GROUPROLE)
 Values
   ('OPERATOR', 'SOSTRFDETAILS', 'SOS Transfer Details', 'Channel Reports-C2C', 'Y', 
    'A', NULL, NULL, 'N', '1', 
    'WEB', 'B', 'N', 'N');
COMMIT;


SET DEFINE OFF;
Insert into CATEGORY_ROLES
   (CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
 Values
   ('BCU', 'SOSTRFDETAILS', '1');
COMMIT;

SET DEFINE OFF;
Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
 Values
   ('SOSTRF', 'C2S', 'ALL', 'TYPE PRODUCTCODE', 'com.btsl.pretups.channel.transfer.requesthandler.SOSTransferRequestHandler', 
    'SOS transfer', 'SOS transfer request', 'Y', TO_DATE('04/18/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('04/18/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'SOS transfer request', 'N', 'N', 
    'Y', NULL, 'N', 'NA', 'N', 
    NULL, NULL, NULL, 'TYPE', 'TYPE,EXTNWCODE,MSISDN,PIN,LOGINID,PASSWORD,EXTCODE,PRODUCTCODE,LANGUAGE1', 
    'Y');
COMMIT;

alter table user_transfer_counts add LAST_SOS_PRODUCT_CODE varchar2(10);
commit;

SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('SOS_SETTLEMENT_TYPE', 'Settlement of SOS', 'SYSTEMPRF', 'STRING', 'AUTO', 
    NULL, NULL, 50, 'Settlement of SOS MANUAL/AUTO', 'N', 
    'Y', 'C2S', 'Settlement of SOS', TO_DATE('04/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('04/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'MANUAL/AUTO', 'Y');
COMMIT;


SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('CHANNEL_SOS_ALLOWED_WALLET', 'SOS allowed wallet', 'NETWORKPRF', 'STRING', 'NETWORK', 
    NULL, NULL, 50, 'SOS allowed wallet either PARENT/OWNER/NETWORK', 'N', 
    'Y', 'C2S', 'SOS allowed wallet either PARENT/OWNER/NETWORK', TO_DATE('04/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('04/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'PARENT/OWNER/NETWORK', 'Y');
COMMIT;


update system_preferences set type='SYSTEMPRF' where preference_code='CHANNEL_SOS_ALLOWED_WALLET';
commit;




SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('DOWNLOAD_CSV_REPORT_REQUIRED', 'Download Reports in csv ', 'SYSTEMPRF', 'BOOLEAN', 'true', 
    NULL, NULL, 50, 'Download Reports in csv required', 'N', 
    'N', 'C2S', 'Download Reports in csv required', TO_DATE('06/16/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('06/17/2005 09:44:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', NULL, 'Y');
COMMIT;

update system_preferences set type='NETWORKPRF' where preference_code='CHANNEL_SOS_ALLOWED_WALLET';
commit;


---------------Added for SOS settlement---------------------

SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('ALLOW_TRANSACTION_IF_SOS_SETTLEMENT_FAIL', 'Allow Transaction if SOS settelment fail', 'SYSTEMPRF', 'STRING', 'FOC, DP', 
    NULL, NULL, 50, 'This flag allow transaction to complete if SOS settelment condition gets failed', 'N', 
    'Y', 'C2S', 'This flag allow transaction to complete if SOS settelment condition gets failed', TO_DATE('05/15/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('06/17/2005 09:44:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'FOC,O2C,C2C,DP', 'Y');
COMMIT;

----Corrected Procedure of SENDER_DEBIT_QUANTITY RECEIVER_CREDIT_QUANTITY TRANSFER_MRP for channel Transfer
CREATE OR REPLACE PROCEDURE RP2PDWHTEMPPRC
(
           P_DATE                 IN DATE,
           P_MASTERCNT            OUT NUMBER,
           P_CHTRANSCNT           OUT    NUMBER,
           P_C2STRANSCNT          OUT    NUMBER,
           P_MESSAGE              OUT VARCHAR2
)
IS

SQLEXCEPTION EXCEPTION;
EXITEXCEPTION EXCEPTION;

BEGIN
        DBMS_OUTPUT.PUT_LINE('START RP2P DWH PROC');

        EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_RP2P_DWH_MASTER';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_RP2P_DWH_CHTRANS';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_RP2P_DWH_C2STRANS';


    INSERT INTO TEMP_RP2P_DWH_MASTER ( SRNO, DATA )
    SELECT ROWNUM,(U.USER_ID||','||PARENT_ID||','||OWNER_ID||','||USER_TYPE||','||EXTERNAL_CODE||','||MSISDN
    ||','||REPLACE(L.LOOKUP_NAME,',',' ')||','||REPLACE(LOGIN_ID,',',' ')||','||U.CATEGORY_CODE||','||CAT.CATEGORY_NAME||','||
    UG.GRPH_DOMAIN_CODE||','||REPLACE(GD.GRPH_DOMAIN_NAME,',',' ')||','||
    REPLACE(USER_NAME,',',' ')||','||REPLACE(CITY,',',' ')||','||REPLACE(STATE,',',' ')||','||REPLACE(COUNTRY,',',' ')||',' ||',' ) DATA FROM USERS U, 

CATEGORIES CAT,USER_GEOGRAPHIES UG,GEOGRAPHICAL_DOMAINS GD,LOOKUPS L, LOOKUP_TYPES LT
    WHERE U.USER_ID=UG.USER_ID AND U.CATEGORY_CODE=CAT.CATEGORY_CODE AND U.STATUS<>'C'
    AND UG.GRPH_DOMAIN_CODE=GD.GRPH_DOMAIN_CODE AND L.LOOKUP_CODE=U.STATUS
    AND LT.LOOKUP_TYPE='URTYP' AND LT.LOOKUP_TYPE=L.LOOKUP_TYPE AND TRUNC(U.CREATED_ON)<=P_DATE
    AND USER_TYPE='CHANNEL';
    COMMIT;
    SELECT MAX(SRNO) INTO P_MASTERCNT FROM TEMP_RP2P_DWH_MASTER;



    INSERT INTO TEMP_RP2P_DWH_CHTRANS ( SRNO, DATA )
    SELECT ROWNUM,DATA FROM (SELECT (CT.TRANSFER_ID||','||REQUEST_GATEWAY_TYPE||','||TO_CHAR

(CT.TRANSFER_DATE,'DD/MM/YYYY')
    ||','||TO_CHAR(CT.CREATED_ON,'DD/MM/YYYY HH12:MI:SS PM')||','||CT.NETWORK_CODE
    ||','||CT.TRANSFER_TYPE||','||CT.TRANSFER_SUB_TYPE||','||CT.TRANSFER_CATEGORY
    ||','||CT.TYPE||','||CT.FROM_USER_ID||','||CT.TO_USER_ID||','||CT.MSISDN||','||CT.TO_MSISDN
    ||','||CT.SENDER_CATEGORY_CODE||','||CT.RECEIVER_CATEGORY_CODE||','||
    CTI.SENDER_DEBIT_QUANTITY||','||CTI.RECEIVER_CREDIT_QUANTITY||','||CT.TRANSFER_MRP
    ||','||CTI.MRP||','||CTI.PAYABLE_AMOUNT||','||CTI.NET_PAYABLE_AMOUNT||','||0
    ||','||CTI.TAX1_VALUE||','||CTI.TAX2_VALUE||','||CTI.TAX3_VALUE||','||CTI.COMMISSION_VALUE
    ||','||','||','||CT.EXT_TXN_NO||','||TO_CHAR(CT.EXT_TXN_DATE,'DD/MM/YYYY')||','||','||CTI.PRODUCT_CODE||','||','
    || DECODE(CT.STATUS ,'CLOSE','200','240') ||','||','||','||','||','||','||','||','||','||','||CT.CELL_ID||','
||CTI.SENDER_POST_STOCK||','||CTI.SENDER_PREVIOUS_STOCK||','||CTI.RECEIVER_POST_STOCK||','||CTI.RECEIVER_PREVIOUS_STOCK||','||','||','||CT.SOS_STATUS||','||CT.SOS_SETTLEMENT_DATE||',') DATA     

            FROM CHANNEL_TRANSFERS CT,CHANNEL_TRANSFERS_ITEMS CTI
    WHERE CT.TRANSFER_ID=CTI.TRANSFER_ID(+)
    AND CT.STATUS IN('CLOSE','CNCL') AND TRUNC(CT.CLOSE_DATE)=P_DATE
    ORDER BY CT.MODIFIED_ON,CT.TYPE);
    COMMIT;
    SELECT MAX(SRNO) INTO P_CHTRANSCNT FROM TEMP_RP2P_DWH_CHTRANS;



    INSERT INTO TEMP_RP2P_DWH_C2STRANS ( SRNO, DATA,TRANSFER_STATUS)
    SELECT ROWNUM,DATA,TRANSFER_STATUS FROM (SELECT (CT.TRANSFER_ID||','||REQUEST_GATEWAY_TYPE||','||TO_CHAR

(CT.TRANSFER_DATE,'DD/MM/YYYY')
    ||','||TO_CHAR(CT.TRANSFER_DATE_TIME,'DD/MM/YYYY HH12:MI:SS PM')||','||CT.NETWORK_CODE||','||CT.SERVICE_TYPE||','||','||   'SALE'||','||'C2S'||','||

CT.SENDER_ID||','||','||CT.SENDER_MSISDN||','||CT.RECEIVER_MSISDN||','||
    CT.SENDER_CATEGORY||','||','||CT.SENDER_TRANSFER_VALUE||','||CT.RECEIVER_TRANSFER_VALUE||','||
    CT.TRANSFER_VALUE||','||CT.QUANTITY||','||','||','|| CT.RECEIVER_ACCESS_FEE||','||
    CT.RECEIVER_TAX1_VALUE||','||CT.RECEIVER_TAX2_VALUE||','||0||','||','||CT.DIFFERENTIAL_APPLICABLE||','||
    CT.DIFFERENTIAL_GIVEN||','||','||','||','||CT.PRODUCT_CODE||','||CT.CREDIT_BACK_STATUS||','||CT.TRANSFER_STATUS
    ||','||CT.RECEIVER_BONUS_VALUE||','||CT.RECEIVER_VALIDITY||','||CT.RECEIVER_BONUS_VALIDITY||','
    ||CT.SERVICE_CLASS_CODE||','||CT.INTERFACE_ID||','||CT.CARD_GROUP_CODE
    ||','||REPLACE(KV.VALUE,',',' ')||','||CT.SERIAL_NUMBER||','||CT.INTERFACE_REFERENCE_ID||','||CT.CELL_ID||','||CT.SENDER_POST_BALANCE||','||CT.SENDER_PREVIOUS_BALANCE||','||CT.RECEIVER_POST_BALANCE||','||CT.RECEIVER_PREVIOUS_BALANCE||','||CT.REVERSAL_ID||','||CT.SUB_SERVICE ||',') DATA,CT.TRANSFER_STATUS TRANSFER_STATUS
    FROM C2S_TRANSFERS CT, KEY_VALUES KV ,Service_Type_Selector_Mapping STSM WHERE CT.TRANSFER_DATE=P_DATE  AND stsm.SELECTOR_CODE=CT.SUB_SERVICE AND stsm.SERVICE_TYPE=CT.SERVICE_TYPE 
    AND KV.KEY(+)=CT.ERROR_CODE AND KV.TYPE(+)='C2S_ERR_CD' ORDER BY CT.TRANSFER_DATE_TIME);
    COMMIT;

    SELECT MAX(SRNO) INTO P_C2STRANSCNT FROM TEMP_RP2P_DWH_C2STRANS;


    DBMS_OUTPUT.PUT_LINE('RP2P DWH PROC COMPLETED');
    P_MESSAGE:='SUCCESS';

    EXCEPTION
                 WHEN SQLEXCEPTION THEN
            P_MESSAGE:='NOT ABLE TO MIGRATE DATA, SQL EXCEPTION OCCOURED';
            RAISE EXITEXCEPTION;
                 WHEN OTHERS THEN
                        P_MESSAGE:='NOT ABLE TO MIGRATE DATA, EXCEPTION OCCOURED';
                        RAISE  EXITEXCEPTION;

END;
/

---------------------------
update SYSTEM_PREFERENCES set DEFAULT_VALUE = 'false' where PREFERENCE_CODE = 'DOWNLOAD_CSV_REPORT_REQUIRED';
commit;

