
--Link-C2C Transfer Summary Report
--Add rolecode in roles table
INSERT INTO ROLES
(DOMAIN_TYPE, ROLE_CODE, ROLE_NAME, GROUP_NAME, STATUS, ROLE_TYPE, FROM_HOUR, TO_HOUR, GROUP_ROLE, APPLICATION_ID, GATEWAY_TYPES, ROLE_FOR, IS_DEFAULT, IS_DEFAULT_GROUPROLE, ACCESS_TYPE)
VALUES('CORPORATE', 'C2CTRFSUMMARY', 'C2C Transfer Summary', 'Channel Reports-C2C', 'Y', 'A', NULL, NULL, 'N', '1', 'WEB', 'B', 'N', 'N', 'B');
COMMIT;

INSERT INTO ROLES
(DOMAIN_TYPE, ROLE_CODE, ROLE_NAME, GROUP_NAME, STATUS, ROLE_TYPE, FROM_HOUR, TO_HOUR, GROUP_ROLE, APPLICATION_ID, GATEWAY_TYPES, ROLE_FOR, IS_DEFAULT, IS_DEFAULT_GROUPROLE, ACCESS_TYPE)
VALUES('DISTB_CHAN', 'C2CTRFSUMMARY', 'C2C Transfer Summary', 'Channel Reports-C2C', 'Y', 'A', NULL, NULL, 'N', '1', 'WEB', 'B', 'N', 'N', 'B');
COMMIT;

--Add rolecode in category_role table
INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('DIST', 'C2CTRFSUMMARY', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('SE', 'C2CTRFSUMMARY', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('AG', 'C2CTRFSUMMARY', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('RET', 'C2CTRFSUMMARY', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('CORPE', 'C2CTRFSUMMARY', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('CCC', 'C2CTRFSUMMARY', '1');
COMMIT;

--Link-Internal User Roles report
--Add rolecode in roles table
INSERT INTO ROLES
(DOMAIN_TYPE, ROLE_CODE, ROLE_NAME, GROUP_NAME, STATUS, ROLE_TYPE, FROM_HOUR, TO_HOUR, GROUP_ROLE, APPLICATION_ID, GATEWAY_TYPES, ROLE_FOR, IS_DEFAULT, IS_DEFAULT_GROUPROLE, ACCESS_TYPE)
VALUES('CORPORATE', 'INTERNALUSERLIST', 'Internal User List', 'Channel Reports-User', 'Y', 'A', NULL, NULL, 'N', '1', 'WEB', 'B', 'N', 'N', 'B');
COMMIT;

INSERT INTO ROLES
(DOMAIN_TYPE, ROLE_CODE, ROLE_NAME, GROUP_NAME, STATUS, ROLE_TYPE, FROM_HOUR, TO_HOUR, GROUP_ROLE, APPLICATION_ID, GATEWAY_TYPES, ROLE_FOR, IS_DEFAULT, IS_DEFAULT_GROUPROLE, ACCESS_TYPE)
VALUES('DISTB_CHAN', 'INTERNALUSERLIST', 'Internal User List', 'Channel Reports-User', 'Y', 'A', NULL, NULL, 'N', '1', 'WEB', 'B', 'N', 'N', 'B');
COMMIT;

--Add rolecode in category_role table
INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('DIST', 'INTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('SE', 'INTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('AG', 'INTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('RET', 'INTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('CORPE', 'INTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('CCC', 'INTERNALUSERLIST', '1');
COMMIT;

--Link-External User List
--Add rolecode in roles table
INSERT INTO ROLES
(DOMAIN_TYPE, ROLE_CODE, ROLE_NAME, GROUP_NAME, STATUS, ROLE_TYPE, FROM_HOUR, TO_HOUR, GROUP_ROLE, APPLICATION_ID, GATEWAY_TYPES, ROLE_FOR, IS_DEFAULT, IS_DEFAULT_GROUPROLE, ACCESS_TYPE)
VALUES('CORPORATE', 'EXTERNALUSERLIST', 'External User List', 'Channel Reports-User', 'Y', 'A', NULL, NULL, 'N', '1', 'WEB', 'B', 'N', 'N', 'B');
COMMIT;

INSERT INTO ROLES
(DOMAIN_TYPE, ROLE_CODE, ROLE_NAME, GROUP_NAME, STATUS, ROLE_TYPE, FROM_HOUR, TO_HOUR, GROUP_ROLE, APPLICATION_ID, GATEWAY_TYPES, ROLE_FOR, IS_DEFAULT, IS_DEFAULT_GROUPROLE, ACCESS_TYPE)
VALUES('DISTB_CHAN', 'EXTERNALUSERLIST', 'External User List', 'Channel Reports-User', 'Y', 'A', NULL, NULL, 'N', '1', 'WEB', 'B', 'N', 'N', 'B');
COMMIT;

--Add rolecode in category_role table
INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('DIST', 'EXTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('SE', 'EXTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('AG', 'EXTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('RET', 'EXTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('CORPE', 'EXTERNALUSERLIST', '1');
COMMIT;

INSERT INTO CATEGORY_ROLES
(CATEGORY_CODE, ROLE_CODE, APPLICATION_ID)
VALUES('CCC', 'EXTERNALUSERLIST', '1');
COMMIT;


#fixes for alert MSISDN
update channel_users set alert_msisdn='' where alert_msisdn='null';