DROP TABLE CHANNEL_VOUCHER_ITEMS;

DROP TABLE CHANNEL_TRANSFER_PAYMENTS;

ALTER TABLE CHANNEL_TRANSFERS DROP COLUMN RECONCILIATION_BY;
ALTER TABLE CHANNEL_TRANSFERS DROP COLUMN RECONCILIATION_DATE;
ALTER TABLE CHANNEL_TRANSFERS DROP COLUMN RECONCILIATION_FLAG;
ALTER TABLE CHANNEL_TRANSFERS DROP COLUMN RECONCILIATION_REMARK;

COMMIT;