ALTER TABLE COMMISSION_PROFILE_PRODUCTS ADD TRANSACTION_TYPE VARCHAR2(10) DEFAULT 'ALL';

ALTER TABLE COMMISSION_PROFILE_PRODUCTS
DROP CONSTRAINT UK_COMMISSION_PROFILE_PRODUCTS;

ALTER TABLE COMMISSION_PROFILE_PRODUCTS ADD (
    CONSTRAINT UK_COMMISSION_PROFILE_PRODUCTS
UNIQUE (COMM_PROFILE_SET_ID, PRODUCT_CODE, PAYMENT_MODE, COMM_PROFILE_SET_VERSION, TRANSACTION_TYPE));

CREATE TABLE COMMISSION_PROFILE_OTF
(
  COMM_PROFILE_OTF_ID    VARCHAR2(10 BYTE),
  COMM_PROFILE_SET_ID        VARCHAR2(10 BYTE)  NOT NULL,
  COMM_PROFILE_SET_VERSION   VARCHAR2(5 BYTE)   NOT NULL,
  PRODUCT_CODE               VARCHAR2(20 BYTE)  NOT NULL,
  OTF_APPLICABLE_FROM       DATE,
  OTF_APPLICABLE_TO         DATE,
  OTF_TIME_SLAB             VARCHAR2(40 BYTE)
);

CREATE UNIQUE INDEX PK_COMMISSION_PROFILE_OTF ON COMMISSION_PROFILE_OTF
(COMM_PROFILE_OTF_ID);

CREATE UNIQUE INDEX UK_COMMISSION_PROFILE_OTF ON COMMISSION_PROFILE_OTF
(COMM_PROFILE_OTF_ID, PRODUCT_CODE, COMM_PROFILE_SET_VERSION);

INSERT INTO IDS
(ID_YEAR, ID_TYPE, NETWORK_CODE, LAST_NO, LAST_INITIALISED_DATE, FREQUENCY, DESCRIPTION)
VALUES('ALL', 'COMM_OTFID', 'ALL', 1, TIMESTAMP '2019-01-19 13:27:20.000000', 'NA', 'OTF ID');

INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, "TYPE", VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('TRANSACTION_TYPE', 'Transaction Type', 'SYSTEMPRF', 'BOOLEAN', 'True', NULL, NULL, 50, 'Flag to specify transaction type', 'Y', 'Y', 'C2S', 'Flag to specify transaction type', TIMESTAMP '2637-01-24 23:52:13.000000', 'ADMIN', TIMESTAMP '2637-01-24 23:52:13.000000', 'SU0001', NULL, 'Y');

INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, "TYPE", VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('PAYMENT_MODE_ALWD', 'Payment Mode allowed', 'SYSTEMPRF', 'BOOLEAN', 'true', NULL, NULL, 50, 'Flag to Enable/Disable Payment Mode allowed', 'N', 'Y', 'C2S', 'Flag to Enable/Disable Payment Mode allowed', TIMESTAMP '2637-01-24 23:52:13.000000', 'ADMIN', TIMESTAMP '2637-01-24 23:52:13.000000', 'SU0001', NULL, 'Y');


INSERT INTO LOOKUPS
(LOOKUP_CODE, LOOKUP_NAME, LOOKUP_TYPE, STATUS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY)
VALUES('O2C', 'Operator to Channel', 'TRXTP', 'Y', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN');
INSERT INTO LOOKUPS
(LOOKUP_CODE, LOOKUP_NAME, LOOKUP_TYPE, STATUS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY)
VALUES('C2C', 'Channel to Channel', 'TRXTP', 'Y', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN');
INSERT INTO LOOKUPS
(LOOKUP_CODE, LOOKUP_NAME, LOOKUP_TYPE, STATUS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY)
VALUES('ALL', 'Default', 'TRXTP', 'Y', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN');
INSERT INTO LOOKUP_TYPES
(LOOKUP_TYPE, LOOKUP_TYPE_NAME, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, MODIFIED_ALLOWED)
VALUES('TRXTP', 'Transaction Type', TIMESTAMP '2005-10-06 00:00:00.000000', 'ADMIN', TIMESTAMP '2005-10-06 00:00:00.000000', 'ADMIN', 'N');

INSERT INTO page_ui_roles(role_code, page_code) VALUES('CATEGORYMGMT', 'P_SU_CHNL_CAT_MGMT');

Commit;



