alter table voms_vouchers add GENERATED_ON DATE;

alter table voms_vouchers add ENABLED_ON DATE;


alter table voms_vouchers add pre_expiry_date DATE;


alter table voms_vouchers add info_3 VARCHAR(100);

alter table voms_vouchers add info_1 VARCHAR(100);
alter table voms_vouchers add info_2 VARCHAR(100);

commit;


update system_preferences set default_value='DES' where preference_code='VMSPIN_EN_DE_CRYPTION_TYPE';



SET DEFINE OFF;
Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
 Values
   ('VV', 'C2S', 'PRE', 'TYPE PIN SERIALNO', 'com.btsl.pretups.channel.transfer.requesthandler.VoucherEnqConHandler', 
    'Voucher validation Service', 'Voucher validation Service', 'Y', TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'Voucher Query Service', 'Y', 'N', 
    'Y', NULL, 'N', 'NA', 'N', 
    NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,PIN,SUBID,LOGINID,PASSWORD,EXTREFNUM,EXTNWCODE,EXTCODE,LANGUAGE1,LANGUAGE2', 
    'Y');
COMMIT;



Insert into SERVICE_KEYWORDS
   (KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, 
    STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, 
    CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, 
    SUB_KEYWORD, REQUEST_PARAM)
 Values
   ('VV', 'EXTGW', '190', 'VV', 'Voucher Validation', 
    'Y', NULL, NULL, NULL, 'Y', 
    TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'SVK4100299', 
    NULL, NULL) ;
COMMIT;





SET DEFINE OFF;
Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
 Values
   ('VRR', 'C2S', 'PRE', 'TYPE PIN SERIALNO', 'com.btsl.pretups.channel.transfer.requesthandler.VoucherEnqConHandler', 
    'Voucher Reservation Service', 'Voucher Reservation Service', 'Y', TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'Voucher Reservation Service', 'Y', 'N', 
    'Y', NULL, 'N', 'NA', 'N', 
    NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,PIN,SUBID,LOGINID,PASSWORD,EXTREFNUM,EXTNWCODE,EXTCODE,LANGUAGE1,LANGUAGE2', 
    'Y');
COMMIT;


SET DEFINE OFF;

Insert into SERVICE_KEYWORDS
   (KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, 
    STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, 
    CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, 
    SUB_KEYWORD, REQUEST_PARAM)
 Values
   ('VRR', 'EXTGW', '190', 'VRR', 'Voucher Reservation', 
    'Y', NULL, NULL, NULL, 'Y', 
    TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'SVK4107205', 
    NULL, NULL) ;
COMMIT;





SET DEFINE OFF;
Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
 Values
   ('VDR', 'C2S', 'PRE', 'TYPE PIN SERIALNO', 'com.btsl.pretups.channel.transfer.requesthandler.VoucherEnqConHandler', 
    'Voucher Direct Rollback Service', 'Voucher Direct Rollback Service', 'Y', TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'Voucher Direct Rollback', 'Y', 'N', 
    'Y', NULL, 'N', 'NA', 'N', 
    NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,PIN,SUBID,LOGINID,PASSWORD,EXTREFNUM,EXTNWCODE,EXTCODE,LANGUAGE1,LANGUAGE2', 
    'Y');
COMMIT;



SET DEFINE OFF;

Insert into SERVICE_KEYWORDS
   (KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, 
    STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, 
    CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, 
    SUB_KEYWORD, REQUEST_PARAM)
 Values
   ('VDR', 'EXTGW', '190', 'VDR', 'Voucher Direct Rollback Service', 
    'Y', NULL, NULL, NULL, 'Y', 
    TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'SVK4107206', 
    NULL, NULL) ;
COMMIT;

update system_preferences set default_value='com.btsl.pretups.util.clientutils.VHAUtil' where preference_code='OPERATOR_UTIL_C'

commit;




SET DEFINE OFF;
Insert into SERVICE_KEYWORDS
   (KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, 
    STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, 
    CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, 
    SUB_KEYWORD, REQUEST_PARAM)
 Values
   ('VQ', 'EXTGW', '190', 'VQ', 'Voucher Query', 
    'Y', NULL, NULL, NULL, 'Y', 
    TO_DATE('02/12/2015 14:52:09', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', TO_DATE('02/12/2015 14:52:09', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'SVK0000210', 
    NULL, NULL);
COMMIT;


SET DEFINE OFF;
Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
 Values
   ('VQ', 'C2S', 'PRE', 'TYPE PIN SERIALNO', 'com.btsl.pretups.channel.transfer.requesthandler.VoucherEnqConHandler', 
    'Voucher Query Service', 'Voucher Query Service', 'Y', TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'Voucher Query Service', 'Y', 'N', 
    'Y', NULL, 'N', 'NA', 'N', 
    NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,PIN,SUBID,LOGINID,PASSWORD,EXTREFNUM,EXTNWCODE,EXTCODE,LANGUAGE1,LANGUAGE2', 
    'Y');
COMMIT;



SET DEFINE OFF;
Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
 Values
   ('VDC', 'C2S', 'PRE', 'TYPE PIN SERIALNO', 'com.btsl.pretups.channel.transfer.requesthandler.VoucherEnqConHandler', 
    'Voucher Direct Consume Service', 'Voucher Direct Consume Service', 'Y', TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('02/11/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'Voucher Direct Consume', 'Y', 'N', 
    'Y', NULL, 'N', 'NA', 'N', 
    NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,PIN,SUBID,LOGINID,PASSWORD,EXTREFNUM,EXTNWCODE,EXTCODE,LANGUAGE1,LANGUAGE2', 
    'Y');
COMMIT;



SET DEFINE OFF;

Insert into SERVICE_KEYWORDS
   (KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, 
    STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, 
    CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, 
    SUB_KEYWORD, REQUEST_PARAM)
 Values
   ('VDC', 'EXTGW', '190', 'VDC', 'Voucher Direct Consume Service', 
    'Y', NULL, NULL, NULL, 'Y', 
    TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'SVK4107207', 
    NULL, NULL) ;
COMMIT;




SET DEFINE OFF;
Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
 Values
   ('VMSPINEXT', 'C2S', 'ALL', '[KEYWORD][DATA]', 'com.btsl.pretups.channel.transfer.requesthandler.VoucherExpiryDateExtensionController', 
    'Voucher Expiry Date Extension API', 'Voucher Expiry Date Extension API', 'Y', TO_DATE('11/06/2017 06:18:46', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('11/06/2017 06:18:46', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'Voucher Expiry Date Extension API', 'Y', 'N', 
    'Y', 11, 'N', 'NA', 'N', 
    NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,MSISDN', 
    'Y');
COMMIT;



Insert into SERVICE_KEYWORDS
   (KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, 
    STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, 
    CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, 
    SUB_KEYWORD, REQUEST_PARAM)
 Values
   ('VMSPINEXT', 'EXTGW', '190', 'VMSPINEXT', 'Voucher Direct Consume Service', 
    'Y', NULL, NULL, NULL, 'Y', 
    TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', TO_DATE('09/28/2017 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'SVK4107977', 
    NULL, NULL) ;
COMMIT;



SET DEFINE OFF;
Insert into LOOKUPS
   (LOOKUP_CODE, LOOKUP_NAME, LOOKUP_TYPE, STATUS, CREATED_ON, 
    CREATED_BY, MODIFIED_ON, MODIFIED_BY)
 Values
   ('VF', 'VF', 'VTYPE', 'Y', TO_DATE('11/06/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'ADMIN', TO_DATE('11/06/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
COMMIT;

SET DEFINE OFF;
Insert into VOMS_TYPES
   (VOUCHER_TYPE, NAME, SERVICE_TYPE_MAPPING, STATUS, CREATED_ON, 
    CREATED_BY, MODIFIED_ON, MODIFIED_BY, TYPE)
 Values
   ('VF', 'vodafone vouchers', 'RC', 'Y', TO_DATE('09/14/2018 16:59:49', 'MM/DD/YYYY HH24:MI:SS'), 
    'SU0001', TO_DATE('09/14/2018 16:59:49', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'VF');
COMMIT;






