INSERT INTO LOOKUPS
(LOOKUP_CODE, LOOKUP_NAME, LOOKUP_TYPE, STATUS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY)
VALUES('LC', 'Local', 'VMSSEG', 'Y', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN');
INSERT INTO LOOKUPS
(LOOKUP_CODE, LOOKUP_NAME, LOOKUP_TYPE, STATUS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY)
VALUES('NL', 'National', 'VMSSEG', 'Y', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN', TIMESTAMP '2005-11-08 00:00:00.000000', 'ADMIN');
INSERT INTO LOOKUP_TYPES
(LOOKUP_TYPE, LOOKUP_TYPE_NAME, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, MODIFIED_ALLOWED)
VALUES('VMSSEG', 'VMS Segment', TIMESTAMP '2005-10-06 00:00:00.000000', 'ADMIN', TIMESTAMP '2005-10-06 00:00:00.000000', 'ADMIN', 'N');
COMMIT;


CREATE TABLE USER_VOUCHER_SEGMENTS
(
  USER_ID       VARCHAR(15)               NOT NULL,
  VOUCHER_SEGMENT  VARCHAR(10)            NOT NULL,
  STATUS        VARCHAR(1)                DEFAULT 'Y'                   NOT NULL,
  CONSTRAINT PK_USER_VOUCHER_SEGMENT PRIMARY KEY (USER_ID,VOUCHER_SEGMENT)
);

ALTER TABLE VOMS_PRODUCTS
  Add VOUCHER_SEGMENT varchar(2) DEFAULT 'LC';
  
ALTER TABLE VOMS_CATEGORIES
  Add VOUCHER_SEGMENT varchar(2) DEFAULT 'LC';

  ALTER TABLE VOMS_BATCHES
  Add VOUCHER_SEGMENT varchar(2) DEFAULT 'LC';
  
INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('USER_VOUCHERSEGMENT_ALLOWED', 'User voucher segment is allowed', 'SYSTEMPRF', 'BOOLEAN', 'true', NULL, NULL, 50, 'User voucher type is allowed', 'Y', 'Y', 'C2S', 'User voucher segment is allowed', TIMESTAMP '2018-06-16 00:00:00.000000', 'ADMIN', TIMESTAMP '2019-09-11 23:39:40.000000', 'SU0001', NULL, 'Y');


INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('NW_NATIONAL_PREFIX', 'NW_NATIONAL_PREFIX', 'SYSTEMPRF', 'STRING', '99', null, null, 50, 'Prefix for National Voucher', 'N', 'N', 'C2S', 'Prefix for National Voucher', TIMESTAMP '2005-06-16 00:00:00.000000', 'ADMIN', TIMESTAMP '2005-06-17 09:44:51.000000', 'ADMIN', NULL, 'N');


INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('NW_CODE_NW_PREFIX_MAPPING', 'NW_CODE_NW_PREFIX_MAPPING', 'SYSTEMPRF', 'STRING', 'NG=11,PB=12', null, null, 250, 'Network code and network Prefix mapping', 'N', 'N', 'C2S', 'Values can be Comma saperated', TIMESTAMP '2005-06-16 00:00:00.000000', 'ADMIN', TIMESTAMP '2005-06-17 09:44:51.000000', 'ADMIN', NULL, 'N');

INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('VOMS_NATIONAL_LOCAL_PREFIX_ENABLE', 'VOMS_NATIONAL_LOCAL_PREFIX_ENABLE', 'SYSTEMPRF', 'BOOLEAN', 'true', NULL, NULL, 50, 'To enable/disable national/local prefix', 'N', 'N', 'C2S', 'To enable/disable national/local prefix', TIMESTAMP '2018-06-16 00:00:00.000000', 'ADMIN', TIMESTAMP '2019-09-11 23:39:40.000000', 'SU0001', NULL, 'Y');


ALTER TABLE CHANNEL_VOUCHER_ITEMS
  Add VOUCHER_SEGMENT varchar(2) DEFAULT 'LC';
  
  ALTER TABLE CHANNEL_VOUCHER_ITEMS
  Add NETWORK_CODE varchar(2);
  
ALTER TABLE VOMS_VOUCHERS
  Add VOUCHER_SEGMENT varchar(2) DEFAULT 'LC';
