UPDATE SYSTEM_PREFERENCES SET DEFAULT_VALUE = 'US' WHERE PREFERENCE_CODE = 'DEFAULT_COUNTRY';
UPDATE SYSTEM_PREFERENCES SET DEFAULT_VALUE = 'en' WHERE PREFERENCE_CODE = 'DEFAULT_LANGUAGE';




INSERT INTO PROCESS_STATUS (PROCESS_ID, START_DATE, SCHEDULER_STATUS, EXECUTED_UPTO, EXECUTED_ON, EXPIRY_TIME, BEFORE_INTERVAL, DESCRIPTION, NETWORK_CODE, RECORD_COUNT) VALUES('ADR', SYSDATE, 'C', SYSDATE, SYSDATE, 360, 30, 'Automated Dump Report', 'BD', 0);


Update service_type set user_interface_language ='Y' where service_type in ('RC','PPB');