-- Histroy Tables ---------
truncate table NETWORK_PRF_HISTORY;
truncate table CONTROL_PRF_HISTORY;
truncate table BARRED_MSISDN_HISTORY;
truncate table BONUS_HISTORY;
truncate table NETWORKS_HISTORY;
truncate table NETWORK_STOCKS_HISTORY;
truncate table OTA_ADM_TRANSACTION_HISTORY;
truncate table P2P_BUDDIES_HISTORY;
truncate table P2P_SUBSCRIBERS_HISTORY;
truncate table PIN_PASSWORD_HISTORY;
truncate table POS_KEY_HISTORY;
truncate table POSTPAID_CUST_PAY_HISTORY;
truncate table REG_INFO_HISTORY;
truncate table RESTRICTED_MSISDNS_HISTORY;
truncate table SCHEDULED_BATCH_DETAIL_HISTORY;
truncate table SCHEDULED_BATCH_MASTER_HISTORY;
truncate table SERVICE_CLASS_PRF_HISTORY;
truncate table SKEY_TRANSFER_HISTORY;
truncate table SUBSCRIBER_ROUTING_HISTORY;
truncate table SYSTEM_PRF_HISTORY;
truncate table TRANSFER_RULES_HISTORY;
truncate table USER_BALANCES_HISTORY;
truncate table CHNL_TRANSFER_RULES_HISTORY;
-- MIS Tables ---------
truncate table ADJUSTMENTS_MISTMP;
truncate table C2S_BONUSES_MISTMP;
truncate table C2S_TRANSFER_ITEMS_MISTMP;
truncate table C2S_TRANSFERS_MISTMP;
truncate table NETWORK_DAILY_STOCKS;
truncate table USER_DAILY_BALANCES;
truncate table DAILY_C2S_TRANS_DETAILS;
truncate table DAILY_CHNL_TRANS_DETAILS;
truncate table DAILY_CHNL_TRANS_MAIN;
truncate table DAILY_TRANSACTION_SUMMARY;
truncate table MONTHLY_C2S_TRANS_DETAILS;
truncate table MONTHLY_CHNL_TRANS_DETAILS;
truncate table MONTHLY_CHNL_TRANS_MAIN;
truncate table MONTHLY_TRANSACTION_SUMMARY;
truncate table MSISDN_USAGE_SUMMARY;
truncate table C2S_DAILY_FAILURE_DETAILS;
truncate table C2S_DAILY_TRANSACTIONS;
truncate table C2S_RECEIVER_REQUESTS;
truncate table C2S_SUB_DENOM_DETAILS;
truncate table C2S_SUMMARY_DAILY;
truncate table HOURLY_TRANSACTION_SUMMARY;
truncate table P2P_DAILY_FAILURE_DETAILS;
truncate table P2P_RECEIVER_REQUESTS;
truncate table P2P_SUBSCRIBER_SUMMARY;
truncate table P2P_SUBSCRIBERS;
truncate table P2P_SUMMARY_DAILY;
-- Transactions Tables ---------
truncate table C2S_TRANSFER_ITEMS;
truncate table C2S_TRANSFERS;
truncate table CHANNEL_TRANSFERS_ITEMS;
truncate table CHANNEL_TRANSFERS;
truncate table BONUS;
truncate table ADJUSTMENTS;
truncate table TRANSFER_ITEMS;
truncate table SUBSCRIBER_TRANSFERS;
truncate table C2C_BATCH_ITEMS;
truncate table C2C_BATCHES;
truncate table NETWORK_STOCK_TRANS_ITEMS;
truncate table NETWORK_STOCK_TRANSACTIONS;
truncate table POSTPAID_CUST_PAY_MASTER;
truncate table OTA_ADM_TRANSACTION;
truncate table OTA_JOB_DATABASE;
truncate table FOC_BATCH_ITEMS;
truncate table FOC_BATCHES;
truncate table FOC_BONUS_BATCHES;
truncate table FOC_BONUS_DETAILS;
truncate table REDEMPTIONS;
truncate table SUBSCRIBER_CONTROL;
truncate table SUBSCRIBER_ROUTING;
truncate table PIN_PASSWORD_ALERT;
truncate table BATCHES;
truncate table USER_TXNS;
truncate table SKEY_TRANSFERS;
truncate table SCHEDULED_BATCH_DETAIL;
truncate table SCHEDULED_BATCH_MASTER;
truncate table CUST_RET_COUNT;
truncate table FNF_ZERO_BASE_CUSTOMER;
-- Profiles Tables ---------
truncate table PROFILE_OTF_DETAILS;
truncate table ADDNL_COMM_PROFILE_DETAILS;
truncate table COMM_PROFILE_SERVICE_TYPES;
truncate table COMMISSION_PROFILE_DETAILS;
truncate table COMMISSION_PROFILE_PRODUCTS;
truncate table COMMISSION_PROFILE_SET_VERSION;
truncate table COMMISSION_PROFILE_SET;
truncate table TRANSFER_PROFILE;
truncate table TRANSFER_PROFILE_PRODUCTS;
truncate table TRANSFER_RULES;
truncate table CHNL_TRANSFER_RULES_PRODUCTS;
truncate table CHNL_TRANSFER_RULES;
truncate table CHANNEL_GRADES;
truncate table DIVISION_DEPARTMENT;
truncate table BATCH_GEOGRAPHIES;
truncate table FOC_BATCH_GEOGRAPHIES;
truncate table O2C_BATCH_GEOGRAPHIES;
delete from GEOGRAPHICAL_DOMAINS where PARENT_GRPH_DOMAIN_CODE<>'ROOT';
delete from CARD_GROUP_SUB_BON_ACC_DETAILS where CARD_GROUP_SET_ID not in (select CARD_GROUP_SET_ID from CARD_GROUP_SET where IS_DEFAULT='Y');
delete from CARD_GROUP_DETAILS where CARD_GROUP_SET_ID not in (select CARD_GROUP_SET_ID from CARD_GROUP_SET where IS_DEFAULT='Y');
delete from CARD_GROUP_SET_VERSIONS where CARD_GROUP_SET_ID not in (select CARD_GROUP_SET_ID from CARD_GROUP_SET where IS_DEFAULT='Y');
delete from CARD_GROUP_SET where IS_DEFAULT<>'Y';
-- Thresholds Tables ---------
truncate table RESTRICTED_MSISDNS;
truncate table USER_TRANSFER_OTF_COUNT;
truncate table USER_TRANSFER_COUNTS;
truncate table USER_THRESHOLD_COUNTER;
truncate table BARRED_MSISDNS;
truncate table LOW_BALANCE_ALERT;
truncate table USER_EVENT_REMARKS;
truncate table SUBS_ACTIVATION_SUMMARY;
truncate table ACT_BONUS_SUBS_MAPPING;
-- Users Tables ---------
truncate table USER_QUESTIONS_ANSWERS;
truncate table USER_BALANCES;
truncate table USER_DOMAINS;
truncate table USER_OTH_PROFILES;
truncate table USER_PHONES;
truncate table USER_PRODUCT_TYPES;
truncate table USER_ROLES;
truncate table USER_OTP;
truncate table USER_SERVICES;
truncate table CHANNEL_USERS;
delete from USER_GEOGRAPHIES where user_id<>'SU0001';
delete from USERS where user_id not in ('SU0001','SYSTEM');
------------------------------------------------------------ ------------------------
--truncate table BATCH_MASTER;
--truncate table GROUP_TYPE_COUNTERS;
--truncate table JOB_MASTER;
--truncate table P2P_BUDDIES;
--truncate table PORTED_MSISDN;
--truncate table POS_KEYS;
--truncate table REG_INFO;
--truncate table SRV_CLASS_MAPPED_MSISDN;
--truncate table TEMP_DAILY_CHNL_TRANS_MAIN;
--truncate table USER_SIM_SERVICES;
--truncate table voms_vouchers;
