SET DEFINE OFF;
Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
 Values
   ('LSTXTXNSW', 'C2S', 'ALL', 'TYPE MSISDN1 PIN TXNTYPE TXNSUBTYPE C2CINOUT', 'com.btsl.pretups.user.requesthandler.LastXTransferServiceWiseController', 
    'c2s.lasttransferstatus', 'Last X transfer deatils', 'Y', TO_DATE('09/13/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('09/13/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'C2S Last X Transfer deatils', 'N', 'N', 
    'Y', NULL, 'N', 'NA', 'N', 
    NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,MSISDN,IMEI,PIN,LANGUAGE1', 
    'Y');
COMMIT;

SET DEFINE OFF;
Insert into SERVICE_KEYWORDS
   (KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, 
    STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, 
    CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, 
    SUB_KEYWORD, REQUEST_PARAM)
 Values
   ('LSTXTXNSW', 'USSD', '190', 'LSTXTXNSW', 'Last X Transfer Service Wise', 
    'Y', NULL, NULL, NULL, 'Y', 
    TO_DATE('08/31/2016 09:28:16', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', TO_DATE('08/31/2016 09:28:16', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'SVK'||(select LAST_NO+1 from ids where ID_TYPE='SVK'), 
    NULL, NULL);
    
 update ids set last_no=last_no+1 where  ID_TYPE='SVK';

COMMIT;

SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('LAST_X_TRF_DETAILS_DAYS', 'Last X Txn details in last x days', 'SYSTEMPRF', 'INT', '10', 
    0, 30, 50, 'No. of days data to be fetched in last  transfer details. if value is ''0'' then no check on date field.', 'N', 
    'Y', 'C2S', 'No of days data to be fetched in last  transfer details.', TO_DATE('09/19/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('09/19/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SUPERADMIN', NULL, 'Y');
COMMIT;

SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('LAST_X_TRF_DETAILS', 'Last X Txn details', 'SYSTEMPRF', 'INT', '5', 
    3, 10, 50, 'Last x transfer deatils for C2C,C2S,O2C,FOC', 'N', 
    'N', 'C2S', 'Last x transfer deatils for C2C,C2S,O2C,FOC', TO_DATE('09/19/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('09/19/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SUPERADMIN', NULL, 'Y');
COMMIT;
