set define off;

ALTER TABLE SYSTEM_PREFERENCES MODIFY DEFAULT_VALUE VARCHAR2(600);
ALTER TABLE SYSTEM_PRF_HISTORY MODIFY DEFAULT_VALUE VARCHAR2(600);

INSERT INTO SYSTEM_PREFERENCES (PREFERENCE_CODE, NAME, "TYPE", VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE) VALUES('EXTREFNUM_MANDATORY_GATEWAYS', 'EXTREFNUM Mandaory Gateways', 'SYSTEMPRF', 'STRING', 'EXTGW', NULL, NULL, 600, 'Comma Separated Gateway codes for which external reference number is mandatory', 'Y', 'N', 'C2S', 'Comma separated Gateway codes for which external reference number is mandatory', sysdate, 'ADMIN', sysdate, 'SU0001', NULL, 'Y');




COMMIT;