CREATE TABLE VOMS_BUNDLE_MASTER
(
  VOMS_BUNDLE_ID        NUMERIC(20)  PRIMARY KEY ,
  BUNDLE_NAME           VARCHAR(50 ),
  BUNDLE_PREFIX         VARCHAR(5 ),
  RETAIL_PRICE          NUMERIC,
  LAST_BUNDLE_SEQUENCE  NUMERIC(20),
  CREATED_ON            DATE,
  CREATED_BY            VARCHAR(50 ),
  MODIFIED_ON           DATE,
  MODIFIED_BY           VARCHAR(50 ),
  STATUS                VARCHAR(25 )
)
TABLESPACE PRTP_DATA;

CREATE TABLE VOMS_BUNDLE_DETAILS
(
  VOMS_BUNDLE_DETAIL_ID  NUMERIC(20)  PRIMARY KEY,
  VOMS_BUNDLE_ID         NUMERIC(20)  REFERENCES VOMS_BUNDLE_MASTER (VOMS_BUNDLE_ID),
  VOMS_BUNDLE_NAME       VARCHAR(50 ),
  PROFILE_ID             VARCHAR(5 ),
  QUANTITY               NUMERIC,
  CREATED_ON             DATE,
  CREATED_BY             VARCHAR(50 ),
  MODIFIED_ON            DATE,
  MODIFIED_BY            VARCHAR(50 ),
  STATUS                 VARCHAR(25 )
)
TABLESPACE PRTP_DATA;

	 ALTER TABLE VOMS_VOUCHERS
		ADD	 column BUNDLE_ID NUMERIC(20) , 
		ADD	 column  MASTER_SERIAL_NO NUMERIC(20) ;

ALTER TABLE CHANNEL_VOUCHER_ITEMS
	ADD	 column  BUNDLE_ID NUMERIC(20) ,
  ADD	 column  REMARKS VARCHAR(100) ;
	
	

    CREATE TABLE MO_SO_NUMBER
(
  SOMOREFID          VARCHAR(50 ),
  FILENAME           VARCHAR(500 ),
  PROCESSINGDATE     DATE,
  FILEREFERENCE      VARCHAR(50 ),
  MONUMBER           VARCHAR(50 ),
  MOLINENUMBER       VARCHAR(50 ),
  DONUMBER           VARCHAR(50 ),
  WMSREFERENCE       VARCHAR(50 ),
  ORGCODE            VARCHAR(50 ),
  SUBINVENTORY       VARCHAR(50 ),
  ITEMCODE           VARCHAR(50 ),
  QUANTITY           VARCHAR(50 ),
  UOM                VARCHAR(50 ),
  FROMSERIAL_NUMBER  NUMERIC,
  TOSERIAL_NUMBER    NUMERIC,
  SEARCHKEY          NUMERIC,
  ACTUALFROMNO       NUMERIC,
  ACTUALTONO         NUMERIC
)
TABLESPACE PRTP_DATA;

ALTER TABLE LOOKUPS
ALTER COLUMN LOOKUP_CODE TYPE VARCHAR(15);