CREATE TABLE VOMS_BUNDLE_MASTER
(
  VOMS_BUNDLE_ID        NUMBER(20),
  BUNDLE_NAME           VARCHAR2(50 BYTE),
  BUNDLE_PREFIX         VARCHAR2(5 BYTE),
  RETAIL_PRICE          NUMBER,
  LAST_BUNDLE_SEQUENCE  NUMBER(20),
  CREATED_ON            DATE,
  CREATED_BY            VARCHAR2(50 BYTE),
  MODIFIED_ON           DATE,
  MODIFIED_BY           VARCHAR2(50 BYTE),
  STATUS                VARCHAR2(25 BYTE)
)
TABLESPACE PRTP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VOMS_BUNDLE_MASTER_PK ON VOMS_BUNDLE_MASTER
(VOMS_BUNDLE_ID)
LOGGING
TABLESPACE PRTP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE VOMS_BUNDLE_MASTER ADD (
  CONSTRAINT VOMS_BUNDLE_MASTER_PK
 PRIMARY KEY
 (VOMS_BUNDLE_ID)
    USING INDEX 
    TABLESPACE PRTP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


CREATE TABLE VOMS_BUNDLE_DETAILS
(
  VOMS_BUNDLE_DETAIL_ID  NUMBER(20),
  VOMS_BUNDLE_ID         NUMBER(20),
  VOMS_BUNDLE_NAME       VARCHAR2(50 BYTE),
  PROFILE_ID             VARCHAR2(5 BYTE),
  QUANTITY               NUMBER,
  CREATED_ON             DATE,
  CREATED_BY             VARCHAR2(50 BYTE),
  MODIFIED_ON            DATE,
  MODIFIED_BY            VARCHAR2(50 BYTE),
  STATUS                 VARCHAR2(25 BYTE)
)
TABLESPACE PRTP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VOMS_BUNDLE_DETIAL_ID_PK ON VOMS_BUNDLE_DETAILS
(VOMS_BUNDLE_DETAIL_ID)
LOGGING
TABLESPACE PRTP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE VOMS_BUNDLE_DETAILS ADD (
  CONSTRAINT VOMS_BUNDLE_DETIAL_ID_PK
 PRIMARY KEY
 (VOMS_BUNDLE_DETAIL_ID)
    USING INDEX 
    TABLESPACE PRTP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE VOMS_BUNDLE_DETAILS ADD (
  FOREIGN KEY (VOMS_BUNDLE_ID) 
 REFERENCES VOMS_BUNDLE_MASTER (VOMS_BUNDLE_ID));
 
 
 ALTER TABLE VOMS_VOUCHERS
	ADD	( BUNDLE_ID NUMBER(20) , MASTER_SERIAL_NO NUMBER(20) )

ALTER TABLE CHANNEL_VOUCHER_ITEMS
		ADD ( BUNDLE_ID NUMBER(20) , REMARKS VARCHAR2(100) )

    CREATE TABLE MO_SO_NUMBER
(
  SOMOREFID          VARCHAR2(50 BYTE),
  FILENAME           VARCHAR2(500 BYTE),
  PROCESSINGDATE     DATE,
  FILEREFERENCE      VARCHAR2(50 BYTE),
  MONUMBER           VARCHAR2(50 BYTE),
  MOLINENUMBER       VARCHAR2(50 BYTE),
  DONUMBER           VARCHAR2(50 BYTE),
  WMSREFERENCE       VARCHAR2(50 BYTE),
  ORGCODE            VARCHAR2(50 BYTE),
  SUBINVENTORY       VARCHAR2(50 BYTE),
  ITEMCODE           VARCHAR2(50 BYTE),
  QUANTITY           VARCHAR2(50 BYTE),
  UOM                VARCHAR2(50 BYTE),
  FROMSERIAL_NUMBER  NUMBER,
  TOSERIAL_NUMBER    NUMBER,
  SEARCHKEY          NUMBER,
  ACTUALFROMNO       NUMBER,
  ACTUALTONO         NUMBER
)
TABLESPACE PRTP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

 ALTER TABLE LOOKUPS
	MODIFY LOOKUP_CODE VARCHAR2(15);