SET DEFINE OFF;


Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
 Values
   ('MAPP_SESSION_EXPIRY_SEC', 'MApp Expiry Time in Seconds', 'SYSTEMPRF', 'NUMBER', '300', 
    60, 999999999999, 50, 'After how many idle seconds Mobile App Session will be treated as expired', 'N', 
    'Y', 'C2S', NULL, TO_DATE('06/20/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('06/20/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', NULL, 'Y');


COMMIT;