set define off;
INSERT INTO SERVICE_KEYWORDS (KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, SUB_KEYWORD, REQUEST_PARAM)VALUES('OTHERBALAN', 'MAPPGW', '190', 'OTHERBALAN', 'app', 'Y', NULL, NULL, NULL, 'Y', SYSDATE, 'SU0001', SYSDATE, 'SU0001', 'SVK1100201', NULL, 'TYPE,IMEI,MSISDN2,EXTREFNUM');


INSERT INTO SERVICE_TYPE
(SERVICE_TYPE, MODULE, "TYPE", MESSAGE_FORMAT, REQUEST_HANDLER, ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, UNDERPROCESS_CHECK_REQD)
VALUES('CHILDBAR', 'C2S', 'ALL', 'TYPE MSISDN2', 'com.btsl.pretups.requesthandler.BarUserHandler', 'Bar User', 'Bar User', 'Y', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN', 'Bar User', 'N', 'N', 'Y', NULL, 'N', 'NA', 'N', NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,MSISDN', 'Y');


INSERT INTO SERVICE_KEYWORDS
(KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, SUB_KEYWORD, REQUEST_PARAM)
VALUES('CHILDBARUSER', 'MAPPGW', '190', 'CHILDBAR', 'Bar User', 'Y', NULL, NULL, NULL, 'Y', SYSDATE, 'SU0001', SYSDATE, 'SU0001', 'SVK0000039', NULL, 'TYPE,IMEI,MSISDN2,USERTYPE,BARTYPE,MODULE');


INSERT INTO SERVICE_TYPE
(SERVICE_TYPE, MODULE, "TYPE", MESSAGE_FORMAT, REQUEST_HANDLER, ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, UNDERPROCESS_CHECK_REQD)
VALUES('CHILDUNBAR', 'C2S', 'ALL', 'TYPE MSISDN2', 'com.btsl.pretups.requesthandler.UnBarUserHandler', 'UnBar User', 'UnBar User', 'Y', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN', 'UnBar User', 'N', 'N', 'Y', NULL, 'N', 'NA', 'N', NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,MSISDN', 'Y');

INSERT INTO SERVICE_KEYWORDS
(KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, SUB_KEYWORD, REQUEST_PARAM)
VALUES('CHILDUNBARUSER', 'MAPPGW', '190', 'CHILDUNBAR', 'Bar User', 'Y', NULL, NULL, NULL, 'Y', SYSDATE, 'SU0001', SYSDATE, 'SU0001', 'SVK0000148', NULL, 'TYPE,IMEI,MSISDN2,USERTYPE,BARTYPE,MODULE');

INSERT INTO SERVICE_TYPE
(SERVICE_TYPE, MODULE, "TYPE", MESSAGE_FORMAT, REQUEST_HANDLER, ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, UNDERPROCESS_CHECK_REQD)
VALUES('CHLDPINRST', 'C2S', 'ALL', 'TYPE MSISDN2', 'com.btsl.pretups.requesthandler.SelfPinResetController', 'child pin reset', 'child pin reset', 'Y', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN', 'UnBar User', 'N', 'N', 'Y', NULL, 'N', 'NA', 'N', NULL, NULL, NULL, 'TYPE,TXNSTATUS,MESSAGE', 'TYPE,MSISDN', 'Y');

INSERT INTO SERVICE_KEYWORDS
(KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, SUB_KEYWORD, REQUEST_PARAM)
VALUES('CHILDPINRESET', 'MAPPGW', '190', 'CHLDPINRST', 'child pin reset', 'Y', NULL, NULL, NULL, 'Y', SYSDATE, 'SU0001', SYSDATE, 'SU0001', 'SVK0000140', NULL, 'TYPE,IMEI,MSISDN2,EXTREFNUM');


INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, "TYPE", VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('TEMP_PIN_EXPIRY_DURATION', 'Temporary pin expiry duration', 'SYSTEMPRF', 'INT', '1', 1, 24, 50, 'Temporary pin expiry duration in hours', 'Y', 'Y', 'C2S', 'Temporary pin expiry duration in hours', SYSDATE, 'ADMIN', SYSDATE, 'SU0001', NULL, 'Y');



UPDATE MESSAGES_MASTER SET  DEFAULT_MESSAGE='Wrong message format.', MESSAGE1='mclass^2&pid^61:7034:Wrong message format.', MESSAGE2='mclass^2&pid^61:7034:Wrong message format.' WHERE MESSAGE_CODE='7034';

INSERT INTO MESSAGES_MASTER
(MESSAGE_TYPE, MESSAGE_CODE, DEFAULT_MESSAGE, NETWORK_CODE, MESSAGE1, MESSAGE2, MESSAGE3, MCLASS, DESCRIPTION, MESSAGE4, MESSAGE5)
VALUES('ALL', '1100118', 'mclass^2&pid^61:User is not a child of sender', 'BD', 'mclass^2&pid^61:User is not a child of sender', 'mclass^2&pid^61:User is not a child of sender', NULL, 'Y', NULL, NULL, NULL);

INSERT INTO MESSAGES_MASTER
(MESSAGE_TYPE, MESSAGE_CODE, DEFAULT_MESSAGE, NETWORK_CODE, MESSAGE1, MESSAGE2, MESSAGE3, MCLASS, DESCRIPTION, MESSAGE4, MESSAGE5)
VALUES('ALL', '1100119', 'mclass^2&pid^61:User is already unbarred', 'BD', 'mclass^2&pid^61:User is already unbarred', 'mclass^2&pid^61:User is already unbarred', NULL, 'Y', NULL, NULL, NULL);

INSERT INTO MESSAGES_MASTER
(MESSAGE_TYPE, MESSAGE_CODE, DEFAULT_MESSAGE, NETWORK_CODE, MESSAGE1, MESSAGE2, MESSAGE3, MCLASS, DESCRIPTION, MESSAGE4, MESSAGE5)
VALUES('ALL', '1100120', 'mclass^2&pid^61:User barred successfully', 'BD', 'mclass^2&pid^61:User barred successfully', 'mclass^2&pid^61:User barred successfully', NULL, 'Y', NULL, NULL, NULL);

INSERT INTO MESSAGES_MASTER
(MESSAGE_TYPE, MESSAGE_CODE, DEFAULT_MESSAGE, NETWORK_CODE, MESSAGE1, MESSAGE2, MESSAGE3, MCLASS, DESCRIPTION, MESSAGE4, MESSAGE5)
VALUES('ALL', '1100121', 'mclass^2&pid^61:User unbarred successfully', 'BD', 'mclass^2&pid^61:User unbarred successfully', 'mclass^2&pid^61:User unbarred successfully', NULL, 'Y', NULL, NULL, NULL);

INSERT INTO MESSAGES_MASTER
(MESSAGE_TYPE, MESSAGE_CODE, DEFAULT_MESSAGE, NETWORK_CODE, MESSAGE1, MESSAGE2, MESSAGE3, MCLASS, DESCRIPTION, MESSAGE4, MESSAGE5)
VALUES('ALL', '1100122', 'mclass^2&pid^61:User is already barred', 'BD', 'mclass^2&pid^61:User is already barred', 'mclass^2&pid^61:User is already barred', NULL, 'Y', NULL, NULL, NULL);

INSERT INTO MESSAGES_MASTER
(MESSAGE_TYPE, MESSAGE_CODE, DEFAULT_MESSAGE, NETWORK_CODE, MESSAGE1, MESSAGE2, MESSAGE3, MCLASS, DESCRIPTION, MESSAGE4, MESSAGE5)
VALUES('ALL', '1100123', 'mclass^2&pid^61:User barring failed', 'BD', 'mclass^2&pid^61:User barring failed', 'mclass^2&pid^61:User barring failed', NULL, 'Y', NULL, NULL, NULL);

INSERT INTO MESSAGES_MASTER
(MESSAGE_TYPE, MESSAGE_CODE, DEFAULT_MESSAGE, NETWORK_CODE, MESSAGE1, MESSAGE2, MESSAGE3, MCLASS, DESCRIPTION, MESSAGE4, MESSAGE5)
VALUES('ALL', '1100124', 'mclass^2&pid^61:User unbarring failed', 'BD', 'mclass^2&pid^61:User unbarring failed', 'mclass^2&pid^61:User unbarring failed', NULL, 'Y', NULL, NULL, NULL);

INSERT INTO MESSAGES_MASTER
(MESSAGE_TYPE, MESSAGE_CODE, DEFAULT_MESSAGE, NETWORK_CODE, MESSAGE1, MESSAGE2, MESSAGE3, MCLASS, DESCRIPTION, MESSAGE4, MESSAGE5)
VALUES('ALL', '1100125', 'mclass^2&pid^61:Dear user, your temporary PIN is {0}. Please reset it by {1}', 'BD', 'Dear user, your temporary PIN is {0}. Please reset it by {1}', 'Dear user, your temporary PIN is {0}. Please reset it by {1}', NULL, 'Y', NULL, NULL, NULL);

INSERT INTO MESSAGES_MASTER
(MESSAGE_TYPE, MESSAGE_CODE, DEFAULT_MESSAGE, NETWORK_CODE, MESSAGE1, MESSAGE2, MESSAGE3, MCLASS, DESCRIPTION, MESSAGE4, MESSAGE5)
VALUES('ALL', '1100126', 'mclass^2&pid^61:Temporary pin has expired, Please regenerate a new one', 'BD', 'mclass^2&pid^61:Temporary pin has expired, Please regenerate a new one', 'mclass^2&pid^61:Temporary pin has expired, Please regenerate a new one', NULL, 'Y', NULL, NULL, NULL);



-------------------------------------UAT fixes------------------------------------

INSERT INTO SYSTEM_PREFERENCES
(PREFERENCE_CODE, NAME, "TYPE", VALUE_TYPE, DEFAULT_VALUE, MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
VALUES('IMEI_OPTIONAL', 'IMEI optional', 'SYSTEMPRF', 'BOOLEAN', 'true', NULL, NULL, 50, 'IMEI optoianl or not', 'N', 'Y', 'C2S', 'IMEI optoianl or not', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN', NULL, 'Y');


UPDATE SERVICE_KEYWORDS SET REQUEST_PARAM ='TYPE,MSISDN2,EXTREFNUM' WHERE KEYWORD ='OTHERBALAN' AND REQ_INTERFACE_TYPE ='MAPPGW';
UPDATE SERVICE_KEYWORDS SET REQUEST_PARAM ='TYPE,MSISDN2,USERTYPE,BARTYPE,MODULE' WHERE KEYWORD ='CHILDBARUSER' AND REQ_INTERFACE_TYPE ='MAPPGW';
UPDATE SERVICE_KEYWORDS SET REQUEST_PARAM ='TYPE,MSISDN2,USERTYPE,BARTYPE,MODULE' WHERE KEYWORD ='CHILDUNBARUSER' AND REQ_INTERFACE_TYPE ='MAPPGW';
UPDATE SERVICE_KEYWORDS SET REQUEST_PARAM ='TYPE,MSISDN2,EXTREFNUM' WHERE KEYWORD ='CHILDPINRESET' AND REQ_INTERFACE_TYPE ='MAPPGW';


INSERT INTO CATEGORY_REQ_GTW_TYPES
(CATEGORY_CODE, GATEWAY_TYPE)
VALUES('AGENT2', 'MAPPGW');
INSERT INTO CATEGORY_REQ_GTW_TYPES
(CATEGORY_CODE, GATEWAY_TYPE)
VALUES('BCU', 'MAPPGW');
INSERT INTO CATEGORY_REQ_GTW_TYPES
(CATEGORY_CODE, GATEWAY_TYPE)
VALUES('DEALERN1', 'MAPPGW');
INSERT INTO CATEGORY_REQ_GTW_TYPES
(CATEGORY_CODE, GATEWAY_TYPE)
VALUES('DELR', 'MAPPGW');
INSERT INTO CATEGORY_REQ_GTW_TYPES
(CATEGORY_CODE, GATEWAY_TYPE)
VALUES('NWADM', 'MAPPGW');
INSERT INTO CATEGORY_REQ_GTW_TYPES
(CATEGORY_CODE, GATEWAY_TYPE)
VALUES('TPDLR', 'MAPPGW');


COMMIT;