ALTER TABLE IDS MODIFY LAST_NO NUMBER(20);

ALTER TABLE VOMS_BATCHES modify REMARKS varchar2(100);

ALTER TABLE VOMS_BATCHES modify FIRST_APPROVER_REMARKS varchar2(100);

ALTER TABLE VOMS_BATCHES modify SECOND_APPROVER_REMARKS varchar2(100);

ALTER TABLE VOMS_BATCHES modify THIRD_APPROVER_REMARKS varchar2(100);



Insert into LOOKUPS
   (LOOKUP_CODE, LOOKUP_NAME, LOOKUP_TYPE, STATUS, CREATED_ON, 
    CREATED_BY, MODIFIED_ON, MODIFIED_BY)
Values
   ('WH', 'Ware House', 'RSTAT', 'Y', TO_DATE('11/06/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'ADMIN', TO_DATE('11/06/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');

Insert into LOOKUPS
   (LOOKUP_CODE, LOOKUP_NAME, LOOKUP_TYPE, STATUS, CREATED_ON, 
    CREATED_BY, MODIFIED_ON, MODIFIED_BY)
Values
   ('PE', 'Print Enable', 'RSTAT', 'Y', TO_DATE('11/06/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'ADMIN', TO_DATE('11/06/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');

Insert into LOOKUPS
   (LOOKUP_CODE, LOOKUP_NAME, LOOKUP_TYPE, STATUS, CREATED_ON, 
    CREATED_BY, MODIFIED_ON, MODIFIED_BY)
Values
   ('UP', 'Under Procsess', 'VSTAT', 'Y', TO_DATE('12/06/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'ADMIN', TO_DATE('12/06/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
COMMIT;
 

Insert into SERVICE_TYPE
   (SERVICE_TYPE, MODULE, TYPE, MESSAGE_FORMAT, REQUEST_HANDLER, 
    ERROR_KEY, DESCRIPTION, FLEXIBLE, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, NAME, EXTERNAL_INTERFACE, UNREGISTERED_ACCESS_ALLOWED, 
    STATUS, SEQ_NO, USE_INTERFACE_LANGUAGE, GROUP_TYPE, SUB_KEYWORD_APPLICABLE, 
    FILE_PARSER, ERP_HANDLER, RECEIVER_USER_SERVICE_CHECK, RESPONSE_PARAM, REQUEST_PARAM, 
    UNDERPROCESS_CHECK_REQD)
Values
   ('VSCH', 'C2S', 'PRE', 'TYPE FROM_SERIALNO TO_SERIALNO STATUS EXTNWCODE STATE_CHANGE_REASON', 'com.btsl.pretups.channel.transfer.requesthandler.VoucherStatusChangeHandler', 
    'Voucher Status Change Service', 'VOMS Status Changes', 'Y', TO_DATE('01/01/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('01/01/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'Voucher Status Change Service', 'Y', 'Y', 
    'Y', NULL, 'N', 'NA', 'N', 
    'com.btsl.pretups.gateway.parsers.IVRPlainStringParser.java', NULL, NULL, 'TYPE,FROM_SERIALNO,TO_SERIALNO,PRE_STATUS,REQ_STATUS,TXNSTATUS,EXTNWCODE,MESSAGE', 'TYPE,FROM_SERIALNO,TO_SERIALNO,STATUS,EXTNWCODE,STATE_CHANGE_REASON', 
    'Y');

Insert into SERVICE_KEYWORDS
   (KEYWORD, REQ_INTERFACE_TYPE, SERVICE_PORT, SERVICE_TYPE, NAME, 
    STATUS, MENU, SUB_MENU, ALLOWED_VERSION, MODIFY_ALLOWED, 
    CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, SERVICE_KEYWORD_ID, 
    SUB_KEYWORD, REQUEST_PARAM)
Values
   ('VOMSSTCHGREQ', 'EXTGW', '190', 'VSCH', 'VoucherStatusChange', 
    'Y', NULL, NULL, NULL, 'Y', 
    TO_DATE('09/28/2017 17:11:06', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', TO_DATE('09/28/2017 17:11:06', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', 'SVK4100232', 
    NULL, 'TYPE,FROM_SERIALNO,TO_SERIALNO,STATUS,EXTNWCODE,STATE_CHANGE_REASON');
COMMIT;

Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
Values
   ('NET_PREFIX_TO_VALIDATED_FOR_BAR_UNBAR', 'Prefix Validation for Bar UnBar', 'SYSTEMPRF', 'BOOLEAN', 'false', 
    NULL, NULL, 50, 'Prefix Validation for Bar UnBar', 'N', 
    'Y', 'P2P', 'Prefix Validation for Bar UnBar', TO_DATE('06/16/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    TO_DATE('09/11/2005 23:39:40', 'MM/DD/YYYY HH24:MI:SS'), 'SU0001', NULL, 'Y');
COMMIT;


Insert into IDS
   (ID_YEAR, ID_TYPE, NETWORK_CODE, LAST_NO, LAST_INITIALISED_DATE, 
    FREQUENCY, DESCRIPTION)
SELECT ID_YEAR,'VMSSRLCNTR',NETWORK_CODE,0,SYSDATE,'NA','Voucher Generation Serial No Counter' from IDS where ID_TYPE='USERID';
COMMIT;
SET DEFINE OFF;
Insert into SYSTEM_PREFERENCES
   (PREFERENCE_CODE, NAME, TYPE, VALUE_TYPE, DEFAULT_VALUE, 
    MIN_VALUE, MAX_VALUE, MAX_SIZE, DESCRIPTION, MODIFIED_ALLOWED, 
    DISPLAY, MODULE, REMARKS, CREATED_ON, CREATED_BY, 
    MODIFIED_ON, MODIFIED_BY, ALLOWED_VALUES, FIXED_VALUE)
Values
   ('VOMS_IS_MRPID_IN_SERIAL', 'IS MRP ID IN VOUCHER SERIAL NO', 'SYSTEMPRF', 'BOOLEAN', 'false', 
    NULL, NULL, 50, 'IS MRP ID IN VOUCHER SERIAL NO', 'Y', 
    'Y', 'C2S', 'IS MRP ID IN VOUCHER SERIAL NO', sysdate, 'ADMIN', 
    sysdate, 'SU0001', NULL, 'Y');
COMMIT;






