--- 
########################################################
# Author           Date        Remarks
#------------    -----------  ---------
#PreTUPS_RoadMap  25-07-2016    Initial Creation
#
# This file takes care of Rollback patch.
#########################################################
 - name: Copy ansible.log
   connection: local
   command: mv logs/ansible.log ./logs/ansibleRollbackPatch.{{ lookup('pipe', 'date +%d-%m-%Y-%H:%M:%S') }}.log
   run_once: true

 - include: ../../validate/tasks/validateUserEntry.yml

 - include: rollbackWar.yml
   when: isWarPatch == true
 
 - include: rollbackFilePatch.yml
   when: isfilePatch == true or isConstant_Props == true or isLog_Config == true

 - debug: msg="Patch is Rolled Back Successfully."
   when: rollbackPatch|success
   tags:
     - rollbackPatch

 - include: javaRollBack.yml
   when: isJAVAPatch == true

 - include: rollbackCOMPatch.yml
   when: isComPatch == true

 - include: rollbackLinkBasedPatch.yml
   when: isLinkBasedPatch == true