---
apiVersion: v1
kind: Service
metadata:
  name: pretups-login-service
spec:
  selector:
    app: pretups-login
  type: NodePort
  ports:
     -  port: 80
        protocol: TCP
        targetPort: LOGIN_MODULE_CONTAINER_PORT
        nodePort: LOGIN_MODULE_NODEPORT	
