package com.inter.claroca.multicurrency;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-11-17T13:42:42.729+05:30
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "ZWS_TIPO_CAMBIO", 
                  wsdlLocation = "/pretupshome/tomcat8_web/conf/pretups/INFiles/SAP/SAP.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZWSTIPOCAMBIO_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWS_TIPO_CAMBIO");
    public final static QName ZWSTIPOCAMBIO = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWS_TIPO_CAMBIO");
    static {
        URL url = null;
        try {
            url = new URL("/pretupshome/tomcat8_web/conf/pretups/INFiles/SAP/SAP.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZWSTIPOCAMBIO_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}","/pretupshome/tomcat8_web/conf/pretups/INFiles/SAP/SAP.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZWSTIPOCAMBIO_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZWSTIPOCAMBIO_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSTIPOCAMBIO_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZWSTIPOCAMBIO_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZWSTIPOCAMBIO_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZWSTIPOCAMBIO_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ZWSTIPOCAMBIO
     */
    @WebEndpoint(name = "ZWS_TIPO_CAMBIO")
    public ZWSTIPOCAMBIO getZWSTIPOCAMBIO() {
        return super.getPort(ZWSTIPOCAMBIO, ZWSTIPOCAMBIO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSTIPOCAMBIO
     */
    @WebEndpoint(name = "ZWS_TIPO_CAMBIO")
    public ZWSTIPOCAMBIO getZWSTIPOCAMBIO(WebServiceFeature... features) {
        return super.getPort(ZWSTIPOCAMBIO, ZWSTIPOCAMBIO.class, features);
    }

}
