// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.iat.client;

public class CheckStatusRequest {
    protected com.inter.iat.client.CheckStatusParam checkStatusParam;

    public CheckStatusRequest() {
    }

    public CheckStatusRequest(com.inter.iat.client.CheckStatusParam checkStatusParam) {
        this.checkStatusParam = checkStatusParam;
    }

    public com.inter.iat.client.CheckStatusParam getCheckStatusParam() {
        return checkStatusParam;
    }

    public void setCheckStatusParam(com.inter.iat.client.CheckStatusParam checkStatusParam) {
        this.checkStatusParam = checkStatusParam;
    }
}
