// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.iat.client;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class IATHUB_pretupsService_Impl extends com.sun.xml.rpc.client.BasicService implements IATHUB_pretupsService {
    private static final QName serviceName = new QName("http://com/wha/iat/pretups/ws", "IATHUB_pretupsService");
    private static final QName ns1_IATHUB_pretupsSoapPort_QNAME = new QName("http://com/wha/iat/pretups/ws", "IATHUB_pretupsSoapPort");
    private static final Class IATHUB_pretups_PortClass = com.inter.iat.client.IATHUB_pretups.class;

    public IATHUB_pretupsService_Impl() {
        super(serviceName, new QName[] { ns1_IATHUB_pretupsSoapPort_QNAME }, new com.inter.iat.client.IATHUB_pretupsService_SerializerRegistry().getRegistry());

    }

    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_IATHUB_pretupsSoapPort_QNAME) && serviceDefInterface.equals(IATHUB_pretups_PortClass)) {
                return getIATHUB_pretupsSoapPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }

    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(IATHUB_pretups_PortClass)) {
                return getIATHUB_pretupsSoapPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }

    public com.inter.iat.client.IATHUB_pretups getIATHUB_pretupsSoapPort() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_IATHUB_pretupsSoapPort_QNAME));
        handlerChain.setRoles(roles);
        com.inter.iat.client.IATHUB_pretups_Stub stub = new com.inter.iat.client.IATHUB_pretups_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
