// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.iat.client;

import javax.xml.rpc.*;

public interface IATHUB_pretupsService extends javax.xml.rpc.Service {
    public com.inter.iat.client.IATHUB_pretups getIATHUB_pretupsSoapPort() throws ServiceException;
}
