// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.iat.client;

public class QuotationRequestResponse {
    protected com.inter.iat.client.CheckStatusResult _return;

    public QuotationRequestResponse() {
    }

    public QuotationRequestResponse(com.inter.iat.client.CheckStatusResult _return) {
        this._return = _return;
    }

    public com.inter.iat.client.CheckStatusResult get_return() {
        return _return;
    }

    public void set_return(com.inter.iat.client.CheckStatusResult _return) {
        this._return = _return;
    }
}
