// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.iat.client;

public class QuotationRequest {
    protected com.inter.iat.client.QuotationParam quotationParam;

    public QuotationRequest() {
    }

    public QuotationRequest(com.inter.iat.client.QuotationParam quotationParam) {
        this.quotationParam = quotationParam;
    }

    public com.inter.iat.client.QuotationParam getQuotationParam() {
        return quotationParam;
    }

    public void setQuotationParam(com.inter.iat.client.QuotationParam quotationParam) {
        this.quotationParam = quotationParam;
    }
}
