// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.iat.client;

public class RechargeRequest {
    protected com.inter.iat.client.RechargeParam rechargeParam;

    public RechargeRequest() {
    }

    public RechargeRequest(com.inter.iat.client.RechargeParam rechargeParam) {
        this.rechargeParam = rechargeParam;
    }

    public com.inter.iat.client.RechargeParam getRechargeParam() {
        return rechargeParam;
    }

    public void setRechargeParam(com.inter.iat.client.RechargeParam rechargeParam) {
        this.rechargeParam = rechargeParam;
    }
}
