// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.iat.client;

public class RechargeRequestResponse {
    protected com.inter.iat.client.RechargeResult _return;

    public RechargeRequestResponse() {
    }

    public RechargeRequestResponse(com.inter.iat.client.RechargeResult _return) {
        this._return = _return;
    }

    public com.inter.iat.client.RechargeResult get_return() {
        return _return;
    }

    public void set_return(com.inter.iat.client.RechargeResult _return) {
        this._return = _return;
    }
}
