// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.iat.client.holders;

public class CheckStatusResultHolder implements javax.xml.rpc.holders.Holder {
    public com.inter.iat.client.CheckStatusResult value;

    public CheckStatusResultHolder() {
    }

    public CheckStatusResultHolder(com.inter.iat.client.CheckStatusResult myCheckStatusResult) {
        this.value = myCheckStatusResult;
    }
}
