// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.safaricom.safaricomstub;

public interface Mediator extends java.rmi.Remote {
    public com.inter.safaricom.safaricomstub.Response authorizeAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request) throws 
         java.rmi.RemoteException;
    public com.inter.safaricom.safaricomstub.Response balanceAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request) throws 
         java.rmi.RemoteException;
    public com.inter.safaricom.safaricomstub.Response captureAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request) throws 
         java.rmi.RemoteException;
    public com.inter.safaricom.safaricomstub.Response chargeAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request) throws 
         java.rmi.RemoteException;
    public com.inter.safaricom.safaricomstub.Response rechargeAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request) throws 
         java.rmi.RemoteException;
    public com.inter.safaricom.safaricomstub.Response rechargeAmountSFC(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request) throws 
         java.rmi.RemoteException;
    public com.inter.safaricom.safaricomstub.Response refundAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request) throws 
         java.rmi.RemoteException;
    public com.inter.safaricom.safaricomstub.Response transferAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request) throws 
         java.rmi.RemoteException;
}
