// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.safaricom.safaricomstub;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class MediatorService_SerializerRegistry implements SerializerConstants {
    public MediatorService_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "rechargeAmount");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_RequestStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "refundAmountResponse");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_refundAmount_ResponseStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_refundAmount_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "rechargeAmountSFCResponse");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_ResponseStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "authorizeAmountResponse");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_ResponseStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "rechargeAmountSFC");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_RequestStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "captureAmountResponse");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_captureAmount_ResponseStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_captureAmount_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "Response");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Response_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Response.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "balanceAmount");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_balanceAmount_RequestStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_balanceAmount_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "chargeAmount");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_chargeAmount_RequestStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_chargeAmount_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "transferAmount");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_transferAmount_RequestStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_transferAmount_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "refundAmount");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_refundAmount_RequestStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_refundAmount_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "captureAmount");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_captureAmount_RequestStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_captureAmount_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "Request");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Request_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Request.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "balanceAmountResponse");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_balanceAmount_ResponseStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_balanceAmount_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "transferAmountResponse");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_transferAmount_ResponseStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_transferAmount_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "chargeAmountResponse");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_chargeAmount_ResponseStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_chargeAmount_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "rechargeAmountResponse");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_ResponseStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("https://med1-svr:8443/Mediator/", "authorizeAmount");
            CombinedSerializer serializer = new com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_RequestStruct_Name_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_RequestStruct.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
