// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.safaricom.safaricomstub;


public class Mediator_refundAmount_ResponseStruct {
    protected com.inter.safaricom.safaricomstub.Response response;
    
    public Mediator_refundAmount_ResponseStruct() {
    }
    
    public Mediator_refundAmount_ResponseStruct(com.inter.safaricom.safaricomstub.Response response) {
        this.response = response;
    }
    
    public com.inter.safaricom.safaricomstub.Response getResponse() {
        return response;
    }
    
    public void setResponse(com.inter.safaricom.safaricomstub.Response response) {
        this.response = response;
    }
}
