// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.safaricom.safaricomstub;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.client.SenderException;
import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;
import javax.xml.rpc.soap.SOAPFaultException;

public class Mediator_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements com.inter.safaricom.safaricomstub.Mediator {
    
    
    
    /*
     *  public constructor
     */
    public Mediator_Stub(HandlerChain handlerChain) {
        super(handlerChain);
        _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://10.66.39.203:8080/");
    }
    
    
    /*
     *  implementation of refundAmount
     */
    public com.inter.safaricom.safaricomstub.Response refundAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(refundAmount_OPCODE);
            
            com.inter.safaricom.safaricomstub.Mediator_refundAmount_RequestStruct _myMediator_refundAmount_RequestStruct = new com.inter.safaricom.safaricomstub.Mediator_refundAmount_RequestStruct();
            _myMediator_refundAmount_RequestStruct.setIn0(in0);
            _myMediator_refundAmount_RequestStruct.setRequest(request);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_refundAmount_refundAmount_QNAME);
            _bodyBlock.setValue(_myMediator_refundAmount_RequestStruct);
            _bodyBlock.setSerializer(ns1_myMediator_refundAmount_RequestStruct_Name_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.inter.safaricom.safaricomstub.Mediator_refundAmount_ResponseStruct _myMediator_refundAmount_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myMediator_refundAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_refundAmount_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myMediator_refundAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_refundAmount_ResponseStruct)_responseObj;
            }
            
            
            return _myMediator_refundAmount_ResponseStruct.getResponse();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of chargeAmount
     */
    public com.inter.safaricom.safaricomstub.Response chargeAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(chargeAmount_OPCODE);
            
            com.inter.safaricom.safaricomstub.Mediator_chargeAmount_RequestStruct _myMediator_chargeAmount_RequestStruct = new com.inter.safaricom.safaricomstub.Mediator_chargeAmount_RequestStruct();
            _myMediator_chargeAmount_RequestStruct.setIn0(in0);
            _myMediator_chargeAmount_RequestStruct.setRequest(request);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_chargeAmount_chargeAmount_QNAME);
            _bodyBlock.setValue(_myMediator_chargeAmount_RequestStruct);
            _bodyBlock.setSerializer(ns1_myMediator_chargeAmount_RequestStruct_Name_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.inter.safaricom.safaricomstub.Mediator_chargeAmount_ResponseStruct _myMediator_chargeAmount_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myMediator_chargeAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_chargeAmount_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myMediator_chargeAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_chargeAmount_ResponseStruct)_responseObj;
            }
            
            
            return _myMediator_chargeAmount_ResponseStruct.getResponse();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of transferAmount
     */
    public com.inter.safaricom.safaricomstub.Response transferAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(transferAmount_OPCODE);
            
            com.inter.safaricom.safaricomstub.Mediator_transferAmount_RequestStruct _myMediator_transferAmount_RequestStruct = new com.inter.safaricom.safaricomstub.Mediator_transferAmount_RequestStruct();
            _myMediator_transferAmount_RequestStruct.setIn0(in0);
            _myMediator_transferAmount_RequestStruct.setRequest(request);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_transferAmount_transferAmount_QNAME);
            _bodyBlock.setValue(_myMediator_transferAmount_RequestStruct);
            _bodyBlock.setSerializer(ns1_myMediator_transferAmount_RequestStruct_Name_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.inter.safaricom.safaricomstub.Mediator_transferAmount_ResponseStruct _myMediator_transferAmount_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myMediator_transferAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_transferAmount_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myMediator_transferAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_transferAmount_ResponseStruct)_responseObj;
            }
            
            
            return _myMediator_transferAmount_ResponseStruct.getResponse();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of captureAmount
     */
    public com.inter.safaricom.safaricomstub.Response captureAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(captureAmount_OPCODE);
            
            com.inter.safaricom.safaricomstub.Mediator_captureAmount_RequestStruct _myMediator_captureAmount_RequestStruct = new com.inter.safaricom.safaricomstub.Mediator_captureAmount_RequestStruct();
            _myMediator_captureAmount_RequestStruct.setIn0(in0);
            _myMediator_captureAmount_RequestStruct.setRequest(request);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_captureAmount_captureAmount_QNAME);
            _bodyBlock.setValue(_myMediator_captureAmount_RequestStruct);
            _bodyBlock.setSerializer(ns1_myMediator_captureAmount_RequestStruct_Name_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.inter.safaricom.safaricomstub.Mediator_captureAmount_ResponseStruct _myMediator_captureAmount_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myMediator_captureAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_captureAmount_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myMediator_captureAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_captureAmount_ResponseStruct)_responseObj;
            }
            
            
            return _myMediator_captureAmount_ResponseStruct.getResponse();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of balanceAmount
     */
    public com.inter.safaricom.safaricomstub.Response balanceAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(balanceAmount_OPCODE);
            
            com.inter.safaricom.safaricomstub.Mediator_balanceAmount_RequestStruct _myMediator_balanceAmount_RequestStruct = new com.inter.safaricom.safaricomstub.Mediator_balanceAmount_RequestStruct();
            _myMediator_balanceAmount_RequestStruct.setIn0(in0);
            _myMediator_balanceAmount_RequestStruct.setRequest(request);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_balanceAmount_balanceAmount_QNAME);
            _bodyBlock.setValue(_myMediator_balanceAmount_RequestStruct);
            _bodyBlock.setSerializer(ns1_myMediator_balanceAmount_RequestStruct_Name_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.inter.safaricom.safaricomstub.Mediator_balanceAmount_ResponseStruct _myMediator_balanceAmount_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myMediator_balanceAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_balanceAmount_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myMediator_balanceAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_balanceAmount_ResponseStruct)_responseObj;
            }
            
            
            return _myMediator_balanceAmount_ResponseStruct.getResponse();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of rechargeAmountSFC
     */
    public com.inter.safaricom.safaricomstub.Response rechargeAmountSFC(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(rechargeAmountSFC_OPCODE);
            
            com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_RequestStruct _myMediator_rechargeAmountSFC_RequestStruct = new com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_RequestStruct();
            _myMediator_rechargeAmountSFC_RequestStruct.setIn0(in0);
            _myMediator_rechargeAmountSFC_RequestStruct.setRequest(request);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_rechargeAmountSFC_rechargeAmountSFC_QNAME);
            _bodyBlock.setValue(_myMediator_rechargeAmountSFC_RequestStruct);
            _bodyBlock.setSerializer(ns1_myMediator_rechargeAmountSFC_RequestStruct_Name_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_ResponseStruct _myMediator_rechargeAmountSFC_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myMediator_rechargeAmountSFC_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myMediator_rechargeAmountSFC_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_ResponseStruct)_responseObj;
            }
            
            
            return _myMediator_rechargeAmountSFC_ResponseStruct.getResponse();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of authorizeAmount
     */
    public com.inter.safaricom.safaricomstub.Response authorizeAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(authorizeAmount_OPCODE);
            
            com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_RequestStruct _myMediator_authorizeAmount_RequestStruct = new com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_RequestStruct();
            _myMediator_authorizeAmount_RequestStruct.setIn0(in0);
            _myMediator_authorizeAmount_RequestStruct.setRequest(request);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_authorizeAmount_authorizeAmount_QNAME);
            _bodyBlock.setValue(_myMediator_authorizeAmount_RequestStruct);
            _bodyBlock.setSerializer(ns1_myMediator_authorizeAmount_RequestStruct_Name_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_ResponseStruct _myMediator_authorizeAmount_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myMediator_authorizeAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myMediator_authorizeAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_ResponseStruct)_responseObj;
            }
            
            
            return _myMediator_authorizeAmount_ResponseStruct.getResponse();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of rechargeAmount
     */
    public com.inter.safaricom.safaricomstub.Response rechargeAmount(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(rechargeAmount_OPCODE);
            
            com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_RequestStruct _myMediator_rechargeAmount_RequestStruct = new com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_RequestStruct();
            _myMediator_rechargeAmount_RequestStruct.setIn0(in0);
            _myMediator_rechargeAmount_RequestStruct.setRequest(request);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_rechargeAmount_rechargeAmount_QNAME);
            _bodyBlock.setValue(_myMediator_rechargeAmount_RequestStruct);
            _bodyBlock.setSerializer(ns1_myMediator_rechargeAmount_RequestStruct_Name_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_ResponseStruct _myMediator_rechargeAmount_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myMediator_rechargeAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myMediator_rechargeAmount_ResponseStruct =
                    (com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_ResponseStruct)_responseObj;
            }
            
            
            return _myMediator_rechargeAmount_ResponseStruct.getResponse();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case refundAmount_OPCODE:
                _deserialize_refundAmount(bodyReader, deserializationContext, state);
                break;
            case chargeAmount_OPCODE:
                _deserialize_chargeAmount(bodyReader, deserializationContext, state);
                break;
            case transferAmount_OPCODE:
                _deserialize_transferAmount(bodyReader, deserializationContext, state);
                break;
            case captureAmount_OPCODE:
                _deserialize_captureAmount(bodyReader, deserializationContext, state);
                break;
            case balanceAmount_OPCODE:
                _deserialize_balanceAmount(bodyReader, deserializationContext, state);
                break;
            case rechargeAmountSFC_OPCODE:
                _deserialize_rechargeAmountSFC(bodyReader, deserializationContext, state);
                break;
            case authorizeAmount_OPCODE:
                _deserialize_authorizeAmount(bodyReader, deserializationContext, state);
                break;
            case rechargeAmount_OPCODE:
                _deserialize_rechargeAmount(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the refundAmount operation.
     */
    private void _deserialize_refundAmount(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myMediator_refundAmount_ResponseStructObj =
            ns1_myMediator_refundAmount_ResponseStruct_Name_LiteralSerializer.deserialize(ns1_refundAmount_refundAmountResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_refundAmount_refundAmountResponse_QNAME);
        bodyBlock.setValue(myMediator_refundAmount_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the chargeAmount operation.
     */
    private void _deserialize_chargeAmount(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myMediator_chargeAmount_ResponseStructObj =
            ns1_myMediator_chargeAmount_ResponseStruct_Name_LiteralSerializer.deserialize(ns1_chargeAmount_chargeAmountResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_chargeAmount_chargeAmountResponse_QNAME);
        bodyBlock.setValue(myMediator_chargeAmount_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the transferAmount operation.
     */
    private void _deserialize_transferAmount(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myMediator_transferAmount_ResponseStructObj =
            ns1_myMediator_transferAmount_ResponseStruct_Name_LiteralSerializer.deserialize(ns1_transferAmount_transferAmountResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_transferAmount_transferAmountResponse_QNAME);
        bodyBlock.setValue(myMediator_transferAmount_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the captureAmount operation.
     */
    private void _deserialize_captureAmount(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myMediator_captureAmount_ResponseStructObj =
            ns1_myMediator_captureAmount_ResponseStruct_Name_LiteralSerializer.deserialize(ns1_captureAmount_captureAmountResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_captureAmount_captureAmountResponse_QNAME);
        bodyBlock.setValue(myMediator_captureAmount_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the balanceAmount operation.
     */
    private void _deserialize_balanceAmount(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myMediator_balanceAmount_ResponseStructObj =
            ns1_myMediator_balanceAmount_ResponseStruct_Name_LiteralSerializer.deserialize(ns1_balanceAmount_balanceAmountResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_balanceAmount_balanceAmountResponse_QNAME);
        bodyBlock.setValue(myMediator_balanceAmount_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the rechargeAmountSFC operation.
     */
    private void _deserialize_rechargeAmountSFC(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myMediator_rechargeAmountSFC_ResponseStructObj =
            ns1_myMediator_rechargeAmountSFC_ResponseStruct_Name_LiteralSerializer.deserialize(ns1_rechargeAmountSFC_rechargeAmountSFCResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_rechargeAmountSFC_rechargeAmountSFCResponse_QNAME);
        bodyBlock.setValue(myMediator_rechargeAmountSFC_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the authorizeAmount operation.
     */
    private void _deserialize_authorizeAmount(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myMediator_authorizeAmount_ResponseStructObj =
            ns1_myMediator_authorizeAmount_ResponseStruct_Name_LiteralSerializer.deserialize(ns1_authorizeAmount_authorizeAmountResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_authorizeAmount_authorizeAmountResponse_QNAME);
        bodyBlock.setValue(myMediator_authorizeAmount_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the rechargeAmount operation.
     */
    private void _deserialize_rechargeAmount(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myMediator_rechargeAmount_ResponseStructObj =
            ns1_myMediator_rechargeAmount_ResponseStruct_Name_LiteralSerializer.deserialize(ns1_rechargeAmount_rechargeAmountResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_rechargeAmount_rechargeAmountResponse_QNAME);
        bodyBlock.setValue(myMediator_rechargeAmount_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    
    
    protected java.lang.String _getDefaultEnvelopeEncodingStyle() {
        return null;
    }
    
    public java.lang.String _getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    public java.lang.String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(java.lang.String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected void _preHandlingHook(StreamingSenderState state) throws Exception {
        super._preHandlingHook(state);
    }
    
    
    protected boolean _preRequestSendingHook(StreamingSenderState state) throws Exception {
        boolean bool = false;
        bool = super._preRequestSendingHook(state);
        return bool;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        ns1_myMediator_authorizeAmount_RequestStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_RequestStruct.class, ns1_authorizeAmount_TYPE_QNAME);
        ns1_myMediator_authorizeAmount_ResponseStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_authorizeAmount_ResponseStruct.class, ns1_authorizeAmountResponse_TYPE_QNAME);
        ns1_myMediator_captureAmount_ResponseStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_captureAmount_ResponseStruct.class, ns1_captureAmountResponse_TYPE_QNAME);
        ns1_myMediator_balanceAmount_RequestStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_balanceAmount_RequestStruct.class, ns1_balanceAmount_TYPE_QNAME);
        ns1_myMediator_captureAmount_RequestStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_captureAmount_RequestStruct.class, ns1_captureAmount_TYPE_QNAME);
        ns1_myMediator_rechargeAmountSFC_ResponseStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_ResponseStruct.class, ns1_rechargeAmountSFCResponse_TYPE_QNAME);
        ns1_myMediator_refundAmount_RequestStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_refundAmount_RequestStruct.class, ns1_refundAmount_TYPE_QNAME);
        ns1_myMediator_balanceAmount_ResponseStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_balanceAmount_ResponseStruct.class, ns1_balanceAmountResponse_TYPE_QNAME);
        ns1_myMediator_rechargeAmount_ResponseStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_ResponseStruct.class, ns1_rechargeAmountResponse_TYPE_QNAME);
        ns1_myMediator_chargeAmount_RequestStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_chargeAmount_RequestStruct.class, ns1_chargeAmount_TYPE_QNAME);
        ns1_myMediator_rechargeAmount_RequestStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_rechargeAmount_RequestStruct.class, ns1_rechargeAmount_TYPE_QNAME);
        ns1_myMediator_rechargeAmountSFC_RequestStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_rechargeAmountSFC_RequestStruct.class, ns1_rechargeAmountSFC_TYPE_QNAME);
        ns1_myMediator_transferAmount_ResponseStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_transferAmount_ResponseStruct.class, ns1_transferAmountResponse_TYPE_QNAME);
        ns1_myMediator_refundAmount_ResponseStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_refundAmount_ResponseStruct.class, ns1_refundAmountResponse_TYPE_QNAME);
        ns1_myMediator_chargeAmount_ResponseStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_chargeAmount_ResponseStruct.class, ns1_chargeAmountResponse_TYPE_QNAME);
        ns1_myMediator_transferAmount_RequestStruct_Name_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.inter.safaricom.safaricomstub.Mediator_transferAmount_RequestStruct.class, ns1_transferAmount_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName _portName = new QName("https://med1-svr:8443/Mediator/", "Mediator");
    private static final int refundAmount_OPCODE = 0;
    private static final int chargeAmount_OPCODE = 1;
    private static final int transferAmount_OPCODE = 2;
    private static final int captureAmount_OPCODE = 3;
    private static final int balanceAmount_OPCODE = 4;
    private static final int rechargeAmountSFC_OPCODE = 5;
    private static final int authorizeAmount_OPCODE = 6;
    private static final int rechargeAmount_OPCODE = 7;
    private static final javax.xml.namespace.QName ns1_refundAmount_refundAmount_QNAME = new QName("https://med1-svr:8443/Mediator/", "refundAmount");
    private static final javax.xml.namespace.QName ns1_refundAmount_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "refundAmount");
    private CombinedSerializer ns1_myMediator_refundAmount_RequestStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_refundAmount_refundAmountResponse_QNAME = new QName("https://med1-svr:8443/Mediator/", "refundAmountResponse");
    private static final javax.xml.namespace.QName ns1_refundAmountResponse_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "refundAmountResponse");
    private CombinedSerializer ns1_myMediator_refundAmount_ResponseStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_chargeAmount_chargeAmount_QNAME = new QName("https://med1-svr:8443/Mediator/", "chargeAmount");
    private static final javax.xml.namespace.QName ns1_chargeAmount_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "chargeAmount");
    private CombinedSerializer ns1_myMediator_chargeAmount_RequestStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_chargeAmount_chargeAmountResponse_QNAME = new QName("https://med1-svr:8443/Mediator/", "chargeAmountResponse");
    private static final javax.xml.namespace.QName ns1_chargeAmountResponse_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "chargeAmountResponse");
    private CombinedSerializer ns1_myMediator_chargeAmount_ResponseStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_transferAmount_transferAmount_QNAME = new QName("https://med1-svr:8443/Mediator/", "transferAmount");
    private static final javax.xml.namespace.QName ns1_transferAmount_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "transferAmount");
    private CombinedSerializer ns1_myMediator_transferAmount_RequestStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_transferAmount_transferAmountResponse_QNAME = new QName("https://med1-svr:8443/Mediator/", "transferAmountResponse");
    private static final javax.xml.namespace.QName ns1_transferAmountResponse_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "transferAmountResponse");
    private CombinedSerializer ns1_myMediator_transferAmount_ResponseStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_captureAmount_captureAmount_QNAME = new QName("https://med1-svr:8443/Mediator/", "captureAmount");
    private static final javax.xml.namespace.QName ns1_captureAmount_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "captureAmount");
    private CombinedSerializer ns1_myMediator_captureAmount_RequestStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_captureAmount_captureAmountResponse_QNAME = new QName("https://med1-svr:8443/Mediator/", "captureAmountResponse");
    private static final javax.xml.namespace.QName ns1_captureAmountResponse_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "captureAmountResponse");
    private CombinedSerializer ns1_myMediator_captureAmount_ResponseStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_balanceAmount_balanceAmount_QNAME = new QName("https://med1-svr:8443/Mediator/", "balanceAmount");
    private static final javax.xml.namespace.QName ns1_balanceAmount_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "balanceAmount");
    private CombinedSerializer ns1_myMediator_balanceAmount_RequestStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_balanceAmount_balanceAmountResponse_QNAME = new QName("https://med1-svr:8443/Mediator/", "balanceAmountResponse");
    private static final javax.xml.namespace.QName ns1_balanceAmountResponse_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "balanceAmountResponse");
    private CombinedSerializer ns1_myMediator_balanceAmount_ResponseStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_rechargeAmountSFC_rechargeAmountSFC_QNAME = new QName("https://med1-svr:8443/Mediator/", "rechargeAmountSFC");
    private static final javax.xml.namespace.QName ns1_rechargeAmountSFC_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "rechargeAmountSFC");
    private CombinedSerializer ns1_myMediator_rechargeAmountSFC_RequestStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_rechargeAmountSFC_rechargeAmountSFCResponse_QNAME = new QName("https://med1-svr:8443/Mediator/", "rechargeAmountSFCResponse");
    private static final javax.xml.namespace.QName ns1_rechargeAmountSFCResponse_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "rechargeAmountSFCResponse");
    private CombinedSerializer ns1_myMediator_rechargeAmountSFC_ResponseStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_authorizeAmount_authorizeAmount_QNAME = new QName("https://med1-svr:8443/Mediator/", "authorizeAmount");
    private static final javax.xml.namespace.QName ns1_authorizeAmount_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "authorizeAmount");
    private CombinedSerializer ns1_myMediator_authorizeAmount_RequestStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_authorizeAmount_authorizeAmountResponse_QNAME = new QName("https://med1-svr:8443/Mediator/", "authorizeAmountResponse");
    private static final javax.xml.namespace.QName ns1_authorizeAmountResponse_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "authorizeAmountResponse");
    private CombinedSerializer ns1_myMediator_authorizeAmount_ResponseStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_rechargeAmount_rechargeAmount_QNAME = new QName("https://med1-svr:8443/Mediator/", "rechargeAmount");
    private static final javax.xml.namespace.QName ns1_rechargeAmount_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "rechargeAmount");
    private CombinedSerializer ns1_myMediator_rechargeAmount_RequestStruct_Name_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_rechargeAmount_rechargeAmountResponse_QNAME = new QName("https://med1-svr:8443/Mediator/", "rechargeAmountResponse");
    private static final javax.xml.namespace.QName ns1_rechargeAmountResponse_TYPE_QNAME = new QName("https://med1-svr:8443/Mediator/", "rechargeAmountResponse");
    private CombinedSerializer ns1_myMediator_rechargeAmount_ResponseStruct_Name_LiteralSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "https://med1-svr:8443/Mediator/"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
