// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.safaricom.safaricomstub;


public class Mediator_refundAmount_RequestStruct {
    protected com.inter.safaricom.safaricomstub.Request in0;
    protected com.inter.safaricom.safaricomstub.Request request;
    
    public Mediator_refundAmount_RequestStruct() {
    }
    
    public Mediator_refundAmount_RequestStruct(com.inter.safaricom.safaricomstub.Request in0, com.inter.safaricom.safaricomstub.Request request) {
        this.in0 = in0;
        this.request = request;
    }
    
    public com.inter.safaricom.safaricomstub.Request getIn0() {
        return in0;
    }
    
    public void setIn0(com.inter.safaricom.safaricomstub.Request in0) {
        this.in0 = in0;
    }
    
    public com.inter.safaricom.safaricomstub.Request getRequest() {
        return request;
    }
    
    public void setRequest(com.inter.safaricom.safaricomstub.Request request) {
        this.request = request;
    }
}
