// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.safaricom.safaricomstub;

import javax.xml.rpc.*;

public interface MediatorService extends javax.xml.rpc.Service {
    public com.inter.safaricom.safaricomstub.Mediator getMediator() throws ServiceException;
}
