// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.safaricom.safaricomstub;


public class Request {
    protected int accountID;
    protected long amount;
    protected java.lang.String msisdn;
    protected java.lang.String opermsisdn;
    protected java.lang.String password;
    protected java.lang.String terminalID;
    protected java.lang.String transactionID;
    protected java.lang.String userID;
    
    public Request() {
    }
    
    public Request(int accountID, long amount, java.lang.String msisdn, java.lang.String opermsisdn, java.lang.String password, java.lang.String terminalID, java.lang.String transactionID, java.lang.String userID) {
        this.accountID = accountID;
        this.amount = amount;
        this.msisdn = msisdn;
        this.opermsisdn = opermsisdn;
        this.password = password;
        this.terminalID = terminalID;
        this.transactionID = transactionID;
        this.userID = userID;
    }
    
    public int getAccountID() {
        return accountID;
    }
    
    public void setAccountID(int accountID) {
        this.accountID = accountID;
    }
    
    public long getAmount() {
        return amount;
    }
    
    public void setAmount(long amount) {
        this.amount = amount;
    }
    
    public java.lang.String getMsisdn() {
        return msisdn;
    }
    
    public void setMsisdn(java.lang.String msisdn) {
        this.msisdn = msisdn;
    }
    
    public java.lang.String getOpermsisdn() {
        return opermsisdn;
    }
    
    public void setOpermsisdn(java.lang.String opermsisdn) {
        this.opermsisdn = opermsisdn;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getTerminalID() {
        return terminalID;
    }
    
    public void setTerminalID(java.lang.String terminalID) {
        this.terminalID = terminalID;
    }
    
    public java.lang.String getTransactionID() {
        return transactionID;
    }
    
    public void setTransactionID(java.lang.String transactionID) {
        this.transactionID = transactionID;
    }
    
    public java.lang.String getUserID() {
        return userID;
    }
    
    public void setUserID(java.lang.String userID) {
        this.userID = userID;
    }
}
