// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.inter.safaricom.safaricomstub;


public class Response {
    protected java.lang.String transactionID;
    protected java.lang.String terminalID;
    protected java.lang.String opermsisdn;
    protected java.lang.String msisdn;
    protected int accountID;
    protected long amount;
    protected int status;
    
    public Response() {
    }
    
    public Response(java.lang.String transactionID, java.lang.String terminalID, java.lang.String opermsisdn, java.lang.String msisdn, int accountID, long amount, int status) {
        this.transactionID = transactionID;
        this.terminalID = terminalID;
        this.opermsisdn = opermsisdn;
        this.msisdn = msisdn;
        this.accountID = accountID;
        this.amount = amount;
        this.status = status;
    }
    
    public java.lang.String getTransactionID() {
        return transactionID;
    }
    
    public void setTransactionID(java.lang.String transactionID) {
        this.transactionID = transactionID;
    }
    
    public java.lang.String getTerminalID() {
        return terminalID;
    }
    
    public void setTerminalID(java.lang.String terminalID) {
        this.terminalID = terminalID;
    }
    
    public java.lang.String getOpermsisdn() {
        return opermsisdn;
    }
    
    public void setOpermsisdn(java.lang.String opermsisdn) {
        this.opermsisdn = opermsisdn;
    }
    
    public java.lang.String getMsisdn() {
        return msisdn;
    }
    
    public void setMsisdn(java.lang.String msisdn) {
        this.msisdn = msisdn;
    }
    
    public int getAccountID() {
        return accountID;
    }
    
    public void setAccountID(int accountID) {
        this.accountID = accountID;
    }
    
    public long getAmount() {
        return amount;
    }
    
    public void setAmount(long amount) {
        this.amount = amount;
    }
    
    public int getStatus() {
        return status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
}
